### ISSUE TITLE
Parsing module without explicit module declaration fails

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#10]
**Original reporter**: _sol@<hidden>_

If a module does not contain an explicit module declaration
**and** starts with

``` haskell
-- | some comment
```

then parsing fails.

This is a bug in GHC's parser.  It is only triggered if
[Opt_Haddock](http://www.haskell.org/ghc/docs/latest/html/libraries/ghc/DynFlags.html#v:Opt_Haddock) is used.
### Details

GHC's parser has a rule for Haddock comments on module headers.
When the parser sees the Haddock comment at the
beginning it then wants the next declaration to be a module header
(the grammar has an S/R conflict because of this).

One possible solution could be to parse Haddock comments separately from the Haskell code, and match up Haddock comments with AST nodes in a later step.
### Steps to reproduce

``` haskell
-- | Hi there
main = print "Hello World!"
```

Running

``` haskell
$ haddock Main.hs
```

fails with:

``` haskell
Main.hs:2:1: parse error on input `main'
```

In contrast both of the following example work just fine:

``` haskell
{-
Hi there
-}
main = print "Hello World!"
```

``` haskell
foo = 23
-- | Hi there
main = print "Hello World!"
```

**Comment by Kleidukos** [comment]
Fixed in 2.26.1
