### ISSUE TITLE
Weird order of document generated.

### ISSUE THREAD

**Issue by Magicloud** [haskell/haddock#1001]
I have a source file in the format of:

```
{- |
cairo_t
Another few lines
-}
newtype Context = Context (C2HSImp.ForeignPtr (Context))
withContext :: Context -> (C2HSImp.Ptr Context -> IO b) -> IO b 
withContext (Context fptr) = C2HSImp.withForeignPtr fptr 
{-# LINE 91 "src/Graphics/Cairo/Types.chs" #-}

outContext :: Ptr Context -> IO Context
outContext = fmap Context . newForeignPtr cairo_destroy

-- Another block in the same format (haddock, newtype, functions)
```

But in the html document generated by haddock, I got:

```
outContext
  DOC of cairo_t
anotherFunX
  ANOTHER DOC A
anotherFunY
newtype Context
  ANOTHER DOC B
```

Not only the order of `Context` and `outContext` are changed, but also haddock grabs docs from other parts below to, fill the gap. And `withContext`, is at a place far below.

**Comment by harpocrates** [comment]
This is more of a problem in the GHC parser. In a nutshell:

  * top-level doc comments get parsed as standalone declarations when `-haddock` is enabled
  * Haddock tries to associate these comments with declarations by looking at positional information (eg. if there is a doc comment, attach it to the declaration with the smallest source position greater than the doc comment's own source position)
  * `LINE` pragmas mess at the lowest level with the position information that GHC builds up

While I agree that the existing behaviour is not good, I think the real blame lies in the program/human that generated the `LINE` pragmas in the first place. Are the `LINE` pragmas being generated by `hsc2hs`? If so, perhaps this counts as an `hsc2hs` bug too (and it should be much easier to fix on that end).

**Comment by Magicloud** [comment]
Did some test. I think I can confirm that removing those `LINE`s fixes the issue.

**Comment by harpocrates** [comment]
I don't really think that `c2hs` should necessarily suppress `LINE` pragmas, but it should at least put the right locations in them.

**Comment by harpocrates** [comment]
Actually, I think we already have an issue for this. Closing in favour of https://github.com/haskell/haddock/issues/441. Feel free to re-open if you think otherwise.
