### ISSUE TITLE
Constructors with existential quantification are rendered poorly

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#1002]
If you run Haddock on the following code:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
module Foo where

data Some f = forall a. Some (f a)
```

This is how it shows up:

![haddock](https://user-images.githubusercontent.com/2364661/51612273-1cc1f100-1eef-11e9-901a-4034b9dbd581.png)

Notice how the `a` in `Some (f a)` is completely unbound. This really ought to be rendered as `forall a. Some (f a)`.

**Comment by harpocrates** [comment]
Thanks for the bug report! Should be fixed in https://github.com/haskell/haddock/pull/1003 (which I'll merge when CI is green).
