### ISSUE TITLE
Some links cannot be recognized.

### ISSUE THREAD

**Issue by Magicloud** [haskell/haddock#1011]
`[CAIRO_STATUS_WRITE_ERROR](https://www.cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-WRITE-ERROR:CAPS)` cannot be recognized as link and is shown as is in result HTML.

**Comment by harpocrates** [comment]
What version of Haddock are you using? Also, are you sure you haven't added a line break somewhere in the URL? I can't seem to replicate this (either on HEAD, haddock released with 8.6.3, or haddock released with 8.4.4):

 ```haskell
module Foo where

-- | A [CAIRO_STATUS_WRITE_ERROR](https://www.cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-WRITE-ERROR:CAPS)
bar :: Int
bar = 9
```

turns into

<img width="860" alt="screen shot 2019-01-30 at 9 00 12 am" src="https://user-images.githubusercontent.com/10766081/51998422-7ab18400-246d-11e9-9785-2369ef2e9bc0.png">

(And the link does go to the right place.)

**Comment by harpocrates** [comment]
Yeah, this is a known bug around lines that start with links. Do you mind if I close in favor of https://github.com/haskell/haddock/issues/774?

Fixing this might not even be too difficult - I haven't looked at that part of the parser recently.

**Comment by Magicloud** [comment]
Sure. No problem. Knowing the cause at least help to get my doc fixed.
