### ISSUE TITLE
Question about list

### ISSUE THREAD

**Issue by Magicloud** [haskell/haddock#1013]
[Here](https://haskell-haddock.readthedocs.io/en/latest/markup.html#itemized-and-enumerated-lists) seems telling me that, I can have a, kind of "short description" for list item, in format

```
{-|
* Title
This is the first parameter.
-}
```

But when this is converted into HTML, all lines like this are joined together since newline means nothing in HTML.

```
<ul>
<li>Title
This is the first parameter.</li>
</ul>
```

I know there is 4-space indent nest, but this still confuses me. Since following example in former link uses the word "above".

```
{-|
* Beginning of list
This belongs to the list above!

    > nested
    > bird
    > tracks

    * Next list
    More of the indented list.

        * Deeper

            @
            even code blocks work
            @

            * Deeper

                    1. Even deeper!
                    2. No newline separation even in indented lists.
-}
```

**Comment by harpocrates** [comment]
> I know there is 4-space indent nest, but this still confuses me. Since following example in former link uses the word "above".

I think the use of "above" in the docs is referring to the layout of the Haddock comment, not to what its output will look like.

> But when this is converted into HTML, all lines like this are joined together since newline means nothing in HTML.

You can force a newline in the output by adding _two_ newlines in the Haddock (although then you also have to indent the second line by 4 spaces):

```haskell
{-|
*   Title

    This is the first parameter.
-}
```

<img width="200" alt="screen shot 2019-02-01 at 9 03 50 am" src="https://user-images.githubusercontent.com/10766081/52137803-576b0e00-2600-11e9-826a-31fa798516a8.png">

However, if you are looking for short descriptions attached to bullets, perhaps you really want definition lists?

```haskell
{-|
[Title1]
    This is the first point.
[Title2]
    This is the second point.
-}
```

<img width="197" alt="screen shot 2019-02-01 at 9 03 59 am" src="https://user-images.githubusercontent.com/10766081/52137853-74074600-2600-11e9-9a5e-b2f4014cc1d6.png">
