### ISSUE TITLE
Wildcard bundled pattern synonyms?

### ISSUE THREAD

**Issue by vdukhovni** [haskell/haddock#1024]
When a module exports **all** the pattern synonyms for a given type as below, haddock does not seem to produce documentation for the implicit bundled pattern constructors.  Exporting them explicitly, one by one, works, but is tedious.  I'm using the haddock with GHC 8.6.3, is that too old? Is this not yet supported?
```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}
module Foo (Foo(..)) where
newtype Foo = Foo { unFoo :: Int } deriving (Eq, Enum)
-- | Pattern X
pattern X :: Foo
pattern X = Foo 1
-- | Pattern Y
pattern Y :: Foo
pattern Y = Foo 2
```

**Comment by harpocrates** [comment]
This actually is a GHC feature/bug, not a Haddock one. `Foo(..)` does _not_ export bundled patterns. The suggested workaround is:

```haskell
module Foo (Foo(.., X, Y)) where
newtype Foo = Foo { unFoo :: Int } deriving (Eq, Enum)
-- | Pattern X
pattern X :: Foo
pattern X = Foo 1
-- | Pattern Y
pattern Y :: Foo
pattern Y = Foo 2
```

If you ever wonder what GHC is exporting for a module, you can use `--show-iface` and look for the `exports:` section:

<pre>
$ ghc Foo.hs
$ ghc --show-iface Foo.hi
Magic: Wanted 33214052,
       got    33214052
Version: Wanted [8, 0, 6, 2],
         got    [8, 0, 6, 2]
Way: Wanted [],
     got    []
interface Foo 8062
  interface hash: 4a02ba2fe6b72d9960831cfb66ef12f3
  ABI hash: 02988b96b36f703e1fbf070366e4cee0
  export-list hash: 4815eab50bbc11a6ff8a07120d351fa6
  orphan hash: 693e9af84d3dfcc71e640e005bdc5e2e
  flag hash: 6a483171080514b480536d54214ce23b
  opt_hash: d0a78e7b344f95c7406be35c9b75e196
  hpc_hash: 93b885adfe0da089cdf634904fd59f71
  plugin_hash: ad164012d6b1e14942349d58b1132007
  sig of: Nothing
  used TH splices: False
  where
<strong>exports:
  Foo{Foo unFoo}</strong>
module dependencies:
package dependencies: base-4.12.0.0 ghc-prim-0.5.3
                      integer-gmp-1.0.2.0
orphans: GHC.Float GHC.Base
family instance modules: Control.Applicative Data.Functor.Const
                         Data.Functor.Identity Data.Monoid Data.Semigroup.Internal
                         GHC.Generics GHC.IO.Exception
import  -/  GHC.Enum 51972331265459b2ecdf2bf83fce4045
import  -/  Prelude 5c01365ec01f83bd405ac01cbb9a8d76
import  -/  GHC.Classes e0d9c979f6368701f34fa421754d2cce
249b649298d5b70bf96a5e7bdfddc4e9
  $bX :: Foo
39a519c32576ea18afb40f3c003e98ae
  $bY :: Foo
4b34b30c6ad23a5a6a0d8fafdfaf300e
  $fEnumFoo :: GHC.Enum.Enum Foo
  DFunId
4b34b30c6ad23a5a6a0d8fafdfaf300e
  $fEqFoo :: GHC.Classes.Eq Foo
  DFunId
d8476aa471094ec89a416538a5d70901
  $mX :: Foo -> (GHC.Prim.Void# -> r) -> (GHC.Prim.Void# -> r) -> r
638289edee3dec9b747daaa393ed3780
  $mY :: Foo -> (GHC.Prim.Void# -> r) -> (GHC.Prim.Void# -> r) -> r
f726fe038944ba38cdb01cd820017683
  $tc'Foo :: GHC.Types.TyCon
c98aefa57de35113932a336b324c55e9
  $tcFoo :: GHC.Types.TyCon
ac5c099367e93be7fc5b51ddbf6ea74c
  $trModule :: GHC.Types.Module
4b34b30c6ad23a5a6a0d8fafdfaf300e
  newtype Foo = Foo {unFoo :: GHC.Types.Int}
e924615f24f016d9ad7b983806123aac
  pattern X :: Foo
cc1a1ac81456e2618afd4c8c634d8677
  pattern Y :: Foo
4b34b30c6ad23a5a6a0d8fafdfaf300e
  unFoo :: Foo -> GHC.Types.Int
  RecSel Left Foo
instance GHC.Enum.Enum [Foo] = $fEnumFoo
instance GHC.Classes.Eq [Foo] = $fEqFoo
trusted: none
require own pkg trusted: False
module header:
  Nothing
declaration docs:
arg docs:
</pre>

Feel free to open a GHC ticket about the pattern export syntax, but don't get your hopes up. 😄
