### ISSUE TITLE
New color scheme has low contrast.

### ISSUE THREAD

**Issue by phadej** [haskell/haddock#1032]
https://github.com/haskell/hackage-server/issues/811

The background of color block is too close to the default white:

![screenshot from 2019-02-24 21-07-17](https://user-images.githubusercontent.com/51087/53319673-dbe93d80-38db-11e9-9edf-aa38f44262c6.png)

The bullet arrow is too subtle, could it be filled?

![screenshot from 2019-02-24 21-15-14](https://user-images.githubusercontent.com/51087/53319686-e4417880-38db-11e9-8c46-f3b929a8a971.png)

Also the `body` (virtually everything "black") color text is `#333`, which is IMO too light, given the font-family is very light on itself.

**Comment by harpocrates** [comment]
@phadej These seem like reasonable requests. Perhaps you'd like to take a stab at fixing this?

Note also that there is not very little time left until the 8.8 release!

**Comment by gbaz** [comment]
Here's how it looks with the body to #111 and the background (which should be set for at least pre, .src, and #contents-list) to #eee.

![image](https://user-images.githubusercontent.com/1125849/53349385-f8d93d00-38ea-11e9-9068-4f6ac0612898.png)

Note that the bullet is a unicode literal. It will look different depending on the fonts on the system. So it comes in for me (os x) like this:

![image](https://user-images.githubusercontent.com/1125849/53349701-ae0bf500-38eb-11e9-9c98-d1444a6f7068.png)

Changing it from "WHITE RIGHT-POINTING SMALL TRIANGLE" to "BLACK RIGHT-POINTING SMALL TRIANGLE" makes it come in like this:

![image](https://user-images.githubusercontent.com/1125849/53349817-edd2dc80-38eb-11e9-83e4-d7bd53ddcb4f.png)

I actually prefer the first one, in this case.

**Comment by phadej** [comment]
@gbaz note that the triangle is different on my machine/screenshot, it depends on the font.

**Comment by harpocrates** [comment]
@gbaz @phadej Just a head's up: if you'd like this to be in the coming release, please open a PR! Otherwise, this is just going to slip by...

**Comment by gbaz** [comment]
should be resolved by #1037

**Comment by phadej** [comment]
Thanks all for discussion!
