### ISSUE TITLE
New theme scrolls horizontally.

### ISSUE THREAD

**Issue by phadej** [haskell/haddock#1038]
On my machne http://hackage.haskell.org/package/sop-core-0.4.0.0/docs/Data-SOP.html has horizontal scroll bar

Seems big instances overflow:

![screenshot from 2019-02-28 15-38-30](https://user-images.githubusercontent.com/51087/53570351-eec77080-3b6e-11e9-87a4-ad3e8181e757.png)

**Comment by phadej** [comment]
This is particularly bad, e.g. in `servant-server`:

![screenshot from 2019-02-28 15-52-03](https://user-images.githubusercontent.com/51087/53571151-dce6cd00-3b70-11e9-9299-b334e6e7d448.png)

**Comment by harpocrates** [comment]
This isn't something specific to the new theme, but I agree completely: the display of instances is pretty terrible (with the huge lines due to long instance heads, then the huge vertical space due to instance docs).

**Comment by phadej** [comment]
@harpocrates, it is specific. See e.g.

http://hackage.haskell.org/package/servant-server-0.16/docs/Servant-Server-Internal.html

The layout is not nie, but at least the page **doesn't scroll** horizontally, `<--->`.

![screenshot from 2019-02-28 16-40-40](https://user-images.githubusercontent.com/51087/53574127-a1033600-3b77-11e9-9aca-9d7575de093b.png)

**Comment by harpocrates** [comment]
Oh nice catch! Will fix ASAP. Thanks for sticking to your guns, and pasting in the old output.

**Comment by harpocrates** [comment]
This seems to be part of the issue: https://github.com/haskell/haddock/blob/59843f9e3d222901421a92fff793a1e031f38f65/haddock-api/resources/html/Linuwial.std-theme/linuwial.css#L564-L566

Would you be OK if this got punted over to the next release (8.8.2 inn this case)? I've never been too happy about the placement of docs in large instances. The new theme really exacerbates the problem (by forcing a narrower width), but fixing this properly is gonna involve a bit more time than is left...

**Comment by Hamzantal** [comment]
I know this is almost 18 months old now, but I would like to bring attention to it once more as this issue is still present :(

**Comment by jhgarner** [comment]
On android chrome this is a pretty large issue because you can't scroll any of the reasonably sized code examples unless you zoom all the way out. For example, I have to zoom out to the attached screenshot so I can scroll the code sample, then zoom back in to actually read it.
![Screenshot_20240116_212658_Chrome](https://github.com/haskell/haddock/assets/7400280/a6c50a42-5f27-47fd-b821-496f50307856)

**Comment by Kleidukos** [comment]
This ticket now lives at https://gitlab.haskell.org/ghc/ghc/-/issues/24729
