### ISSUE TITLE
Synopsis isn't scrollable

### ISSUE THREAD

**Issue by carbolymer** [haskell/haddock#1043]
That's probably duplicate of #989 

**Affected versions:**
Haddock 2.22.0

**Steps to reproduce:**
1. Go to https://www.stackage.org/haddock/nightly-2019-03-07/http-conduit-2.3.5/Network-HTTP-Client-Conduit.html#v:method
2. Click on `Synopsis`

**Actual result:**
The list isn't scrollable and is clipped

**Expected result:**
All functions are available in synopsis, and the list can be scrolled.

**Comment by hvr** [comment]
Note that Stackage uses a custom CSS and possibly a custom modified `haddock` and is therefore not supported, and this was indeed fixed as stated in #989.

**Comment by carbolymer** [comment]
@hvr Thanks for clarification. Where can support issues for stackage customizations?

**Comment by harpocrates** [comment]
@carbolymer not sure, but your best bet is to poke around https://github.com/commercialhaskell.
