### ISSUE TITLE
Haddock crashes when re-exporting a data-type associated pattern synonym without the data-type

### ISSUE THREAD

**Issue by ekmett** [haskell/haddock#1067]
Consider a module like

```
{-# language PatternSynonyms #-}
module Foo ( Foo(P) ) where

data Foo = Foo
pattern P :: Foo
pattern P = Foo
```

and a secondary module

```
{-# language PatternSynonyms #-}
module Bar ( pattern P ) where
import Foo
```

Haddock crashes in this scenario because it can't find the pattern synonym. It isn't trying hard enough. =)

**Comment by harpocrates** [comment]
Haddock finally tries harder as of 5bc5016a14bc872a8315cddc629f8171a9ccd62e.
