### ISSUE TITLE
Parse error of comments with `^` in windows

### ISSUE THREAD

**Issue by jneira** [haskell/haddock#1094]
Hi, trying to generate haddock docs for `haskell-ide-engine` with `cabal-3.0.0.0`, an error is thrown in some comments with a `^` (circumflex accent) inside the comment:

https://github.com/haskell/haskell-ide-engine/blob/1267d2b081a07c4cb55304865ca4b558ab8ce28c/src/Haskell/Ide/Engine/Plugin/HsImport.hs#L374-L380

```
src\Haskell\Ide\Engine\Plugin\HsImport.hs:379:21: error:
’   parse error on input ‘-- ^ Simple import, import the whole module
    |
379 |                     -- ^ Simple import, import the whole module
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal.exe: Failed to build documentation for haskell-ide-engine-0.12.0.0
(which is required by lib:hie-test-utils from haskell-ide-engine-0.12.0.0).
```

or

https://github.com/haskell/haskell-ide-engine/blob/1267d2b081a07c4cb55304865ca4b558ab8ce28c/src/Haskell/Ide/Engine/Plugin/HsImport.hs#L437-L449

```
src\Haskell\Ide\Engine\Plugin\HsImport.hs:441:9: error:
    parse error on input ‘-- ^ Note, that it must never happen
’       -- in combination with `symbolType == Nothing`
    |
441 |         -- ^ Note, that it must never happen
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal.exe: Failed to build documentation for haskell-ide-engine-0.12.0.0
(which is required by lib:hie-test-utils from haskell-ide-engine-0.12.0.0).
```

I suppose in nix it should work.

**Comment by harpocrates** [comment]
`-- ^` is syntax indicating the start of a docstring that will annotate whatever the preceding element was, so the behaviour you observed is correct: Haddock encountered a docstring in a context where none was expected and reported an error.

It would be nice if Haddock could warn (instead of crashing) when it encounters a misplaced docstring (or give a more informative message), but that problem is a bit more involved and has to do more with GHC than Haddock: https://gitlab.haskell.org/ghc/ghc/issues/8944.

**Comment by jneira** [comment]
Thanks for the quick and precise response.
Then, only to be sure, it will not work in any platform and it should be fixed if we want to generate the complete documentation? It strange to me that project docs are broken 🤔

**Comment by harpocrates** [comment]
> Then, only to be sure, it will not work in any platform and it should be fixed if we want to generate the complete documentation? It strange to me that project docs are broken 🤔

Correct. I too am surprised that `haskell-ide-engine` would have broken docs. Then again, people generate documentation for executable projects far less frequently than for libraries (the docs for `cabal-install` were broken not long ago by a very similar issue).

**Comment by jneira** [comment]
Thanks again, i think we could close this one.
