### ISSUE TITLE
Data family instances lack arguments since haddock-2.23.0

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#1103]
(Note: this is essentially the same bug report as in [GHC#17296](https://gitlab.haskell.org/ghc/ghc/issues/17296), but from a Haddock perspective.)

Here is some code:

```hs
{-# LANGUAGE TypeFamilies #-}
module Bug where

data family Foo :: * -> *
data instance Foo Bool
```

If you run this through `haddock-2.23.0` (bundled with GHC 8.8.1), you'll get some strange results:

![haddock](https://user-images.githubusercontent.com/2364661/67397924-ed244000-f577-11e9-805c-dc174082c6b4.png)

Notice that the data instance is incorrectly rendered as `data Foo`, not `data Foo Bool`. This is a regression from `haddock-2.22.0` (bundled with GHC 8.6.5), where is was rendered as you would expect:

![haddock](https://user-images.githubusercontent.com/2364661/67398169-43917e80-f578-11e9-95ee-3f9ad8dc9a9c.png)

Patch incoming.

**Comment by phadej** [comment]
@RyanGlScott could you reupload docs for `singletons` using this patch?

I see

![Screenshot from 2019-10-31 11-17-31](https://user-images.githubusercontent.com/51087/67934238-29871a00-fbd0-11e9-8df8-587a3e5189f6.png)

Or is type-family something different than data-family?

**Comment by RyanGlScott** [comment]
What you see is something entirely different from this bug. In fact, Haddock is behaving correctly, since every `Sing` instance is literally defined like so:

```hs
type instance Sing = SBool
type instance Sing = SMaybe
-- etc.
```

These are all distinguished by the invisible kind argument used to instantiate the `k` in `k -> Type`. I suppose this would be a little clearer if they were displayed like so:

```hs
type instance Sing @Bool = SBool
type instance Sing @(Maybe a) = SMaybe @a
-- etc.
```

But that is beyond Haddock's current feature set.

**Comment by phadej** [comment]
That's tough. How to decide when to show kind arguments. For most uses, they are irrelevant.

Except it's impossible to tell from haddocks whether e.g. 

```
Eq a => Eq (Const a b)
```

is polykinded in `b`


There're also confusing things like

```
(Typeable k, Data a, Typeable b) => Data (Const a b)
```

in https://downloads.haskell.org/~ghc/8.8.1/docs/html/libraries/base-4.13.0.0/Data-Functor-Const.html

I don't have any ideas how to present that information, but not to obfuscate "Haskell98" haddocks.
