### ISSUE TITLE
Haddock emits warnings for "missing modules" when it encounters boot files

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haddock#1116]
When there are both normal modules and their boot versions in a library and the normal versions are listed either in `exposed-modules` or `other-modules` Haddock nevertheless thinks that `hs-boot` modules are not exposed. For example in Ormolu:

```
<no location info>: error: [-Wmissing-home-modules, -Werror=missing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:
        Ormolu.Printer.Meat.Declaration
        Ormolu.Printer.Meat.Declaration.Value
```

These two modules have `.hs-boot` counterparts and are included in `exposed-modules`. My understanding that there is no way to include `.hs-boot` module separately, so this situation cannot be resolved, and therefore it is a bug.

**Comment by mrkkrp** [comment]
May I ask what's the status of this one? It seems to fail with 8.6.5 yet succeeds with 8.8.3.

**Comment by mpickering** [comment]
It was fixed by your colleagues.

https://gitlab.haskell.org/ghc/ghc/issues/16551

**Comment by mrkkrp** [comment]
Excellent!
