### ISSUE TITLE
haddock-library-1.8.0 fails to build for base-4.5

### ISSUE THREAD

**Issue by hvr** [haskell/haddock#1119]
See https://matrix.hackage.haskell.org/package/haddock-library@1569860216

I've already performed a Hackage revision (see https://hackage.haskell.org/package/haddock-library-1.8.0/revisions/) and I'm working on a patch I'm gonna submit asap (EDIT: see be8b02c4e3cffe7d45b3dad0a0f071d35a274d65)

**Comment by harpocrates** [comment]
This will be fixed in the imminent upcoming 1.9.0 release, thanks to your patch.

Thank you for noticing this!
