### ISSUE TITLE
Subheadings do not appear as collapsed in module documentation

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1134]
### Short Version

While checking the Haddocks for some modules in `base`, I came to the realisation that while some helpful examples have been committed many moons ago, they do not appear to show up when being rendered by `haddock`.

### Long Version

For instance, let us pick the `Data.Functor` module:

---
![image](https://user-images.githubusercontent.com/29253044/77003312-6bd1ad80-695d-11ea-9aad-67297a032347.png)

---

Although we could regret the inopportune line wrapping for the function signature, the module description is pretty succinct. Surely, an example cannot hurt!  
But alas! The usage of `fmap` and the `Functor` typeclass are left to our imagination.

To make up for the lack of examples of `fmap`, one may be willing to add some examples, using the useful experimental feature that collapses subheadings if their title is surrounded by underscores.
And in August of 2018, our prayers were answered!

---
![Screenshot from 2020-03-18 21-20-31](https://user-images.githubusercontent.com/29253044/77003872-6cb70f00-695e-11ea-8e99-345c0a17b0ad.png)

---

But then, despair *struck* our heart! For the oh-so desired examples would remain unseen, only revealing themselves to the most adventurous Haskellers, who would dare to go and see the sources of the module by themselves.
And so their eyes would be blessed by the sight of those examples, hidden in a subheading whose title, enclosed by four underscores, would indicate a collapsed section.

---

You shall find thereafter a minimal working example. The rendering was made through `stack haddocks`, on Fedora 31.

Should the maintainer team need any precisions or details, I would be glad to give them.

![Screenshot from 2020-03-18 21-03-49](https://user-images.githubusercontent.com/29253044/77003077-f534b000-695c-11ea-94db-008ca3d78be3.png)

**Comment by sjakobi** [comment]
Thanks for the report! Is this issue limited to module headers or does it also appear in other structures, e.g. named chunks?

I would expect that if the same example would appear in the haddocks on a declaration like that `someFunc` function, it would be rendered, right?

**Comment by Kleidukos** [comment]
Hi @sjakobi!

I played around with named chunks and collapsible sections.  
Named collapsible sections are rendered when appearing in the export list, following a proper header (like `* Misc`).

I thiink our two options here are 

1. Considering the non-rendering of module-level collapsible sections as a bug, since nowhere in [the documentation](https://haskell-haddock.readthedocs.io/en/latest/markup.html#headings) it is indicated that they must be in the form of a named chunk preceded by a heading and located in the export list;
2. Fix the documentation and call it a feature.

What do you think?

---

![Screenshot from 2020-03-19 11-15-17](https://user-images.githubusercontent.com/29253044/77056614-f30d3880-69d2-11ea-8a0a-a4c99c88f627.png)

**Comment by sjakobi** [comment]
When collapsible sections in the module header aren't rendered, that's quite certainly a bug. In general, I'd expect the Haddock markup to work the same in all structures.

Would you be interested in fixing this? Right now my old Haddock knowledge is all paged out, but I might still be able to provide pointers if you need any.

**Comment by Kleidukos** [comment]
@sjakobi I would love helping out, but I have never worked on Haddock before and I'm afraid I would have to learn quite a lot of things from scratch before being remotely useful.
However, should a PR in that direction happen, I would gladly follow its development. :)

**Comment by Lysxia** [comment]
The HTML is there but hidden because it uses a class "`caption`" that is already used with a conflicting meaning, where the CSS hides it. That extra class seems to come from `hackMarkup` in `haddock-api/src/Haddock/Backends/Xhtml/DocMarkup.hs`.

Comparing with the styling of other headings, it doesn't look like this code actually relies on any rules for "`caption`", so it can probably be renamed to something else just as arbitrary, like "`subheading`".

```html
<!-- Data-Functor.html -->

<h4 class="caption details-toggle-control details-toggle expander" data-details-id="ch:noid:0">Examples</h4>
```

```css
/* linuwial.css */

#description .caption {
￼    display: none;
}
```

**Comment by Kleidukos** [comment]
Oh, that's actually quite simple, I was afraid I would need to dive in the innards of Haddock. :) Thanks!
