### ISSUE TITLE
Haddock crash when building base's docs in GHC b03fd3bc

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1136]
Hi!

I tried to build the `base` documentation on GHC [b03fd3bcd4ff14aed2942275c3b0db5392dc913c](https://gitlab.haskell.org/ghc/ghc/commit/b03fd3bcd4ff14aed2942275c3b0db5392dc913c), but was instead met with a quite obscure error message from Hadrian. I refined the process by running the haddock command myself (which is quite enormous), and it would seem that this file is the culprit:

```
Warning: GHC.Driver.Backpack: could not find link destinations for:
    BkpEnv BkpM backpackProgressMsg
./haddock-command.sh: line 3: 1619205 Killed
```

So unless some multithreading is involved and that the output function is not thread-safe, it would seem that haddock is unable to process this file.

EDIT: I was just told on IRC that the SIGKILL may indicate the work of the OOM Killer. I will try to investigate more on that.

---

**Hadrian command**: 
```
  $ hadrian/build -j --flavour=Quick --freeze1 docs \
                     --docs=no-sphinx-pdfs \
                     --docs=no-sphinx-html 
```

**Haddock version** :
```
  $ _build/stage1/bin/haddock --version
  Haddock version 2.22.0, (c) Simon Marlow 2006
  Ported to use the GHC API by David Waern 2006-2008
```

**Comment by harpocrates** [comment]
This is a pretty serious regression. I thought GHC's CI was supposed to be building Haddock documentation so as to prevent this sort of issue.

**Comment by Kleidukos** [comment]
My bad! It would seem that haddock requires more or less 8GB of RAM when generating `base`'s documentation, because I had to kill every other application and launch i3wm instead of my usual desktop environment to make it work.
