### ISSUE TITLE
Make the frames version a separate output mode

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#114]
**Original reporter**: *duncan*

The frames version of the html haddock output is almost universally ignored. That is the files:
```haskell 
frames.html
index-frames.html
mini_$MODULE.html
```
which are generated to support the frames view.

Since nobody uses the frames view and it takes extra space and clutter, how about making it a separate mode.

```haskell 
--html         output in HTML
--html-frames  output in HTML using frames
```

Note: when extracting the frames code from the normal code, make sure to omit the on-load code from the html head:
```haskell 
<SCRIPT TYPE="text/javascript">
window.onload = function () {
  setSynopsis("mini_Distribution-Simple.html")
};
</SCRIPT>
```

**Comment by Rufflewind** [comment]
[Frames are obsolete in HTML5](http://www.w3.org/TR/html5-diff/#obsolete-elements), so eliminating them is probably a good idea in the long run.  That being said, a (collapsible?) navigation panel can still be useful.
