### ISSUE TITLE
Parse pragmas in @@ blocks

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#1148]
The following comment

```haskell
-- @
-- {-# LANGUAGE DeriveGeneric #-}
-- @
```

Gets interpreted as containing an anchor `# LANGUAGE DeriveGeneric #`, `{-<a id=" LANGUAGE DeriveGeneric "></a>-}`, so people will just see this in the rendered doc:

```
{--}
```

The current workaround is to escape the `#`:

```
-- @
-- {-\# LANGUAGE DeriveGeneric \#-}
-- @
```

The problem is that it is very easy to miss.

It would be nice to detect this situation automatically and not parse these as anchors, so we wouldn't have to escape them. Some possible criteria:

- Don't recognize anchors `#...#` containing/starting with/ending with spaces
- Don't recognize anchors `#...#` surrounded by `{-`, `-}`
- Don't recognize anchors in the middle of code blocks

**Comment by harpocrates** [comment]
Are HTML anchors even technically allowed to have space in them? If not, I think the first criteria is one we should definitely add!

**Comment by Lysxia** [comment]
Ah you're right! That makes it easy!

> id's value must not contain whitespace
>
> https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by harpocrates** [comment]
If you have time for a PR, it should be pretty straightforward:

https://github.com/haskell/haddock/blob/5dc3866928759fcaf6b31d1598051781389a01d4/haddock-library/src/Documentation/Haddock/Parser.hs#L230

Then maybe a comment here about how the anchor name should be whitespace-free:

https://github.com/haskell/haddock/blob/5dc3866928759fcaf6b31d1598051781389a01d4/haddock-library/src/Documentation/Haddock/Types.hs#L128-L129

And finally a simple unit test in [`Documentation.Haddock.ParserSpec`](https://github.com/haskell/haddock/blob/ghc-8.10/haddock-library/test/Documentation/Haddock/ParserSpec.hs).

**Comment by Lysxia** [comment]
Thanks! I'll work on it.
