### ISSUE TITLE
Change default branch to 8.10

### ISSUE THREAD

**Issue by harpocrates** [haskell/haddock#1150]
Now that GHC 8.10.1 has been released, Haddock's default branch should be 8.10 (so that people stop opening PRs against 8.8 😛). I don't have the Github permissions to do this.

/cc @cartazio @emilypi @hvr

**Comment by harpocrates** [comment]
Ping

**Comment by emilypi** [comment]
HVR is currently making headway on a particularly difficult hackage server migration (to make use of Cabal 3.x). I imagine this is related. @Herbert?

**Comment by hvr** [comment]
Sorry, missed the notification; it's done now! :-)

**Comment by harpocrates** [comment]
Thanks!
