### ISSUE TITLE
More customizable type synonym documentations

### ISSUE THREAD

**Issue by poscat0x04** [haskell/haddock#1153]
![image](https://user-images.githubusercontent.com/53291983/78127506-dcd99080-7446-11ea-958e-012c0de1c25d.png)
Right now when generating type synonyms, haddock maximizes parenthesis and does not allow commenting segments (unlike function arrows).

**Comment by harpocrates** [comment]
Dup of #556? In any case, I agree.

This sort of change probably requires changes to the GHC parser though.
