### ISSUE TITLE
Data constructors printed prefix, when symbolic (begin-with-a-colon), should be parenthesized

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#117]
**Original reporter**: _isaacdupree_

for example,

``` haskell
data Foo = (:::) Int Bool
```

is displayed by Haddock similarly except without the parentheses.  Obviously it should use the parentheses anytime it's not using such a thing infix-ly.

**Comment by harpocrates** [comment]
This is fixed. See:

<img width="314" alt="screen shot 2018-07-01 at 4 16 46 pm" src="https://user-images.githubusercontent.com/10766081/42138358-37f01570-7d4a-11e8-804c-ef45f0d5041e.png">
