### ISSUE TITLE
parse failure: section heading as second line comment

### ISSUE THREAD

**Issue by shapr** [haskell/haddock#1171]
Haddock fails to parse a section heading as the second comment line, minimal example below.
As mentioned before, if I'm reporting known parse failures, please point me to a list of known problems!

```
module Main where


data Record = Record
  { -- | first line
    -- * second line
    field :: Int
  }

data FailRecord = FailRecord
  { -- first line fails without a leading "-- |" as on line 5 above
    -- * second line
    failfield :: Int
  }

main = print "hi"
```

**Comment by nitros12** [comment]
On GHC 9.0 with `-Winvalid-haddock -haddock` (https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock), ghc will now report the following error:

```
1171.hs:12:5: warning: [-Winvalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
   |
12 |     -- * second line
   |     ^^^^^^^^^^^^^^^^
```
