### ISSUE TITLE
parse failure: section header before module declaration

### ISSUE THREAD

**Issue by shapr** [haskell/haddock#1173]
haddock fails to parse a file that has a section header comment before the module declaration.

```
-- * section header breaks here
module Main where

main = print "hi"

```

**Comment by nitros12** [comment]
On GHC 9.0 with `-Winvalid-haddock -haddock` (https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock), ghc will now report the following error:

```
1173.hs:1:1: warning: [-Winvalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
  |
1 | -- * section header breaks here
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
