### ISSUE TITLE
parse failure: vertical bar comment on datatype last constructor 

### ISSUE THREAD

**Issue by shapr** [haskell/haddock#1174]
haddock fails to parse a vertical bar comment on the last constructor of a datatype

```
module Main where

main = print "hi"

data Fooa =
  Bara -- | this is fine
  | Baza -- | this line is fine
  | Quuxa

data Foo =
  Bar -- | this is fine
  | Baz -- | this line breaks unless there's another data constructor on the next line!
```

**Comment by Lysxia** [comment]
This and some other failures make a lot of sense though (`-- |` comments are attached to the next item, but in this case there is no next item).

Just to make it clear, is your position that haddock should never fail on a file that GHC accepts, so this kind of error should be a warning instead?

**Comment by shapr** [comment]
For any GHC acceptable file to pass as a warning seems reasonable to me.
I'm just an interested user though, there may be perfectly sensible reasons that's a bad idea.

**Comment by nitros12** [comment]
On GHC 9.0 with `-Winvalid-haddock -haddock` (https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock), ghc will now report the following error:

```
1174.hs:12:9: warning: [-Winvalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
   |
12 |   | Baz -- | this line breaks unless there's another data constructor on the next line!
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
