### ISSUE TITLE
parse failure: section comment after let

### ISSUE THREAD

**Issue by shapr** [haskell/haddock#1175]
haddock fails to parse a file that has a section comment after a let

```
module Main where

main = print "hi"

something :: [Int]
something = do
  let myid = id
  -- * section
  pure 1
```

**Comment by nitros12** [comment]
On GHC 9.0 with `-Winvalid-haddock -haddock` (https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock), ghc will now report the following error:

```
1175.hs:8:3: warning: [-Winvalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
  |
8 |   -- * section
  |   ^^^^^^^^^^^^
```
