### ISSUE TITLE
haskell-haddock.readthedocs.io seems to display Haddock 1.0 documentation

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1177]
Hi! The title of haskell-haddock.readthedocs.io/ indicates that the documentation cover Haddock v1.0!
It doesn't seem to be true but I'd like to confirm with you since I tend to believe what I read on the internet, especially when it ends with `readthedocs.io`. ;)

cc @harpocrates @cartazio @gbaz

**Comment by cartazio** [comment]
I know at least cabal is working to shift to keeping up to date links to stable vs dev / latest hosted

**Comment by harpocrates** [comment]
I have no idea how to update haskell-haddock.readthedocs.io. If I did, I'd update it. 😄
There are some other issues also open about this.

**Comment by Kleidukos** [comment]
Blimey, so are we locked out? :o

**Comment by gbaz** [comment]
cf https://github.com/haskell/haddock/issues/338

**Comment by gbaz** [comment]
ben just added me and @harpocrates as admins and i think fixed the immediate issue, which was induced by haddock not having a "master" by setting the latest to be ghc-head.

**Comment by Kleidukos** [comment]
@gbaz Does that mean that new commits to the documentation will autogenerate the output on ReadTheDocs?

**Comment by m1-s** [comment]
I accidentally stumbled upon this. The readthedocs documentation is one of the first results that is offered when searching for haddock. The website says it is on `latest` and when clicking on `edit on Github` it links to the branch ghc-head but the hosted documentation is not up to date with ghc-head. There are significant informations missing in the readthedocs documentation compared to ghc-head. 

We should either update or remove the readthedocs completely. This old but official looking documentation is very misleading.

**Comment by gbaz** [comment]
Found and fixed the issue. The webhook we configured was deprecated by github, and we needed to install a new integration via the readthedocs interface -- new doc builds should now occur again.
