### ISSUE TITLE
Relax upper bound of Cabal for haddock-api >= 2.20.0 && <= 2.22.0

### ISSUE THREAD

**Issue by jneira** [haskell/haddock#1191]
* `haddock-api` was fixing both `base'  and `Cabal` package versions
* It makes difficult to use it in build plans that needs a newer Cabal version compatible with an older base one
* The problem has arised when we tried to use `cabal-helper-1.1.0.0` in `haskell-ide-engine`, that uses in turn `haddock-api` for several builds plans for ghc >= 8.4.2 and <= 8.6.5
  * `cabal-helper` needs Cabal > 3.0.1.0 in windows to avoid a nasty bug
  * `haddock-api` restricts upper bound on Cabal for each base/ghc version
  * isue in cabal-helper: https://github.com/DanielG/cabal-helper/issues/116
* The temporary workaround had been enable `allow-newer` in stack.yaml and `cabal.project` files
* It seems that the usage of `Cabal` in `haddock-api` is not extensible and in fact `allow-newer` does not throw any compile error, so maybe no code patch is needed
* So publish hackage revisions for those haddock-api versions relaxing the upper bound up to `3.0.1.0` could let users remove the always dangerous `allow-newer`

Thanks in advance!
/cc @DanielG

**Comment by harpocrates** [comment]
Thanks for reporting!

I see the issue and I'm checking locally how much we can loosen the bounds (maybe even up to `3.2.0`?). As you say, the `Cabal` dependency in `haddock-api` was hardly used, hence why it has been removed completely in more recent versions.

**Comment by harpocrates** [comment]
An eternity of building `Cabal` versions 2.4, 3.0, and 3.2 against GHC 8.4 and GHC 8.6, I'm convinced all is well with the proposed revision. Also, I wish I'd removed the `Cabal` dependency sooner.

Relevant revisions:

  * https://hackage.haskell.org/package/haddock-api-2.20.0/revisions/
  * https://hackage.haskell.org/package/haddock-api-2.21.0/revisions/
  * https://hackage.haskell.org/package/haddock-api-2.22.0/revisions/

Is there anything I missed?

**Comment by jneira** [comment]
@harpocrates wow, thank you so much for your quick a helpful response and for take care of this.
Yeah, those are the versions we are using in haskell-ide-engine and haskell-language-server and their hackage revisions will let us get rid of `allow-newer`'s.
I am gonna update the indexes and try it asap.

**Comment by jneira** [comment]
Well, we've been able to upgrade Cabal (and use cabal-helper-1.1 in windows) in [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine/pull/1771) and [haskell-language-server](https://github.com/haskell/haskell-language-server/pull/108) without no `allow-newer`
Thanks again @harpocrates 🙏

**Comment by harpocrates** [comment]
Glad to hear it! I'm very excited about the good work that is happening in those projects. 😄
