### ISSUE TITLE
Support export of modules using their "as" name

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#121]
**Original reporter**: _bjpop@<hidden>_

Haskell allows you to import modules using an "as" name, and re-export the module using that name:

   module Language.Python.Common ( module Pretty )
   import Language.Python.Common.Pretty as Pretty

It seems that Haddock 2.4.2 has trouble with this and complains that:

   Warning: language-python-0.2:Language.Python.Common: Could not find documentation for exported module: Pretty

Changing the export to use the full qualified name of the module fixes the problem.

**Comment by brandonchinn178** [comment]
+1

**Comment by gbaz** [comment]
should be resolved by #688
