### ISSUE TITLE
What's the difference between haddock-api and haddock-library?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell/haddock#1215]
Is `haddock-api` trying to provide a stable API (across compiler, or haddock, versions) on top of `haddock-library`?

PS: Sorry - didn't know the appropriate forum to ask this question.

**Comment by harpocrates** [comment]
haddock-library is designed to build across many GHC versions and is really only concerned with parsing Haddocks markup.

haddock-api bundles together into a library most of haddock’s functionality - it’s primary purpose is just to make the functionality easy to use as a library. It makes heavy use of GHCs API, so only ever builds with exactly one GHC version.

**Comment by saurabhnanda** [comment]
> haddock-library is designed to build across many GHC versions and is really only concerned with parsing Haddocks markup.

So, haddock-library parses haddock markup into a Haskell data-type and doesn't do much beyond that (like emitting HTML, generating hyperlinked source files, etc)? All of the other functionality is in haddock-api?

**Comment by harpocrates** [comment]
Yep, exactly.

**Comment by saurabhnanda** [comment]
Thanks!
