### ISSUE TITLE
Error building with ghc-8.10.2

### ISSUE THREAD

**Issue by mvoidex** [haskell/haddock#1229]
[tcdName](https://github.com/haskell/haddock/blob/ghc-8.10/haddock-api/src/Haddock/GhcUtils.hs#L62) have different type in [ghc-8.10.2](https://downloads.haskell.org/~ghc/8.10.2/docs/html/libraries/ghc-8.10.2/GHC-Hs-Decls.html#v:tcdName) (compare to [ghc-8.10.1](https://downloads.haskell.org/~ghc/8.10.1/docs/html/libraries/ghc-8.10.1/GHC-Hs-Decls.html#v:tcdName))

```haskell
tcdName :: TyClDecl pass -> IdP pass  -- ghc-8.10.1
tcdName :: TyClDecl (GhcPass p) -> IdP (GhcPass p)  -- ghc-8.10.2
```

> haddock-api> /tmp/stack-a8f062bc5e8dbbce/haddock-api-2.24.0/src/Haddock/GhcUtils.hs:60:42: error:
> haddock-api>     • Could not deduce: p ~ GhcPass p0
> haddock-api>       from the context: (SrcSpanLess (LPat p) ~ Pat p,
> haddock-api>                          HasSrcSpan (LPat p))
> haddock-api>         bound by the type signature for:
> haddock-api>                    getMainDeclBinder :: forall p.
> haddock-api>                                         (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
> haddock-api>                                         HsDecl p -> [IdP p]
> haddock-api>         at src/Haddock/GhcUtils.hs:(58,1)-(59,40)
> haddock-api>       ‘p’ is a rigid type variable bound by
> haddock-api>         the type signature for:
> haddock-api>           getMainDeclBinder :: forall p.
> haddock-api>                                (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
> haddock-api>                                HsDecl p -> [IdP p]
> haddock-api>         at src/Haddock/GhcUtils.hs:(58,1)-(59,40)
> haddock-api>       Expected type: TyClDecl (GhcPass p0)
> haddock-api>         Actual type: TyClDecl p
> haddock-api>     • In the first argument of ‘tcdName’, namely ‘d’
> haddock-api>       In the expression: tcdName d
> haddock-api>       In the expression: [tcdName d]
> haddock-api>     • Relevant bindings include
> haddock-api>         d :: TyClDecl p (bound at src/Haddock/GhcUtils.hs:60:28)
> haddock-api>         getMainDeclBinder :: HsDecl p -> [IdP p]
> haddock-api>           (bound at src/Haddock/GhcUtils.hs:60:1)
> haddock-api>    |
> haddock-api> 60 | getMainDeclBinder (TyClD _ d) = [tcdName d]
> haddock-api>    |                                          ^
> haddock-api>

**Comment by dunrix** [comment]
*bump*

Anybody working already on this ? Broken since 8th of August, release date of GHC 8.10.2 .
I may have a look on it, but eager to do duplicate job.

**Comment by arjunkathuria** [comment]
same with ghc 8.10.3, windows. any luck @alexbiehl ?


```
     |
60 | getMainDeclBinder (TyClD _ d) = [tcdName d]
     |                                          ^

cabal: Failed to build haddock-api-2.24.0 (which is required by exe:hsdev from
hsdev-0.3.4.0). See the build log above for details.
```

**Comment by arjunkathuria** [comment]
here's the fuller log if you need it, @alexbiehl 

```
[11 of 40] Compiling Haddock.GhcUtils ( src\Haddock\GhcUtils.hs, dist\build\Haddock\GhcUtils.o )

src\Haddock\GhcUtils.hs:60:42: error:
    * Could not deduce: p ~ GhcPass p0
      from the context: (SrcSpanLess (LPat p) ~ Pat p,
                         HasSrcSpan (LPat p))
        bound by the type signature for:
                   getMainDeclBinder :: forall p.
                                        (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
                                        HsDecl p -> [IdP p]
        at src\Haddock\GhcUtils.hs:(58,1)-(59,40)
      `p' is a rigid type variable bound by
        the type signature for:
          getMainDeclBinder :: forall p.
                               (SrcSpanLess (LPat p) ~ Pat p, HasSrcSpan (LPat p)) =>
                               HsDecl p -> [IdP p]
        at src\Haddock\GhcUtils.hs:(58,1)-(59,40)
      Expected type: TyClDecl (GhcPass p0)
        Actual type: TyClDecl p
    * In the first argument of `tcdName', namely `d'
      In the expression: tcdName d
      In the expression: [tcdName d]
    * Relevant bindings include
        d :: TyClDecl p (bound at src\Haddock\GhcUtils.hs:60:28)
        getMainDeclBinder :: HsDecl p -> [IdP p]
          (bound at src\Haddock\GhcUtils.hs:60:1)
     |
60 | getMainDeclBinder (TyClD _ d) = [tcdName d]
     |                                          ^
cabal: Failed to build haddock-api-2.24.0 (which is required by exe:hsdev from
hsdev-0.3.4.0). See the build log above for details.
```

**Comment by arrowd** [comment]
Can we have a new haddock release with this change in?

**Comment by sonatav2** [comment]
it doesn't seem like the changes @alexbiehl made were ever merged into the master branch of haddock

https://github.com/haskell/haddock/commit/bc962c945af2955402c8bed66ccb310f35a1e676

**Comment by alexbiehl** [comment]
@sonatav2 The master branch has been abandoned quite some time ago in branches which reflect the companion GHC version. That is, if you want to talk ghc-8.10.4 you likely want to give the ghc-8.10 branch a try.
