### ISSUE TITLE
Haddock is putting multiline function signatures all on the same line.

### ISSUE THREAD

**Issue by locallycompact** [haskell/haddock#1248]
Hi. I'm experiencing this behaviour here. https://hackage.haskell.org/package/polysemy-methodology-0.1.5.0/docs/Polysemy-Methodology.html

**Comment by harpocrates** [comment]
Which function in particular? Note that the multiline rendering only kicks in if you documented any of the arguments.

**Comment by sjakobi** [comment]
Duplicate of https://github.com/haskell/haddock/issues/147?!

#472 seems related, too.

**Comment by locallycompact** [comment]
> Which function in particular? Note that the multiline rendering only kicks in if you documented any of the arguments.

Oh, I didn't know that. OK.
