### ISSUE TITLE
Broken link to idoc in the docs

### ISSUE THREAD

**Issue by vrom911** [haskell/haddock#1261]
The link in the Introduction section to `idoc` doesn't work for everyone: http://www.cse.unsw.edu.au/~chak/haskell/idoc/
Ideally, it is better to have a link that could be accessible to everyone. 
<img width="635" alt="Screenshot 2020-12-02 at 15 37 30" src="https://user-images.githubusercontent.com/8126674/100894673-a57b2200-34b4-11eb-80a8-3d716612015e.png">

**Comment by vrom911** [comment]
I see problems with other "Acknowledgements" links as well:
* HDoc – http://www.fmi.uni-passau.de/~groessli/hdoc/
* Doxygen – http://www.stack.nl/~dimitri/doxygen/

**Comment by alexbiehl-gc** [comment]
Thanks for noticing @vrom911. I am putting this on my long haddock backlog.
