### ISSUE TITLE
parse failure: parenthesis in constructor argument

### ISSUE THREAD

**Issue by damiencourousse** [haskell/haddock#1283]
Parsing errors in constructor arguments:

```
-- haddock: parse OK
data T0 a b
  = T0
      a
      b  -- ^ This is the documentation for the argument of type 'b'

-- haddock: parse error
data T1 a b
  = T1   -- ^ This is the documentation for the 'C1' constructor
      a  -- ^ This is the documentation for the argument of type 'a'
      b  -- ^ This is the documentation for the argument of type 'b'

-- haddock: parse error
data T2 a b
  = T2         -- ^ This is the documentation for the 'C1' constructor
      (a -> b) -- ^ This is the documentation for the argument of type 'a -> b'
      b        -- ^ This is the documentation for the argument of type 'b'
```

**Comment by alexbiehl-gc** [comment]
What's the exact error message you are seeing? It's hard to tell wether it's haddock or GHC in question.

**Comment by damiencourousse** [comment]
I think it's haddock:

```
Running Haddock on library for hackup-0.20.3..

lib/Hackup/Backends/Restic.hs:50:7: error: parse error on input ‘a’
   |
50 |       a  -- ^ This is the documentation for the argument of type 'a'
   |       ^
```

Building with stack, using `$ stack haddock`, but I am not up-to-date:
```
$ cat  stack.yaml | grep lts                               
resolver: lts-12.26

$  stack exec haddock -- --version                         
Haddock version 2.20.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008

$ stack exec ghc -- --version                 
The Glorious Glasgow Haskell Compilation System, version 8.4.4
```
```

**Comment by alexbiehl-gc** [comment]
The error message is actually GHC, can you open a ticket on GHCs issue tracker? Haddock itself never fails parsing the markup. Similar to, say Markdown parsers.

**Comment by damiencourousse** [comment]
I don't know how haddock uses GHC, but the project builds fine otherwise (e.g. `$ stack build`).  
Also, if using comments without the haddock markups (e.g., without `^`), haddock builds everything fine.

Are you sure the issue is with GHC?

Here is a detailed excerpt of the build log:

```
$ LANG=C stack build --haddock --cabal-verbose 

...


hackup> haddock
/home/damien/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/bin/haddock --ghc-version --hyperlinked-source --quickjump
/home/damien/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/bin/ghc --print-libdir -fhide-source-paths
creating .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build
creating .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/autogen
creating .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/autogen
Preprocessing library for hackup-0.20.3..
Running Haddock on library for hackup-0.20.3..
creating .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/doc/html/hackup
/home/damien/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/bin/haddock '@.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/doc/html/hackup/haddock-response5079-1.txt' --hyperlinked-source --quickjump

lib/Hackup/Backends/Restic.hs:50:7: error: parse error on input `a'
   |
50 |       a  -- ^ This is the documentation for the argument of type 'a'
   |       ^
Haddock coverage:

...
```

**Comment by harpocrates** [comment]
This was indeed a GHC-side bug, but it was fixed a release or two ago. With Haddock bundled with GHC 8.10.1:

<img width="584" alt="Screen Shot 2021-01-01 at 11 11 43 AM" src="https://user-images.githubusercontent.com/10766081/103442203-26e3e280-4c22-11eb-9047-a1fad204916d.png">

In the upcoming GHC 9.0 series, you won't get errors for misplaced doc strings either - just warnings.

---

Although I know this wasn't the point of your question, note that single quotes are generally for trying to link to other identifiers (and won't work on anything not identifier-like, such as `a -> b`). For just mono-spacing, consider using `@`-delimited blocks.

**Comment by damiencourousse** [comment]
> This was indeed a GHC-side bug, but it was fixed a release or two ago. With Haddock bundled with GHC 8.10.1:
> 
> <img alt="Screen Shot 2021-01-01 at 11 11 43 AM" width="584" src="https://user-images.githubusercontent.com/10766081/103442203-26e3e280-4c22-11eb-9047-a1fad204916d.png">

Thank you @harpocrates  and @alexbiehl. I did a test with stackage's nightly-2021-01-02, and I confirm that the parsing error is gone.

> In the upcoming GHC 9.0 series, you won't get errors for misplaced doc strings either - just warnings.
> 
> Although I know this wasn't the point of your question, note that single quotes are generally for trying to link to other identifiers (and won't work on anything not identifier-like, such as `a -> b`). For just mono-spacing, consider using `@`-delimited blocks.

Thanks for the feedback.  Yes, that does not make sense in my minimal example used the issue report, but it does make sense in the project I am working on.
