### ISSUE TITLE
Missing parenthesis around infix GADT constructors

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#129]
**Original reporter**: _david.waern@<hidden>_

Here's an example:

http://hackage.haskell.org/packages/archive/operational/0.1.0.0/doc/html/Control-Monad-Operational.html#v%3A%3A%3E%3E%3D

**Comment by harpocrates** [comment]
This is fixed as per the latest (July 2018) docs: http://hackage.haskell.org/package/operational-0.2.3.5/docs/Control-Monad-Operational.html#v%3A%3A%3E%3E%3D. Judging from Hackage, this has been fixed for at least 4 years.
