### ISSUE TITLE
CI failure for hoogle-test's Bug873

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1291]
The `hoogle-test` part of the test suite fails in CI with

`hoogle-test: hoogle-test/out/Bug873: removeDirectoryRecursive:getSymbolicLinkStatus: does not exist (No such file or directory)`

This is blocking https://github.com/haskell/haddock/pull/1181

cc @alexbiehl-gc Do you have any idea why?

**Comment by alexbiehl-gc** [comment]
Uh, annoying. I haven't seen that one. Have you tried to re-trigger CI? Might be just a blip.
