### ISSUE TITLE
Binary serialisation/deserialisation changes for interface files with GHC 9.0?

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1307]
I am getting a weird binary serialisation/deserialisation issue in the Haddock test suite.

```
haddock: While creating Haddock interface for Bug310:

While creating Haddock interface for Bug310:

get Wrap: Bad h (239)
CallStack (from HasCallStack):
  error, called at src/Haddock/InterfaceFile.hs:729:12 in haddock-api-2.24.0-inplace:Haddock.InterfaceFile
```

For reference, we are expecting a number between 1 and 3, but certainly not 239. This suggests that we can't really deal with unknown interface files in a more structured way (I have yet to discover a formal schema for the binary representation), but also that this bug has crept in the codebase for way too long and I can't figure out when it was introduced.

@harpocrates Had a solid lead on https://github.com/haskell/haddock/pull/1296#discussion_r563339358 but removing the PR that introduced changes to the binary format (https://github.com/haskell/haddock/pull/1181) didn't change the outcome: It still fails. 

I can't really use HLS on that one because there is no version for ghc-9.0 available yet, so I'm faced with my own incomprehension of this whole situation right now. 

@bgamari @hsyl20 @alexbiehl  I could really benefit from your insights on the matter, this is still new territory for me. And it could be the perfect occasion to explicit a lot of the tribal knowledge that makes everything hold together, or even start out with a cold rewrite of Haddock that would be tailored for GHC 9.0.

**Comment by alexbiehl** [comment]
I think we can close this one?
