### ISSUE TITLE
Remnants of merge conflict in `ghc-9.0` branch

### ISSUE THREAD

**Issue by harpocrates** [haskell/haddock#1325]
I see this in the `ghc-9.0` branch, which looks to me like leftover from some merge/rebase:

https://github.com/haskell/haddock/blob/6b7fe26d9f592d7fcc8e77fbeb39f591fdff3386/haddock-api/src/Haddock/Interface/Create.hs#L48-L62

We should remove it.

**Comment by alexbiehl** [comment]
Aww man, my bad. Will fix.
