### ISSUE TITLE
haddockHtmlTest failure in ghc-9.0

### ISSUE THREAD

**Issue by monoidal** [haskell/haddock#1350]
The test `haddockHtmlTest` fails with Haddock's `ghc-9.0` branch 23ee81fc79. I'm using the tip of GHC's `ghc-9.0` branch - commit c78867a186c21, except the submodule is updated:

https://gitlab.haskell.org/tweag/ghc/-/pipelines/31780

I have not investigated the cause.

**Comment by Kleidukos** [comment]
@monoidal Hi, and thanks for the report!

Could you run `hadrian/build -j test --only="haddockHtmlTest"` and give us the result? :)

**Comment by monoidal** [comment]
This is the result of `make accept` for this test: https://github.com/haskell/haddock/commit/21e156a76c1dfad008546688a8f9f3a803c063ba

AFAICT the changes are benign but I didn't look thoroughly.

**Comment by Kleidukos** [comment]
Okay this mostly looks like golden tests needing updating
