### ISSUE TITLE
Better inline monospace styling

### ISSUE THREAD

**Issue by Kleidukos** [haskell/haddock#1414]
As of now, the inline monospace styling is not optimal, and could use better contrast (like a greyed background).  
GitHub's `own styling` could be taken as a model.

https://css-tricks.com/considerations-styling-pre-tag/

https://css-tricks.com/styling-code-in-and-out-of-blocks/

**Comment by vedant-z** [comment]
Hey @Kleidukos I am willing to work on this issue. I just need some help on understanding which part needs the changes to be done?

**Comment by Kleidukos** [comment]
@vedant-z Sure! Do you have any experience writing CSS? :)

**Comment by vedant-z** [comment]
@Kleidukos Ya I do.

**Comment by ayeankit** [comment]
@Kleidukos I would like to work on this issue. Please assign me this.

**Comment by Kleidukos** [comment]
This has been fixed by https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12660
