### ISSUE TITLE
Allow -- ^ comment on record constructor

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#144]
**Original reporter**: _red5_2@<hidden>_

This enhancement would add flexibility to the commenting style for record constructors.  Accept a `-- ^` comment between a constructor and its fields, meaning the same as a `-- |` comment before the constructor.  The example below is rejected as a parse error due to the comment on 'Branch'.

``` haskell
-- | A tree with labeled internal nodes
data Tree =
    Empty                -- ^ Leaf
  | Branch               -- ^ Internal node
    { label :: a         -- ^ Node label
    , subtrees :: [Tree] -- ^ List of subtrees
    }
```

**Comment by sjakobi** [comment]
This seems to have been fixed in #709.
