### ISSUE TITLE
Please determine what to do with https://www.haskell.org/haddock/

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/haddock#1443]
Dear Haddock maintainers,

I am writing as a haskell.org committee member, ultimately responsible for haskell.org and the experience users have with it.

There is a subsite of haskell.org, https://www.haskell.org/haddock/ that is *severely* out of date. It hasn't been updated for seven years. It is indexed prominently by search engines and [has confused new users](https://github.com/haskell-infra/www.haskell.org/issues/148). [According to @gbaz](https://github.com/haskell-infra/www.haskell.org/pull/103#issuecomment-877643716), as the maintainers of Haddock, you are the owners of that particular subsite, so you can decide what to do with it. I can see a couple options, perhaps you have other ideas.

1. Since you already have a [readthedocs site](https://haskell-haddock.readthedocs.io/en/latest/markup.html) perhaps the `haddock/` subsite can just be deleted, and the old URLs made to redirect to the readthedocs site.
2. You might want to host the Sphinx docs on `haddock/` as well as readthedocs

Could you please determine what should be done with it. Alternatively you are welcome to delegate that decision to the haskell.org committee.

Thanks,

Tom

**Comment by Kleidukos** [comment]
Hi @tomjaguarpaw and thank you for reaching out to us.

I would like to accept your offer and redirect `www.haskell.org/haddock` to the ReadTheDocs website.

**Comment by tomjaguarpaw** [comment]
Thank you for that decision. As a haskell.org committee member I will tak responsibility for enacting that decision.
