### ISSUE TITLE
Odd in-page search behavior with recent Chromium and Chrome

### ISSUE THREAD

**Issue by treeowl** [haskell/haddock#1451]
I don't know if this is a Chromium bug or a Haddock bug or some weird interaction, but since I updated Chrome and Chromium recently, I've been having a problem. Specifically, if I hit Ctrl-F to find a word in some module documentation, and the word appears some ways down the page, it ends up opening up the Synopsis tab and searching there before continuing with the main page. UGH. Note: I don't have this problem in Firefox.

**Comment by eltix** [comment]
I confirm I've been getting the same visualization bug in latest Chrome. Here is a screenshot exhibiting the bug:

![image](https://user-images.githubusercontent.com/28726150/154075546-6fbe3993-8332-4bce-8aa7-4ab614faefac.png)

Clicking on the search match in the yellow right panel has no effect

**Comment by stevehartdata** [comment]
This is a result of a recent change to the HTML spec that specifies that closed `details` elements should be searchable. See [the relevant section in the HTML spec](https://html.spec.whatwg.org/#interaction-with-details), which was changed in this [pull request](https://github.com/whatwg/html/pull/6466). The change was implemented in [Chrome 97](https://chromestatus.com/feature/5032469667512320) and Firefox has an [open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1724299) to implement it.

**Comment by treeowl** [comment]
Thanks, @stevehartdata. That confirms the bug is in Haddock and not Chromium. Do you happen to know what we have to do to fix it? The search feature is currently nearly unusable.

**Comment by treeowl** [comment]
No, I'm certainly not. Have you tried navigating Hackage with the new behavior? I can confidently say it's not what anyone is likely to want.

**Comment by treeowl** [comment]
Specifically: search will go into the sidebar, then clicking on the found thing won't actually take you there. It's just wretched.

**Comment by stevehartdata** [comment]
The links in the synopsis not taking you to the expected location is a different bug that is not related to the recent HTML change. I definitely agree that that behavior is not how it should be, and I've opened #1457 to track that issue separately.

**Comment by treeowl** [comment]
I personally really don't want searching to open the sidebar either.

**Comment by parsonsmatt** [comment]
I can't really say how I feel about this without being hyperbolic and rude, so I'll just say "please let's fix it"

**Comment by Lysxia** [comment]
This does seem like an easy fix. I'll make a PR.

The new default behavior of `<details>` makes sense as a default, but this certainly seems like a case where we want to override it. There's no reason to search the synopsis element, since all of its contents can already be found elsewhere in the main part of the page. It doesn't seem possible to unconditionally hide an element from search, so disabling visibility when it's already hidden by `<details>` seems the next best option. And `content-visibility: hidden` seems preferable to `visibility: hidden` because we do not care about preserving its layout.

**Comment by MaxGabriel** [comment]
@Lysxia Thank you so much!

**Comment by Kleidukos** [comment]
@eltix Hackage will have do adopt the next Haddock release, which will be cut for the next GHC release. :)

**Comment by Kleidukos** [comment]
> How is this synchronized in practice?

This is done at the discretion of the Hackage maintainers, you'll have to ask them directly

**Comment by Lysxia** [comment]
That's a very old package. Picking a more recent package [like text](https://hackage.haskell.org/package/text-2.0/docs/Data-Text.html) shows that 2.24 is being used. I believe [hackage-server](https://github.com/haskell/hackage-server) is where the issue can be raised.

**Comment by mrbech** [comment]
For anyone that can't wait I have created a chrome extension (https://github.com/mrbech/hackage-synopsis-search-hider) that applies the fix from https://github.com/haskell/haddock/pull/1486 to hackage.haskell.org
