### ISSUE TITLE
Hyperlinked sources as generated by the Nix toolchain prepend `../` in absolute paths

### ISSUE THREAD

**Issue by lf-** [haskell/haddock#1481]
Sample bit of bad source from the Persistent `Database.Persist.TH` hyperlinked docs generated by haddock 2.25.1:

```html
<span class="annot"><span class="annottext">Exp -&gt; Stmt
</span><a href="../file:///nix/store/3bwbsy0llxxn1pixx3ll02alln56ivxy-ghc-9.0.2-doc/share/doc/ghc/html/libraries/template-haskell-2.17.0.0/src" class=""><span class="hs-identifier hs-var">NoBindS</span></a></span>
```

It's also the case in other packages such as `aeson` linking to functions in packages included with ghc. I don't know/remember if it affects links to packages sourced from hackage.

I am guessing that the following code, or code near it, is the cause of the leading `../`:

https://github.com/haskell/haddock/blob/bc0f2d6c1bfd331a9426fa9a92288444178267b1/haddock-api/src/Haddock/Backends/Hyperlinker/Renderer.hs#L265-L270

However, setting up a development environment such that I can test it with the Nix builder is running into some bugs in nixpkgs, so I can't proceed any further on figuring this out myself.

**Comment by lf-** [comment]
Exact repro with aeson:

```
$ nix-build '<nixpkgs>' -A haskell.packages.ghc922.aeson.doc
/nix/store/nwk37d36j9zjkalxs58qfli9cfa9jvd5-aeson-2.0.3.0-doc
```

then go to `file:///nix/store/nwk37d36j9zjkalxs58qfli9cfa9jvd5-aeson-2.0.3.0-doc/share/doc/aeson-2.0.3.0/html/src/Data.Aeson.Text.html` in a browser and `TB.singleton` is an example of a bad link.

**Comment by Kleidukos** [comment]
@lf- Hi! I don't personally use Nix so I'm not really sure how to approach this.
We could probably have a heuristic that determines whether or not to insert the `../` if the `path` starts with `file://`.
What do you think of that?

**Comment by lf-** [comment]
That was what I was thinking as well. Detect if it's absolute and go from there. I'm not sure who gives us the file:// URLs (or indeed if we are given them at all; might be some Nix hack), but it's easy enough to detect them and not do the prepend. I have now figured out the setup to test a proposed patch so I might write one.

**Comment by Kleidukos** [comment]
@lf- Very well. Ping me if you can't find the time, I'll handle it. :)
