### ISSUE TITLE
Package metadata

### ISSUE THREAD

**Issue by coot** [haskell/haddock#1493]
I would like haddock to be aware of at least rudimentary package metadata.  As as a start the package name of what is being build. The rationale for that is splitting the `haddocks` generated content page (the tree of modules) into a list of trees one per package.   The simple way to solve this is to pass `--package-name` & `--package-version` to haddock which would be written to the interface file file; when `haddock` generates the content page it reads the interface files it would know which interfaces comes from which package:

I have a [draft pr](https://github.com/haskell/haddock/pull/1492
) where I infer package names from interface file names.

**Comment by coot** [comment]
@Kleidukos let me know what do you think.  Here's a print screen of what I have so far:
![image](https://user-images.githubusercontent.com/698209/170639013-68f6e3e1-821e-4f4f-8d71-fe40077b0c6d.png)

I think it would be nice to also print package version next to its name.

**Comment by coot** [comment]
Related to haskell/cabal#7669.

**Comment by Kleidukos** [comment]
@coot I love it.
