### ISSUE TITLE
The methods of `Eq` and `Ord` do not show up in their haddocks

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#1528]
https://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#t:Eq

**Comment by ulysses4ever** [comment]
Dup of #549

**Comment by harpocrates** [comment]
Fixed a while ago, no? https://hackage.haskell.org/package/base-4.10.0.0/docs/Prelude.html#t:Eq and later seem fine.

**Comment by Lysxia** [comment]
I was probably very very tired when I submitted this :)
