### ISSUE TITLE
Tooltips use unrelated type synonyms

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#1573]
In the following hyperlinked source, the function `showName :: Name -> String` is unexpectedly shown to have type `Name -> FilePath` in the tooltip that appears when you hover over it https://hackage.haskell.org/package/template-haskell-2.19.0.0/docs/src/Language.Haskell.TH.Syntax.html#showName

I haven't tracked down the cause of the issue, but this may end up being something to be fixed on GHC's side rather than haddock.

**Comment by Kleidukos** [comment]
Ticket has been migrated to https://gitlab.haskell.org/ghc/ghc/-/issues/24860
