### ISSUE TITLE
Unrendered since annotations

### ISSUE THREAD

**Issue by treeowl** [haskell/haddock#1577]
I just noticed that the rendered documentation for [`Data.Semigroup`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Semigroup.html) is missing `@since` annotations for `Generic` and `Generic1` instances. I figured that someone must have forgotten to put them in, but that is not the case! See, for example, the [documentation for `Last`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Semigroup.html#t:Last) vs. [the source for `Last`](https://hackage.haskell.org/package/base-4.17.0.0/docs/src/Data.Semigroup.html#Last). While all the derived instances have `@since` annotations in the source, not all of them are rendered.

**Comment by Kleidukos** [comment]
Thanks for reporting this. This ticket now lives at https://gitlab.haskell.org/ghc/ghc/-/issues/24857
