### ISSUE TITLE
Support GHC 9.6.1

### ISSUE THREAD

**Issue by jlwoodwa** [haskell/haddock#1588]

**Comment by LaurentRDC** [comment]
I think a Hackage revision to bump `base` bounds should be enough, at least for `haddock-library`. 

I can build and run `hakyll` (which depends transitively on `haddock-library`) if I add `allow-newer: haddock-library:base` to `cabal.project`.

**Comment by andreasabel** [comment]
`main` currently has these outdated dependencies:
```
haddock-library[main !]$ cabal outdated
base >=4.5 && <4.17 (latest: 4.18.0.0)
base-compat >=0.12.0 && <0.13 (latest: 0.13.0)
hspec >=2.4.4 && <2.10 (latest: 2.10.10)
```

**Comment by andreasabel** [comment]
I published revision 2 with the latest dependencies: https://hackage.haskell.org/package/haddock-library-1.11.0/revisions/
