### ISSUE TITLE
Linearity hidden in multi-line type signatures

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#1589]
The last arrow in the function `Data.Array.Mutable.Linear.slice` is linear, but is not displayed as such:

https://hackage.haskell.org/package/linear-base-0.3.0/docs/Data-Array-Mutable-Linear.html#v:slice

**Comment by sidkshatriya** [comment]
This happens in many multi-line type signatures in https://hackage.haskell.org/package/text-builder-linear-0.1/docs/Data-Text-Builder-Linear-Core.html also:

e.g. `appendBounded`, `appendExact`, etc. The last arrows in these functions should be `⊸` (or `%1 ->`) but that does not happen.

cc: @Bodigrim

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
