### ISSUE TITLE
hlint CI chokes on `MIN_VERSION_ghc(9,5,0)` (?)

### ISSUE THREAD

**Issue by andreasabel** [haskell/haddock#1590]
https://github.com/haskell/haddock/blob/a75c08f885207fafbd5dec5bc061cf2f81a7f268/haddock-api/src/Haddock/InterfaceFile.hs#L126
https://github.com/haskell/haddock/actions/runs/4457586699/jobs/7828749016#step:4:14
```
hlint: #error Unsupported GHC version
  in haddock-api/src/Haddock/InterfaceFile.hs  at line 132 col 1
  CallStack (from HasCallStack):
    error, called at ./Language/Preprocessor/Cpphs/CppIfdef.hs:113:21 in cpphs-1.20.9.1:Language.Preprocessor.Cpphs.CppIfdef
  hlint completed with status code 1
```
First failing hlint CI run on `main`: commit e8fe591fecf626fe4540ed666d147c61728c890f
- #1518

Is this an upstream issue? (Latest `hlint`, `3.5`, _is_ used.)

**Comment by Kleidukos** [comment]
This appears to be related to https://github.com/ndmitchell/hlint/issues/1442

**Comment by andreasabel** [comment]
Ping @philderbeast .
