### ISSUE TITLE
How to tell from Haddocks whether a data type is a re-export?

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/haddock#1595]
I asked the below question in [the Haskell subreddit](https://old.reddit.com/r/haskell/comments/13h8vvp/how_to_tell_from_haddocks_whether_a_data_type_is/) and did not find a solution. Therefore I'm asking the same question here. Also, if the answer (as I expect) is "it's not possible", I hope someone can give an overview of the changes required to make it possible.

---

I'm trying to figure out whether it's possible to tell from Haddock documentation whether a given data type is a distinct type with the same name or a re-export of a type defined in another module.

For example, if I [search for `IO` on Hoogle](https://hoogle.haskell.org/?=&hoogle=IO%20is%3Aexact&scope=), the result for `data IO a` points to many different modules, e.g. the `Hedgehog.Internal.Prelude` module from the `hedgehog` package: https://hackage.haskell.org/package/hedgehog-1.2/docs/Hedgehog-Internal-Prelude.html#t:IO. As far as I can see, there is no way to tell, from the docs alone, that this type is a re-export of `Prelude.IO`. However, this must be the case since the following code typechecks:

```haskell
import qualified Hedgehog.Internal.Prelude

test1 :: Hedgehog.Internal.Prelude.IO ()
test1 = (pure () :: Prelude.IO ())
```

If I, on the other hand, [search for e.g. `Query` on Hoogle](https://hoogle.haskell.org/?hoogle=Query+is%3Aexact&scope=set%3Astackage), I will get lots of data types called `Query` that are *not* the same, ie. not re-exports. For example:

1. https://hackage.haskell.org/package/postgresql-simple-0.6.5/docs/Database-PostgreSQL-Simple.html#t:Query
2. https://hackage.haskell.org/package/aws-0.24/docs/Aws-DynamoDb-Commands-Query.html#t:Query

Which means that the following will *not*  typecheck:

```haskell
import qualified Aws.DynamoDb.Commands.Query
import qualified Database.PostgreSQL.Simple

test2 :: Aws.DynamoDb.Commands.Query.Query
test2 = (undefined :: Database.PostgreSQL.Simple.Query)
```

Hence my question: given the Haddocks for two datatypes with the same name, is there a way to tell if they're the same?

**Comment by runeksvendsen** [comment]
> Neither of these is perfect, but a rule of thumb is that if something is a re-export from some other package it will not have a "source" link, while haddocks within a package will have a source link.

I should probably have noted that I'm interested in not just determining whether or not something is a re-export, but also what it is a re-export of — ie. in which module it was originally defined.

In essence, I'm looking for the ability to construct a set of "equivalent types", where all members of this set are considered "the same type" by GHC when doing type checking. For the `IO` type this would include (but not necessarily be limited to) the following fully qualified identifiers:

* [GHC.Types.IO](https://hackage.haskell.org/package/ghc-prim-0.10.0/docs/GHC-Types.html#t:IO)
* [GHC.IO.IO](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-IO.html#t:IO)
* [Hedgehog.Internal.Prelude.IO](https://hackage.haskell.org/package/hedgehog-1.2/docs/Hedgehog-Internal-Prelude.html#t:IO)
* [Prelude.Compat.IO](https://hackage.haskell.org/package/base-compat-0.13.0/docs/Prelude-Compat.html#t:IO)
* [Protolude.IO](https://hackage.haskell.org/package/protolude-0.3.3/docs/Protolude.html#t:IO)
* [Protolude.Base.IO](https://hackage.haskell.org/package/protolude-0.3.3/docs/Protolude-Base.html#t:IO)
* [Relude.Base.IO](https://hackage.haskell.org/package/relude-1.2.0.0/docs/Relude-Base.html#t:IO)
* [RIO.Prelude.Types.IO](https://hackage.haskell.org/package/rio-0.1.22.0/docs/RIO-Prelude-Types.html#t:IO)
* [BasePrelude.IO](https://hackage.haskell.org/package/base-prelude-1.6.1/docs/BasePrelude.html#t:IO)
* [GHC.Prelude.Basic.IO](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Prelude-Basic.html#t:IO)

Notably, this set includes both the newtype `GHC.Types.IO` and the data type `Prelude.IO` (which GHC apparently considers equivalent). I wonder if GHC is somehow hardcoded to consider these two (seemingly distinct, since one is `newtype IO a` and the other is `data IO a`) types as equivalent.

> Further, one can open the instance of datatypes, should any instances be defined, and note those instances are defined in `base` which likely means the datatype itself is also defined there.

This seems very promising. However, when I open the Haddocks for e.g. [Hedgehog.Internal.Prelude.IO](https://hackage.haskell.org/package/hedgehog-1.2/docs/Hedgehog-Internal-Prelude.html#t:IO) there are no "Source" links for any of the instance declarations. Is this because it's a re-export?

**Comment by gbaz** [comment]
Right. That's what I said above. "if something is a re-export from some other package it will not have a "source" link, while haddocks within a package will have a source link."

Note if you click to open the instances you can see where those are defined.

![image](https://github.com/haskell/haddock/assets/1125849/ced8d3f9-fa52-4ed5-b0ce-884ccae6f4e8)

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
