### ISSUE TITLE
Can't install haddock through cabal

### ISSUE THREAD

**Issue by alt-romes** [haskell/haddock#1596]
Running `cabal install haddock` results in
```
Error: cabal: Could not resolve dependencies:
[__0] trying: haddock-2.27.0 (user goal)
[__1] trying: haddock:-in-ghc-tree
[__2] trying: haddock-api-2.27.0 (dependency of haddock -in-ghc-tree)
[__3] next goal: ghc (dependency of haddock-api)
[__3] rejecting: ghc-9.4.4/installed-9.4.4 (conflict: haddock-api =>
base^>=4.16.0, ghc => base==4.17.0.0/installed-4.17.0.0)
[__3] rejecting: ghc-9.6.1, ghc-9.4.5, ghc-9.4.4, ghc-9.4.3, ghc-9.4.2,
ghc-9.4.1, ghc-9.2.7, ghc-9.2.6, ghc-9.2.5, ghc-9.2.4, ghc-9.2.3, ghc-9.2.2,
ghc-9.2.1, ghc-9.0.2, ghc-8.10.7, ghc-8.10.2, ghc-8.10.1, ghc-8.8.3,
ghc-8.8.1, ghc-8.6.5, ghc-8.6.4, ghc-8.6.1, ghc-8.4.4, ghc-8.4.3, ghc-8.4.1,
ghc-8.2.2, ghc-8.2.1, ghc-9.2.3.20220620 (constraint from non-upgradeable
package requires installed instance)
[__3] fail (backjumping, conflict set: ghc, haddock-api)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, haddock, ghc, haddock-api,
haddock:in-ghc-tree
Try running with --minimize-conflict-set to improve the error message.
```

This was reported on the #ghc IRC and I confirmed I was unable to install it.
The `-in-ghc-tree` bit in the error message seems suspicious.

Thanks!

**Comment by Kleidukos** [comment]
@alt-romes cf https://gitlab.haskell.org/ghc/ghc/-/issues/23178 

If hackage uploads do not happen from this repo I cannot help much.

**Comment by simonmichael** [comment]
Adding this here because it sounds related: haddock 2.29.0 on hackage is currently not installable because it depends on haddock-api which has conflicting dependencies base-4.16 and ghc-9.6.

cabal-install's --allow-newer option can be used as a workaround, eg `cabal install haddock-2.29.0 --allow-newer`. It builds with ghc 9.6/base 4.18 so it seems that haddock-api's base upper bound could be relaxed, eg to base<4.19.

**Comment by ulysses4ever** [comment]
@Kleidukos do you think you could relax base bound in haddock-api on have through a revision, by any chance? That is, 4.17 » 4.19. Looks like a no-brainer to me, since we checked that it builds.
