### ISSUE TITLE
Pretty Printing of Types in Declarations

### ISSUE THREAD

**Issue by emiflake** [haskell/haddock#1599]
# Motivation

Previously, large types in declarations looked like this:

![image](https://github.com/haskell/haddock/assets/7753922/71d7e1ae-d3f8-4bbc-bb19-0b983958e02b)

(Note the type runs out of the bounds of the browser window to the right.) 

Thankfully, after [#1525](https://github.com/haskell/haddock/pull/1525), large types in declarations look like this:

![image](https://github.com/haskell/haddock/assets/7753922/ebbdab37-4ca4-4980-ab4d-ce1a9e577914)

This is a significant improvement! However, it should be obvious that this is still not ideal. It still takes quite a lot of work to mentally parse the type. I think we can do better.

# Proposal

Extend the pretty-printing capabilities of the html backend (for the types in declarations only!!) with indent-level and column-alignment information, which allows us to output the whitespace necessary to nicely align and indent the types. This could apply to type-level lists, repeated infix type operators or longer tuples.

One approach to allow this is to wrap the pretty printing code in a `State` monad which we can use to keep track of the current column. (Though if we were using Lucid, we can use `HtmlT` with a `State` monad more cleanly.)

### Produced HTML

There are many ways to accomplish this indentation using HTML:

- We could directly insert `<br>` tags for newlines, and `&nbsp;` to force spaces.
    
    This cannot be styled, so cannot be, for instance, disabled on mobile, or configured in any way.
    
- We could use `<br>` *plus* a span that is of a particular length.
    
    This *can* be styled, but requires two entities.
    
- We could wrap each indentation level in blocks, and use the browser’s native layout engine in our favour.
    
    Sadly this creates a tree structure in the HTML which doesn’t mirror the tree structure of the actual code. 
    

### Example

Looking again at the example constructor in the motivation section, we ought to be able to format it like we would format code. (The actual specific stylistic choices don’t matter here — anything is better than how it is now.) 

```haskell
PTxInfo 
  (Term s (PDataRecord 
    '[ "inputs" := PBuiltinList PTxInInfo
     , "outputs" := PBuiltinList PTxOut
     , "fee" := PValue 'Sorted 'Positive
     , "mint" := PValue 'Sorted 'NoGuarantees
     , "dcert" := PBuiltinList PDCert
     , "wdrl" := PBuiltinList (PAsData (PTuple PStakingCredential PInteger))
     , "validRange" := PPOSIXTimeRange
     , "signatories" := PBuiltinList (PAsData PPubKeyHash)
     , "datums" := PBuiltinList (PAsData (PTuple PDatumHash PDatum))
     , "id" := PTxId 
     ]))
```

Pending further improvements/overhauls of the pretty-printing (**#1598**, incidentally the status/plan to proceed with this could be clarified), we can extend the existing pretty-printing as appropriate.

cc: @t1lde, @Kleidukos

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
