### ISSUE TITLE
Update readthedocs (by pushing tags?)

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/haddock#1604]
Currently, the official site [www.haskell.org/haddock/](http://www.haskell.org/haddock/) redirects to readthedocs (RTD), which, by default, shows some version of Haddock it calls "latest". Apparently, this corresponds to the tip of the `ghc-head` branch. The only other version it suggests is v2.20 from 2018. So, no docs for the latest release!

The issue seems to be is that releases are tagged in a way that confuses RTD. In particular, I believe, you have to put `v` in front of the version if you want to use subproject names in the tags (e.g. `haddock-api-v2.26`), while the current tags look like `haddock-api-2.26-release`. At least, that's what working for Cabal. 

So, it'd be cool if you could push a tag recognizable by RTD at least for the latest release  (2.26, I think), so that we have publicly available docs for the release.

**Comment by Kleidukos** [comment]
will do, thanks!
