### ISSUE TITLE
Haddock renders ambiguous type/value names strangely

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#1608]
_(Originally observed in https://github.com/ekmett/lens/pull/1042.)_

Here is a stripped-down version of Haddocks that you'd find in a typical `lens` module:

```hs
-- Bug.hs
module Bug where

data ReifiedLens = Lens

type Lens = ()

-- | A 'Lens'.
f :: Lens
f = ()
```

Note that the `'Lens'` reference in `f`'s Haddocks is ambiguous, as there is both a type and a data constructor named `Lens`. My reading of [this section](https://haskell-haddock.readthedocs.io/en/latest/markup.html?highlight=prefix#hyperlinked-identifiers) of the Haddock readthedocs is that when such ambiguities arise, Haddock will default to the type name:

> Since values and types live in different namespaces in Haskell, it is possible for a reference such as `'X'` to be ambiguous. In such a case, Haddock defaults to pointing to the type.

This is not what I observe in practice, however. If you render the Haddocks for this module by running the following command:

```
$ haddock Bug.hs -o bug --html
Warning: 'Lens' is ambiguous. It is defined
    * at Bug.hs:4:20
    * at Bug.hs:6:1
    You may be able to disambiguate the identifier by qualifying it or
    by specifying the type/value namespace explicitly.
    Defaulting to the one defined at Bug.hs:4:1
  25% (  1 /  4) in 'Bug'
  Missing documentation for:
    Module header
    ReifiedLens (Bug.hs:4)
    Lens (Bug.hs:6)
```

You will end up with the following HTML page:

![haddock](https://github.com/haskell/haddock/assets/2364661/33a4e618-9bed-4bf2-96a1-d70ed39d6134)

I believe there are two bugs here:

1. The rendered Haddocks say "`RenderedLens`", which is completely different from the original "`'Lens'`". I'm not sure why this happens.
2. Moreover, `RenderedLens` refers to the _value_-level version of `Lens`, not the type-level `Lens`. If I understood the readthedocs correctly, it should be the other way around.

**Comment by ncfavier** [comment]
Note that I can't reproduce this bug on the `ghc-9.6` branch of this repo, so presumably https://github.com/haskell/haddock/pull/1597 helped (cc @FinleyMcIlwaine).

Regarding the buggy code though, [this comment](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Parser-PostProcess.html#v:setRdrNameSpace) looks suspicious to me...

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
