### ISSUE TITLE
Nested {- -} comments in code examples

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#161]
**Original reporter**: _mail-haddock@<hidden>_

This...

``` haskell
-- > {- long comment -}
```

...get's printed out in the haddock document just as you'd expect it to, but...

``` haskell
{-

> {- long comment -}

-}
```

...is not shown at all.

See for example http://n-sch.de/hdocs/test/Test.html

**Comment by harendra-kumar** [comment]
I ran into this and just wondering why not support this? This is valid Haskell and compiler supports the syntax. I don't see a reason why it cannot be implemented in haddock. Either treat any nested comments literally or have a way to escape them by special markup.

Can someone please reopen this issue?

**Comment by harendra-kumar** [comment]
I found a workaround for nested block comments. The following shows the nested comment along with the comment markup ("{- -}")in the generated doc:

    {- | This module
    {\- nested comment here -\}
    -}

But this is just a workaround. Many of those who run into this may not be able to find or imagine about this.
