### ISSUE TITLE
Annotating functions in module signature

### ISSUE THREAD

**Issue by andrewthad** [haskell/haddock#1611]
In a module signatures (`hsig` files), annotating types and functions with haddocks doesn't seem to work. The haddock application doesn't crash, but it just ignores all the documentation that should be attached to the definitions. I'm using haddock 2.27.0 and GHC 9.4.

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
