### ISSUE TITLE
Re-exported module documentation appears twice if imported qualified as well as unqualified

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/haddock#1622]
If a module is imported qualified as well as unqualified then docs for re-export appear twice. For example:
```
module Streamly.Internal.Data.Array
    (
      module Streamly.Internal.Data.Array.Type
    )

where

import qualified Streamly.Internal.Data.Array.Type as A
import Streamly.Internal.Data.Array.Type
```

I noticed the docs for the entire module appearing twice and it was difficult to isolate what the problem was.

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
