### ISSUE TITLE
A few identifier rendering issues, possibly duplicates

### ISSUE THREAD

**Issue by chreekat** [haskell/haddock#1623]
Sorry I don't know how to make reproducers.

In short, https://github.com/brendanhay/amazonka/issues/970 , which I will copy here for ease of reading:

- - - - -
Take for example https://hackage.haskell.org/package/amazonka-s3-2.0/docs/Amazonka-S3.html#v:newPutObject

![image](https://github.com/brendanhay/amazonka/assets/538538/c2565102-122a-46c8-86cc-ee3056b5d82d)

Where is all the `$sel` stuff coming from?

Why are the comments for the first two arguments erroneous?

Maybe related: #1608

**Comment by Lysxia** [comment]
It may be related to the fact that `PutObject` is a record type but gets rendered as a non-record type.

**Comment by chreekat** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/24558

**Comment by chreekat** [comment]
Fixed upstream.
