### ISSUE TITLE
show COMPLETE pragmas in documentation

### ISSUE THREAD

**Issue by olafklinke** [haskell/haddock#1625]
This is a feature request. 
Much like `MINIMAL` pragmas for type classes, the `COMPLETE` pragma is used to signal a contract, namely that a set of functions (patterns in this case) cover a type. While the `MINIMAL` pragma is picked up by Haddock, `COMPLETE` is not. Thus the only way for a library user to discover this information is either to look at the source or compile with Wincomplete-uni-patterns.

Relevant haskell-cafe-thread: [Wincomplete-uni-patterns and bidirectional patterns](https://mail.haskell.org/pipermail/haskell-cafe/2024-January/136568.html)

A prominent example and test case is the module [Data.Sequence.Internal](https://hackage.haskell.org/package/containers-0.7/docs/Data-Sequence-Internal.html) which contains two `COMPLETE` pragmas.

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket,but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
