### ISSUE TITLE
haddock release with quickjump fix

### ISSUE THREAD

**Issue by gbaz** [haskell/haddock#1631]
It would be great to get a patch release for haddock with https://github.com/haskell/haddock/pull/1522

Hackage currently is producing docs without quickjump working, since we upgraded haddock and ghc to be relatively recent.

**Comment by edsko** [comment]
Workaround that was pointed out to me, and might be useful to others also: quickjump still works when you're inside a module, just not on the index page for the package.

**Comment by Kleidukos** [comment]
Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate the ticket :)
