### ISSUE TITLE
ghc-head branch

### ISSUE THREAD

**Issue by coot** [haskell/haddock#1632]
I find it quite difficult to use `ghc-head` branch which requires `ghc-9.7` (which one probably needs to install from `ghc` source repo, rather than with something like `ghcup`).  The `CONTRIBUTING` file mentioned that PRs should be opened against that branch, is this correct? Why then we have the `main` branch?  It is quite confusing which branch should be used when trying to do something which actually works (currently `ghc-9.{4,6}` works fine, bug `ghc-{head,9.8}` require `ghc-9.7` for some reason, while the `main` branch has quite old version of haddock:

branch | haddock-api version
-------|--------------------
main   | 2.27.0
ghc-9.6| 2.28.0
ghc-9.8| 2.28.0
ghc-head|2.28.0

This is also confusing when compared to which `haddock` versions are published with `ghc`:

ghc version | haddock version
------------|----------------
9.6.4       | 2.29.2
9.8.1       | 2.30.0

The `CONTRIBUTING.md` file should explain it better to make it much less confusing.

**Comment by coot** [comment]
It even seems that the `ghc-9.6` branch is not compatible with `ghc-9.6` right now :frowning_face:.

**Comment by coot** [comment]
The `CONTRIBUTING.md` file should mention that the preferred way of building `haddock` is using the  `ghc` repo & hadrian build system.

**Comment by Kleidukos** [comment]
Now that Haddock lives in GHC I'm not sure if this issue is still relevant. Your opinion?
