### ISSUE TITLE
MathJax formula at beginning of paragraph breaks in bullet lists

### ISSUE THREAD

**Issue by jasagredo** [haskell/haddock#1633]
This code

```
-- | An example
--
-- - __A__:
--
--   \(X\)
--
-- - __B__:
--
--     \(X\)
--
-- - __C__:
--
--     \(X\) blah
--
-- - __D__:
--
--     blah
--     \(X\)
--
-- - __E__:
--
--     blah
--     blah \(X\)
--
-- - __F__:
--
--     blah
--      \(X\)
--
-- - __G__:
--
--     blah
--     \(X\) blah
```

Renders as:
![image](https://github.com/haskell/haddock/assets/9791461/9db6e614-bcc0-40ce-ad6c-ba400d777651)

- 🚫 in `A`, it seems we have to align the paragraph with the end of `__` otherwise the paragraph is not regarded as belonging to the bullet point.
- ✔️ in `B` the formula as the first thing in the paragraph works.
- ✔️ in `C` we see it can be followed by anything and it works.
- 🚫 in `D` we see that if it is the first thing on a line but not the first thing of the paragraph it breaks.
- ✔️ in `E` we see that if we put something in front it works.
- ✔️ in `F` even just an space works.
- 🚫 in `G` putting something afterwards does not work.

I think this is also a manifestation of #774

**Comment by Kleidukos** [comment]
Hi, thank you for this PR, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)
