### ISSUE TITLE
Add some way to refer explicitly to either a type/class constructor or a data constructor

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#21]
**Original reporter**: _david.waern@<hidden>_

There's no way to refer explicitly to either a type/class constructor or data constructor when there are more than one of these with the same name.  Perhaps introduce a special syntax for them?  (eg. ':C' means data constructor C?)

**Comment by harpocrates** [comment]
Duplicate of #667. Technically it's the other way around, but that issue has more useful information attached to it.
