### ISSUE TITLE
() is not hyperlinked anymore

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#211]
**Original reporter**: _sol@<hidden>_

I adapted the tests for now:

https://github.com/ghc/haddock/commit/85665a576b76cdc856ad3727b28a8abe5d185d59

I have no idea which commit introduced that regression.  Finding the commit in a systematic way would require code bisection in GHC's source tree (due to changes to Haddocks interface file and the GHC API).  However, I'm not aware of a systematic way to do code bisection in GHC's source tree.

**Comment by gbaz** [comment]
Closing in favor of #368 which is more general but also covers this, I think.
