### ISSUE TITLE
Investigate unexpected change with (Monad (Either e))

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#212]
**Original reporter**: _sol@<hidden>_

see: https://github.com/ghc/haddock/commit/47e6c8e77a4b8edbb1e4869ba5a0f76ee71ad8bb

**Comment by gbaz** [comment]
is this issue still live? looks sort of rotted to me...

**Comment by harpocrates** [comment]
> is this issue still live? looks sort of rotted to me...

Me too. Closing.
