### ISSUE TITLE
references to identifiers are not recognized in emphasized text

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#221]
**Original reporter**: _sol@<hidden>_

Minimal example:

``` haskell
-- | /some `foo` text/
foo :: Int
foo = 23
```

**Comment by harpocrates** [comment]
This is fixed since at least version 2.17.4. Proof:

```haskell
module Fixed where

-- | /some `foo` text/
foo :: Int
foo = 23
```

Generates

<img width="272" alt="screen shot 2018-07-01 at 4 04 16 pm" src="https://user-images.githubusercontent.com/10766081/42138266-b3d13626-7d48-11e8-9c41-aa1ca80823fa.png">
