### ISSUE TITLE
Ugly definition lists

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#241]
**Original reporter**: *duairc*

The HTML produced by definition lists in the comments of class methods is currently displayed rather uglily when styled by ocean.css. For example, the HTML page produced by haddock for following code is displayed (in Firefox, but in other browsers too) as follows:

```haskell 
module Blah (Blah (..)) where
 
-- | The 'Blah' type class.
class Blah a where
    -- | The 'foo' method. Here is a definition list:
    --
    --     [foo] This is the foo entry of the definition list.
    --
    --     [bar] This is the bar entry of the definition list.
    foo :: a -> a
    
    -- | The 'bar' method.
    bar :: a -> a

```

In Firefox:

[[Image(http://i.imgur.com/NMyfTOY.png)]]

As you can see, it's quite confused and unreadable. The problem is to do with floats not being cleared properly.

I've made a small change to ocean.css (and am attaching a patch with this change below) that significantly improves how the documentation for the above is displayed. This what it looks like now:

[[Image(http://i.imgur.com/LjTmNXF.png)]]

**Comment by Helkafen** [comment]
Looks fine on master, no weird spaces.

**Comment by Fuuzetsu** [comment]
@Helkafen did you check that the code in OP doesn't look like http://i.imgur.com/NMyfTOY.png ? This ticket, when migrated from Haddock Trac has lost its attachment. Weird spacing in my comment is after using the attachment that was there.
