### ISSUE TITLE
Expose the HTML backend so that simply comments can be converted

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#243]
**Original reporter**: _david.waern@<hidden>_

The haddock library currently does not expose functionality for
converting strings of Haddock markup to HTML.

This functionality is needed by Hackage, for example, to render
package description text. Hackage duplicates the haddock parsing and
lexing code rather than using it directly:

http://code.haskell.org/hackage-server/Distribution/Server/Pages/Package/

We should add functions to the Haddock API for parsing the markup.

**Comment by gbaz** [comment]
I believe this was resolved by https://github.com/haskell/hackage-server/commit/0617b1bb8e485bc56aeec1dc49abae5e76bddc89
