### ISSUE TITLE
don't output warning about missing rts package every time haddock generates docs

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#251]
**Original reporter**: _juhpetersen@<hidden>_

Haddock outputs this warning

``` haskell
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0
```

everytime it generates documentation which seems kind of futile.

I don't think any rts docs exist and probably never will?
So could haddock please just ignore rts?

Perhaps I can try to come up with a patch later.

**Comment by gbaz** [comment]
I think this no longer happens? Or am I missing something?
