### ISSUE TITLE
Links to anchors have confusing labels

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#262]
**Original reporter**: _gcrosswhite@<hidden>_

At the moment, when you link to an anchor in haddock using something like `"MyModule#anchor"`, the link on the generated page just says `"MyModule"`.  This is very confusing because it looks like the link is taking one to the module page, when really it goes to a specific anchor on that page.  It would be great if either the anchor name could be added to the label for the link to make it clear where the links is going, or if there were a way one could manually specify the label of the link --- say, by borrowing the syntax used by URLs to specify the label using a space, such as `"MyModule#anchor label goes here"`.

**Comment by MorrowM** [comment]
Implemented by #1181 

@Kleidukos This issue can be closed.

**Comment by Kleidukos** [comment]
jolly good, thank you
