### ISSUE TITLE
--hoogle drops module qualifier in instances

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#263]
**Original reporter**: *hvr@\<hidden\>*

For instance, `base` defines the following two instances:

```haskell #!hs
instance Applicative (ST s) where
    pure = return
    (<*>) = ap

instance Applicative (Lazy.ST s) where
    pure = return
    (<*>) = ap
```

However, in `--hoogle`'s output the `Lazy.` qualifier is dropped, resulting in

```haskell #!hs
instance Applicative (ST s)
instance Applicative (ST s)
```

**Comment by Fuuzetsu** [comment]
@ndmitchell is this new output style OK with you? If we just want to qualify some things, the printing will have to become a bit more involved.

```
module Foo where

import Data.ByteString.Lazy as BL
import Data.ByteString as BS

class Foo a where
  fooId :: a -> a

instance Foo BL.ByteString where
  fooId = id

instance Foo BS.ByteString where
  fooId = id
```

gives

```
-- Hoogle documentation, generated by Haddock
-- See Hoogle, http://www.haskell.org/hoogle/

@package fake
@version 0.0.0.0

module Foo
class Foo a
fooId :: Foo a => a -> a
instance Foo.Foo Data.ByteString.Lazy.Internal.ByteString
instance Foo.Foo Data.ByteString.Internal.ByteString
```

**Comment by ndmitchell** [comment]
It seems weird to qualify the types in instance declarations but not type signatures. But I'm OK with it as it stands, or fully qualified, or completely unqualified. Generally defaulting to more qualification is probably better, since stripping the unwanted information is easy but adding it is impossible.

I also note that if `fooId` is a reexport from another module there is no way to tell, so perhaps it should be `Bar.fooId` if `fooId` is a reexport?

**Comment by Fuuzetsu** [comment]
>It seems weird to qualify the types in instance declarations but not type signatures.

We can do that too if you prefer.

I have not considered re-exports, I'll look into it.

**Comment by ndmitchell** [comment]
Currently Hoogle can only handle unqualified names, but I'm certainly happy to fix that, and the more information I have the more I can do unambiguously. At the same time, having approximate information about types is usually enough for Hoogle. I also note that in reality it's both the module and package qualification that uniquely determines a name. So basically do whatever you think is best, partly based on the needs of other people using the Hoogle output, and erring on the side of more information than less, and I'll adjust Hoogle accordingly.

**Comment by hvr** [comment]
+1 for disambiguating the hoogle output! While it's not meant for it, you can get quite far using the `.txt` Hoogle output for comparing API versions.

**Comment by Fuuzetsu** [comment]
It's actually pretty trivial to disambiguate it, we just change `showSDocUnqual` to something that prints qualifiers. I will do it soon.
