### ISSUE TITLE
add a --show=MODULE and/or --ignore-hide to complement --hide=MODULE

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#266]
**Original reporter**: _carter.schonwald@<hidden>_

add a --show=MODULE and/or --ignore-hide to complement --hide=MODULE

having some sort of --ignore-hide flag would be great for making

cabal haddock --internal  behave as expected, because currently, cabal haddock --internal won't generate the docs for an exposed module which has a module level pragma telling haddock to hide that.

**Comment by cartazio** [comment]
Yes I guess I filed this one too.   :)
Both the show module foo and  more global ignore hide flavors would be useful. :)

**Comment by harpocrates** [comment]
@cartazio https://github.com/haskell/haddock/pull/752 Implements `--show=MODULE` and `--show-all`. Does that cover your use cases?

**Comment by cartazio** [comment]
Should be!  Unless there’s other things they mean than what I imagine.

It does make me curious how cabal emulates the show internal stuff in
global cabal confit

**Comment by harpocrates** [comment]
Good! Once you get to try this out, feel free to close the issue. 

> It does make me curious how cabal emulates the show internal stuff in global cabal config

Wonder no more and discover for yourself! If you pass in `-v` to cabal, you can see enough debug output of commands that are run to piece together what it is doing. Normally, Cabal passes `--hide=<mod>` for every internal module. When you pass it the show internal stuff flag, it just skips over hiding the internal modules.

**Comment by cartazio** [comment]
And now show / show all ignores module hide pragmas?

**Comment by harpocrates** [comment]
> And now show / show all ignores module hide pragmas?

Yes. More accurately, it overrides hide (either passed in the command line earlier, or in the file's `OPTIONS_HADDOCK`). So, short of patching the `--show-all` flag into Cabal, you could see what command to Haddock Cabal is issuing and manually re run that, but with `--show-all` appended to the very end of the command.

**Comment by cartazio** [comment]
Ok.

I assume I can’t have my cabal config set to add this globally to cabal
haddock  invocations until the ghc and associated  haddock pair lands? Or
when? :)


Thx!!!

**Comment by cartazio** [comment]
Seriously thx.  This has been like the most pleasant bug/feature request
experience I’ve had with haddock to date


(Grumbles about how Data fam constructor docs are pinched to the right in
crazy ways)

**Comment by harpocrates** [comment]
Closed in 5141e4b76af8462e49abdf48e44bb9cddb183383.
