### ISSUE TITLE
Broken source links in class methods

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#273]
**Original reporter**: _uwe@<hidden>_

in class methods, e.g. in Prelude class Eq there are
source links for (==) and (/=). These source links
contain ASCII control char %01 and %02 (in binary format,
not in %01 and %02 syntax as shown below)
http://hackage.haskell.org/packages/archive/%01/%02/doc/html/src/GHC-Classes.html#%3D%3D

Example page is http://hackage.haskell.org/package/base-4.6.0.1/docs/Prelude.html#t:Eq

Found on hackage, haddock version there was 2.13.2, that one could
not be selected, in the form for the bug report 2.13.1 was the
latest version

**Comment by gbaz** [comment]
I'm positive this was a user-error in generating the docs, since base docs have to be built and uploaded rather than generated on-server. Closing as such.
