### ISSUE TITLE
How about add response file support for long command line argument list

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#285]
**Original reporter**: *sray@\<hidden\>*

Here is my origin post for cabal-install [https://github.com/haskell/cabal/issues/1681]

After install a lot of hackages, it seems impossible to regenerate an overall local document index. As for my case, with 160+ hackages, the command line argument list is more than 50k characters long, where the limitaion on Windows is 32768.

As Mikhail suggested on the link above, this problem could be solved by adding support for response file [http://gcc.gnu.org/wiki/Response_Files]

**Comment by randen** [comment]
This will (I have tried it) fail with something like "-title=hscolour-1.22: Colourise Haskell code." as the spaces in this param get split up.

**Comment by 23Skidoo** [comment]
@randen 
What about `-title="hscolour-1.22: Colourise Haskell code."`?

**Comment by randen** [comment]
@Fuuzetsu, sorry this has become more complicated that I had thought.

@23Skidoo, my lazy, but non-standard thing I did temporarily was to force the response file creator to signal the appropriate parsing by using a newline (carriage-return, whatever--any of the various CR/NL combos) to separate each param in the response file, then the consumer can just split back out with "lines".  Not really standard, but, except for being able to provide on of CR or NL in a param value, it covers more cases than splitting on any white-space.
