### ISSUE TITLE
Ambiguous fixity annotation when only a single operator out of a grouped type signature inside a class definition has a fixity annotation

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#287]
**Original reporter**: _haddock@<hidden>_

To reproduce:

``` haskell
class Bug a where
  (<*<), (>*>) :: a -> a -> a
  infix 9 <*<
```

The haddock output just shows | infix 9 | here since there is only one fixity annotation for that line, except here it is not clear which operator the annotation corresponds to.

I think the proper way to address this would be to split apart lines of a class in general, instead of adding complex special case logic to detect the scenario of attaching a single fixity annotation to a method group (which does not fit into the current design whatsoever).

I'll look into implementing this feature whenever I get some free time and energy unless somebody else wants to.

**Comment by harpocrates** [comment]
This appears to have been fixed somewhere between 2.17.3 and 2.18.2 since on the latter I get:

![screen shot 2018-02-09 at 9 00 20 am](https://user-images.githubusercontent.com/10766081/36039615-d8c15894-0d77-11e8-8037-84adde87aff4.png)

**Comment by alexbiehl** [comment]
Alec, could you try Haddock 2.19? Especially Operators.hs test should be a good test case cfir various things related to fixities.

**Comment by harpocrates** [comment]
@alexbiehl Just did, and things are looking spiffy!

![screen shot 2018-02-09 at 9 06 43 am](https://user-images.githubusercontent.com/10766081/36039870-a0b4857e-0d78-11e8-8e36-7feea7bc58f1.png)

**Comment by alexbiehl** [comment]
Alright, good. I fiddled around there a few days ago. What is strange
thoughy, I think **< and friends are missing documentation! I think they
should have the same docs as **>!

Alec Theriault <notifications@github.com> schrieb am Fr., 9. Feb. 2018,
18:07:

**Comment by alexbiehl** [comment]
Fixed, see https://github.com/haskell/haddock/commit/4b4733a05c7bf35d98ed82f2a62d4771db1fb788
