### ISSUE TITLE
Work on the module re-export stuff

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#290]
**Original reporter**: _fuuzetsu@<hidden>_

This is just a ticket to track the state of module re-exports bugs as it seems the whole re-export machinery needs a longer look.

The tickets that are in need of attention are #269, #254, #232, #225, #174, #164 (?).

**Comment by ntc2** [comment]
Issues #597 and #584 are also related.

**Comment by ntc2** [comment]
A related feature request: #185.

**Comment by gbaz** [comment]
should be resolved by #688

**Comment by gbaz** [comment]
The only bug not resolved by earlier work or #688 seems to be https://github.com/haskell/haddock/issues/164.

(the feature request, which is orthogonal, also is outstanding)

As such I think this can be closed, as it no longer tracks a meaningful work-unit.
