### ISSUE TITLE
Generate docs for orphan instances in the module where they are defined

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#297]
**Original reporter**: *mail+haddock-trac@\<hidden\>*

It often happens that orphan instances are declared in an `.Instances` module of a package, e.g. http://hackage.haskell.org/package/vect-0.4.7/docs/Data-Vect-Double-Instances.html.

It is very impractical that Haddock generates empty pages for this.

It would be great if haddock could always generate instance documentation for orphan instances in modules are defined.

**Comment by chowells79** [comment]
This really would be very handy.

**Comment by mgsloan** [comment]
What happened with this?  Is hackage using too old of a haddock?

`Store` has many instances, I'd expect to see them here https://hackage.haskell.org/package/store-0.1.0.1/docs/Data-Store-Internal.html

Pinging @phadej since he implemented the fix in https://github.com/haskell/haddock/pull/449

**Comment by phadej** [comment]
@mgsloan seems to be in haddock bundled with ghc8: http://docs.futurice.com/haskell-mega-repo/futurice-prelude-0.1.9.0/Futurice-Prelude-Internal-Orphans.html

**Comment by bgamari** [comment]
Oleg Grenrus <notifications@github.com> writes:

> @mgsloan seems to be in haddock bundled with ghc8:
> http://docs.futurice.com/haskell-mega-repo/futurice-prelude-0.1.9.0/Futurice-Prelude-Internal-Orphans.html
>
Indeed, we'll need to update the Haddock version used by the Hackage
documentation builder. @davean, how can we make this happen?

**Comment by davean** [comment]
I can take care of that, what has to happen?

**Comment by bgamari** [comment]
davean <notifications@github.com> writes:

> I can take care of that, what has to happen?
>
You will need to update on the builder to GHC to 8.0.1 and ensure that
the haddock shipped with this release is used by the builder.

Cheers,

- Ben

**Comment by bgamari** [comment]
Ben Gamari <ben@smart-cactus.org> writes:

> [ Unknown signature status ]
> davean <notifications@github.com> writes:
>
>> I can take care of that, what has to happen?
>>
> You will need to update on the builder to GHC to 8.0.1 and ensure that
> the haddock shipped with this release is used by the builder.
>
Any news on this?

**Comment by Blaisorblade** [comment]
This (?) is hiding instances for `Text` from `Text`, because its instances are somehow technically orphans (?) (instances in `Data.Text`, datatype definition in `Data.Text.Internal`):
http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html#g:4

**Comment by phadej** [comment]
It's not *this*. IIRC the bug was present in haddock shipped with GHC7.10 already. Seems there aren't an issue for that though. There are similar bugs reports already
- https://github.com/haskell/haddock/issues/469
- https://github.com/haskell/haddock/issues/372
