### ISSUE TITLE
Record field documentation doesn't align with field name

### ISSUE THREAD

**Issue by tibbe** [haskell/haddock#301]
As can be seen in the screenshot below (look for `flushInterval`) the record field documentation doesn't always align with the field name.

![haddock-issue](https://cloud.githubusercontent.com/assets/17277/3091559/385c1992-e59f-11e3-8cf0-59a032d2c078.png)

```
$ haddock --version
Haddock version 2.14.2, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
```

**Comment by Rufflewind** [comment]
Getting `<dl>` to display like a table involves compromises: you have to fix the width of one of the columns and if the content overflows that width something bad will happen.  In this particular case, the text pushed the other column downwards.

I suggest scrapping `<dl>` entirely and replacing it with something like:

    <ul>
      <li><dfn>host :: !Text</dfn> Server hostname or IP address</li>
      <li><dfn>port :: !Int</dfn> Server port</li>
      …
    </ul>

and then use `display: table-row` and `display: table-cell` to tabularize them.
