### ISSUE TITLE
Consider implementing `--qual` aliased

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/haddock#325]
Currently it does nothing. We should either remove the constructor for it and remove it from option list or make it work. I think with the other modes `--qual` offers, we can get away without making it work as it seems like it would involve a lot of effort:

```
  | OptAliasedQual    -- ^ Uses aliases of module names
                      --   as suggested by module import renamings.
                      --   However, we are unfortunately not able
                      --   to maintain the original qualifications.
                      --   Image a re-export of a whole module,
                      --   how could the re-exported identifiers be qualified?
```

**Comment by sjakobi** [comment]
The Hi Haddock changes are going to remove the `aliased` option.
