### ISSUE TITLE
Migrate User Guide from DocBook to Markdown

### ISSUE THREAD

**Issue by sol** [haskell/haddock#338]
I would give the User Guide much more love if I could write it in Markdown.  So why not migrate it?  In addition, is GH pages an option for hosting?

**Comment by lfairy** [comment]
I've taken a liking to [Asciidoc](http://asciidoctor.org/). It supports a few things that Markdown doesn't, like callout boxes and tables.

Also, at its core it's just an alternative syntax for DocBook. So it's easy to convert between the two.

**Comment by Fuuzetsu** [comment]
Probably just going to go with Markdown and gh-pages because I'm far too lazy to regenerate/upload it each time. Just need to take some time to do the leap. Will probably also point the haskell.org/haddock page to those pages at that point so we never have to update that again, it's a pain.

**Comment by ntc2** [comment]
I think this is all done, except for updating the homepage to point to the new docs (but the new docs are RestructuredText, not Markdown).

The new doc sources: https://github.com/haskell/haddock/tree/master/doc /*.rst

Rendered version: http://haskell-haddock.readthedocs.io/en/latest/index.html.

Since there is already Issue #360 for updating the website, this current issue can probably be closed.

**Comment by gbaz** [comment]
@ntc who has permissions on the readthedocs account? It could possibly use some updating?

**Comment by gbaz** [comment]
@ntc2 who has permissions on the readthedocs account? It could possibly use some updating?

**Comment by ntc2** [comment]
I certainly don't :) I'm not sure who does, but @harpocrates was quite involved at one point. Maybe he knows?

**Comment by harpocrates** [comment]
Nope, I have no idea. This was set up before I started working on Haddock.

I was just recently complaining about this, since the website is now a couple years out of date with the code 😄.

**Comment by gbaz** [comment]
Perhaps its @Fuuzetsu ?

Otherwise, could we just bring back a master branch for docs?

**Comment by harpocrates** [comment]
> Otherwise, could we just bring back a master branch for docs?

That would be a headache - everyone seems to assume that `master` is the branch for development. Rather than do that, I'd prefer to start hosting new documentation elsewhere (perhaps directly with github pages).

**Comment by gbaz** [comment]
Ah, @bgamari owns this project  (https://readthedocs.org/profiles/bgamari/) Ben, can you help us?

**Comment by gbaz** [comment]
ok i think this is fixed and we might as well close this old issue

**Comment by Fuuzetsu** [comment]
>Perhaps its @Fuuzetsu ?

I tried to log in just now: they don't know my e-mail address nor GitHub, so I assume I don't have access or at least I never signed up.

**Comment by bgamari** [comment]
For the record,I have configured the RtD `latest` version to build from `ghc-head`.
