### ISSUE TITLE
Pattern synonyms do not show types nor attached haddock descriptions

### ISSUE THREAD

**Issue by ekmett** [haskell/haddock#341]
It seems when I generate haddocks for pattern synonyms I get neither a signature for the synonym nor any attached haddock entry.

I am currently generating about 40,000 of these. It'd be really nice to be able to tell what they meant.

For bonus credit, if the pattern synonym is a simple bidirectional synonym it'd be really nice to be able to see the pattern, too.

**Comment by sjakobi** [comment]
Looks like this was fixed in #709.
