### ISSUE TITLE
JSON Backend

### ISSUE THREAD

**Issue by jfischoff** [haskell/haddock#352]
It would nice to be able to directly dump out a version the Interfaces that Haddock generates as JSON

This need is being driven by some Hackage redesign work. We would like to distribute the generation of documentation in a safe way (HTML is hard to keep safe) and also have output we can cache forever. 

Having an external format in JSON will allow Hackage to cache the Interface information forever, and more easily change the presentation layer. There are other benefits as well, in terms of analysis, and future Haddock features e.g, pass through markup.

I am volunteering to do this work.

**Comment by beerendlauwers** [comment]
Is there a package that provides this functionality? I'd like to look up the type and definition of a function in the JSON. (and probably whatever else we could cram into it)

**Comment by alanz** [comment]
I'm pretty sure leksah should be able to provide this

**Comment by beerendlauwers** [comment]
[This seems pretty interesting](https://hackage.haskell.org/package/leksah-server-0.15.0.7/docs/IDE-Utils-FileUtils.html). I'll see what happens when I have this puke out JSON.
