### ISSUE TITLE
Package keys versus installed package identifiers

### ISSUE THREAD

**Issue by edsko** [haskell/haddock#362]
(This applies to ghc 7.10, build from the `ghc-7.10` branch, commit 25e416dfba7ea6007f9c74699e1d6a9efd65db9b, Jan 26, and using corresponding submodule for `haddock` in the `ghc/utils` directory.)

The interface files installed when building ghc (with `HADDOCK_DOCS` enabled) contain package _keys_ in their link environments; for instance, `~/local/src/ghc/libraries/transformers/dist-install/doc/html/transformers/transformers.haddock` contains mappings such as

```
(trans_H9c1w14lEUN3zdWCTsn8jG:Control.Monad.Trans.Reader.runReaderT, trans_H9c1w14lEUN3zdWCTsn8jG:Control.Monad.Trans.Reader)
```

However, the interface files subsequently installed contain _installed IDs_ installed; for example, `~/.cabal/share/doc/x86_64-osx-ghc-7.10.0.20150128//mtl-2.2.1/html/mtl.haddock
` contains mappings such as

```
(mtl-2.2.1:Control.Monad.Cont.Class.callCC, mtl-2.2.1:Control.Monad.Cont.Class)
```

This gets even more confusing for tools when the subsequently installed packages redefine the home module for packages installed as part of `ghc`; for example, the link environment for `mtl.haddock` (same file as the previous example) also contains 

```
(trans_H9c1w14lEUN3zdWCTsn8jG:Control.Monad.Trans.Reader.runReaderT, mtl-2.2.1:Control.Monad.Reader)
```

which contains both a package key _and_ and installed package ID.

I don't know which is correct (package key or package installed ID), but it should at least be consistent. Moreover, _if_ it is decided that it ought to be the installed package ID rather than the package key (which seems a reasonable choice), then perhaps it's not a good idea to reuse `ghc`'s `Module` type in the `LinkEnv`, because that datatype very specifically refers to a package _key_, not a package ID.

**Comment by Fuuzetsu** [comment]
I bellieve the general idea is to use package keys everywhere and using a package ID in interface file is simply a bug. This should really go into 7.10 though I don't know if I can fix it on time. If someone wants to step in then feel free.

**Comment by edsko** [comment]
I'm not sure actually -- package keys are mostly an internal notion for ghc, and used for linking etc. Installed package identifiers are used to uniquely identify a single package in the system. It's possible for a two installed packages to have different installed package IDs but equal package keys. It would make sense to me if Haddock uses package installed IDs instead of keys (although admittedly it would make my life slightly more complicated because internally I would need to translate back to package keys in my code). But @dcoutts may have a different opinion here.

**Comment by edsko** [comment]
Actually, correction: I believe these are not installed IDs but _source_ IDs. That's probably worse than either the installed ID or the package key.

**Comment by edsko** [comment]
Yes, confirmed, they are source IDs. I have a workaround for this now, looking up the source ID in the ghc package DB and mapping them to package keys.

**Comment by dcoutts** [comment]
Given what haddock is doing, and that it's tightly connected to the GHC API, I think using package keys consistently is ok for haddock.

**Comment by edsko** [comment]
Fixed by having Cabal pass the right package key to Haddock (https://github.com/haskell/cabal/pull/2466).
