### ISSUE TITLE
Haddock sometimes fails with "internal error: expectJust getPackageDetails"

### ISSUE THREAD

**Issue by edsko** [haskell/haddock#363]
Function `modulePackageInfo` from the `haddock-api` library calls 

```
getPackageDetails :: DynFlags -> PackageKey -> PackageConfig
```

from `ghc`, which throws the runtime error `expectJust getPackageDetails` when the package key does not exist in the database. Note that this expects a package _key_; so this is almost certainly related to #362.

**Comment by Fuuzetsu** [comment]
See https://github.com/haskell/haddock/issues/353

**Comment by dcoutts** [comment]
Looks like `--package-name` and `--package-version` ought to be required args.

**Comment by edsko** [comment]
Fixed by updating to latest Cabal (https://github.com/haskell/cabal/pull/2439).
