### ISSUE TITLE
haddock-library-1.1.1 introduces conflicts for Attoparsec

### ISSUE THREAD

**Issue by jessicah** [haskell/haddock#364]
I was trying to build the latest version of pandoc using cabal install; however, I now have conflicts with Attoparsec due to the vendored version you now provide.

Please see https://github.com/jgm/pandoc/issues/1526#issuecomment-69530777 for some more details about the issue.

**Comment by Fuuzetsu** [comment]
We vendor attoparsec as that's what we use for parsing, however as we ship with GHC and are expected to work inside GHC tree (i.e. with GHC HEAD and even local tree changes), we can not depend on anything that doesn't live inside GHC tree. The hack is to bundle a stripped down version of attoparsec with Haddock.

Having said that, I don't know what to do about your problem. Maybe we can just rename the modules we vendor and spirit the problem away. I think a quicker and more robust solution would be to use the GHC pragma PackageImports which allows you to specify which package you want the module to come from. This is something for you to try ;).

**Comment by sol** [comment]
I would have assumed that non-exposed modules can have what ever name we prefer, without effecting other packages?

Is this a bug in GHC or cabal?

**Comment by gbaz** [comment]
Can we close this?

**Comment by alexbiehl** [comment]
Not Sure. Currently we include an attoparsec subset as convenience lib in haddock-library. Not sure how these interfere. /cc @hvr

**Comment by sol** [comment]
I think close.  What ever the issue was, I don't think there is anything wrong Haddock.  Naming conflicts with non-exposed modules is something very common, this is why there are not exposed in the first place.

**Comment by sol** [comment]
As @denisshevchenko stated:

> Thank you very much, John! I reinstalled cabal-install 1.20.0.3 - and now all works fine.

Closing.

**Comment by sol** [comment]
> As @denisshevchenko stated:
>> Thank you very much, John! I reinstalled cabal-install 1.20.0.3 - and now all works fine.

I got that wrong, the thread is about multiple issues.  I still vote for closing.
