### ISSUE TITLE
Duplicate `MonadFix (ST s)` instance shown

### ISSUE THREAD

**Issue by ggreif** [haskell/haddock#365]
At the bottom of page:
http://hackage.haskell.org/package/base-4.7.0.2/docs/Control-Monad-Fix.html#v:mfix

**Comment by Fuuzetsu** [comment]
It's not a duplicate, it is for two different types called `ST`. You can pass options to Haddock which will qualify the names more a bit. Maybe we could introduce an option to do this with a Haddock pragma on per-module basis but for now closing this as invalid.

**Comment by ggreif** [comment]
Okay, I see. Thanks for the explanation @Fuuzetsu!
When you click into the `ST` links you get carried to the strict/lazy monad definitions.

Interestingly this set me on the wrong track:
I cliked on [Source](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/Control-Monad-Fix.html#mfix) which took me to
``` haskell
instance MonadFix (ST s) where
        mfix = fixST
```
There was no indication whatsoever that there might be other definitions in this file.

**Comment by Fuuzetsu** [comment]
You went to source of `mfix` of the class not of the instance: the instance might have been elsewhere. Haddock simply shows all instances it knows about.
