### ISSUE TITLE
ghc-head needs 8e06728afb0784128ab2df0be7a5d7a191d30ff4

### ISSUE THREAD

**Issue by ezyang** [haskell/haddock#371]
I was attempting to update GHC to use Cabal head but I ran into
https://github.com/haskell/cabal/issues/2297#issuecomment-77616193

I want to just cherry-pick the relevant commit onto `ghc-head`; is there anything wrong with doing that/

**Comment by Fuuzetsu** [comment]
No, there is nothing wrong with that, feel free to do so. It has not been done merely due to lack of time on my end.

**Comment by hvr** [comment]
has this been resolved by now?

**Comment by Fuuzetsu** [comment]
I saw the commit in ghc-head at least so should be.
