### ISSUE TITLE
Documentation for base-4.8.0.0 doesn't mention Show Double or Show Float instances

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#372]
The [current release candidate documentation for `base-4.8.0.0` on Hackage](https://hackage.haskell.org/package/base-4.8.0.0/candidate) does not mention the `Show` instance for `Float` in `Double` in [any](https://hackage.haskell.org/package/base-4.8.0.0/candidate/docs/Prelude.html#t:Float) of the [places](https://hackage.haskell.org/package/base-4.8.0.0/candidate/docs/Prelude.html#t:Double) that I [can](https://hackage.haskell.org/package/base-4.8.0.0/candidate/docs/Prelude.html#t:Show) think of. The code for the `Show` instances themselves still appear to be fine ([in `GHC.Float`](https://hackage.haskell.org/package/base-4.8.0.0/candidate/src/GHC/Float.hs)).

**Comment by Fuuzetsu** [comment]
That and many other instances are now not showing up but it's not due to a change on Haddock end at the very least. Maybe @hvr can explain.

**Comment by RyanGlScott** [comment]
This issue is popping up more and more frequently. Some other victims of this issue include:

* [`aeson`](https://github.com/bos/aeson/issues/375) ([example](http://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-Types.html#t:FromJSON))
* [`MonadRandom`](https://github.com/byorgey/MonadRandom/issues/23) ([example](http://hackage.haskell.org/package/MonadRandom-0.4.2.2/docs/Control-Monad-Random-Class.html#t:MonadRandom))
* `text` ([example](http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html#t:Text))
* [`text-show`](https://github.com/RyanGlScott/text-show/issues/18) ([example](http://hackage.haskell.org/package/text-show-3.2.2/docs/TextShow.html#t:TextShow))

The discussion in https://github.com/ku-fpg/hermit/issues/173 possibly reveals [a workaround](https://github.com/ku-fpg/hermit/issues/173#issuecomment-185545800)?

cc @andrewthad

**Comment by Blaisorblade** [comment]
Based on https://github.com/haskell/haddock/issues/297#issuecomment-239144362, #469 might be a dup. At least in the case of `Text`, in #469 and in ku-fpg/hermit#173, the trigger is that the datatype and the instances are not defined in the same module (even if in the same package), and the problem started with GHC 7.10 apparently.
Rather than the workaround in https://github.com/ku-fpg/hermit/issues/173#issuecomment-185562501 (newtype wrappers to avoid orphans), which I guess is what @RyanGlScott meant to link to, most packages could just move instance definitions together with datatype definitions — or at least, `text` could.

**Comment by RyanGlScott** [comment]
@Blaisorblade: By "workaround", I mean [this comment in particular](https://github.com/ku-fpg/hermit/issues/173#issuecomment-185545800), which reveals how GHC solves this problem internally. I don't know if the same idea can be used in Haddock.

I agree that while most packages should just define instances alongside their datatype/class definitions, it's simply not feasible for every package. `text-show` in particular suffers from this, since I split up the multitude of `TextShow` instances across several orphan-instance containing modules to (1) avoid having to compile everything in one mega-module, which would likely eat up all your RAM, and (2) keep me sane as I try to make incremental changes when developing it.

**Comment by Blaisorblade** [comment]
@RyanGlScott Ah, now I get why you linked to that specific comment, thanks for elaborating.

I agree these orphans are fine.

OT on orphans (sorry but couldn't resist): `text-show` sounds like an excellent use case for modules and separate compilation! Why would anyone add restrictions on that? `</snark>` (The snark is not against you but against coherence).
Also, in the cases under discussion, datatypes and instances are probably exported together (modulo internal packages), so they're safe I assume. I only checked for `text` though.

**Comment by RyanGlScott** [comment]
This was fixed in https://github.com/haskell/haddock/pull/724.
