### ISSUE TITLE
Make polymorphic functions more obvious in haddock.

### ISSUE THREAD

**Issue by fhaust** [haskell/haddock#376]
This was discussed on reddit ([here](http://www.reddit.com/r/haskell/comments/2x4nzb/feature_request_make_polymorphic_functions_more/)), so I will just quote it here to make it an _official_ enhancement proposal:

> In light of the current AMP and FTP discussions there were (few) voices that claimed that more polymorphic functions would lead to more confusion when learning the language.
> I propose a simple way that will probably reduce this confusion: enrich the haddock documentation with specialized versions of the typeclass instances.
> Instead of just listing the instanced typeclasses list functions from the typeclass module, but instead of giving their polymorphic definitions list the specialized one for the current data type.
> In turn this would mitigate another problem beginners are facing: for some datatypes it is not imediatly obvious what you can do with them because they take functionality from their class instances (Data.Sequence being a prime example there).

In the discussion there is a nice mockup of the concept by [/u/tobiasgw](http://www.reddit.com/user/tobiasgw): http://imgur.com/jz43fGy

**Comment by TimoFreiberg** [comment]
I think this is done: https://hackage.haskell.org/package/containers-0.5.10.2/docs/Data-Sequence.html#t:Seq

**Comment by alexbiehl** [comment]
@TimoFreiberg You are right. Closing this.
