### ISSUE TITLE
Add tests for Hoogle backend

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#377]
The Hoogle backend seems to be prone to bitrot - its not something many people see, and it seems to accumulate bugs over time. Is it possible to add a module/expected result test, and then we can be sure things don't regress in future?

**Comment by Fuuzetsu** [comment]
Certainly planned.

**Comment by ndmitchell** [comment]
Thanks :). I also plan to document all the remaining bugs, after testing properly with the new GHC.

**Comment by ndmitchell** [comment]
I just download Haddock from GHC 7.10.1 and tested out all the bugs I was aware of which didn't have tickets, which I think covered 5 separate issues. Testing shows they're all fixed with the latest version, which is great news, so now there's nothing I'm aware of which is Haddock's fault and is not ticketed.

**Comment by Fuuzetsu** [comment]
Great to hear.

**Comment by RyanGlScott** [comment]
Testing support for `--hoogle` was added in https://github.com/haskell/haddock/pull/438.
