### ISSUE TITLE
haddock-library-1.2.0 test suite failure

### ISSUE THREAD

**Issue by peti** [haskell/haddock#378]
Citing from http://hydra.cryp.to/build/697284/nixlog/1/raw:

    test/Documentation/Haddock/ParserSpec.hs:58: (best-effort)
    1) Documentation.Haddock.Parser.parseString, when parsing text, allows to backslash-escape characters
         Falsifiable (after 39 tests): 
         expected: DocString "\r"
          but got: DocString "\\"
         '\r'

**Comment by Fuuzetsu** [comment]
I fixed this in https://github.com/haskell/haddock/commit/f42970cc6d62a63529874bf7dfe0f6e3c010dd13 but 7.10 went out before this commit made it in. It will be in point release though I don't have a date. You can safely put the above commit as a patch for time being.

I'll close this for now.

**Comment by peti** [comment]
I've simply disabled the test suite for the time being.
