### ISSUE TITLE
Classes with multiple methods are printed wrongly in the Hoogle output

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#380]
Given:

```
module Test where
class MyClass a where
    (+++++), (//////) :: a -> a -> a
    (****), logBase :: a -> a -> a
    foo, bar :: a -> a -> a
```

Using the GHC 7.10 release of Haddock, if I run `haddock --hoogle Test.hs --package-name=test --package-version=1` I get the output:

```
module Test
class MyClass a
(+++++, //////) :: MyClass a => a -> a -> a
(****, logBase) :: MyClass a => a -> a -> a
foo, bar :: MyClass a => a -> a -> a
```

The final line is fine, but the other lines have incorrect operator brackets.

**Comment by mrhania** [comment]
Another one that is probably fixed. I get this output:

    module Test
    class MyClass a
    (+++++) :: MyClass a => a -> a -> a
    (//////) :: MyClass a => a -> a -> a
    (****) :: MyClass a => a -> a -> a
    logBase :: MyClass a => a -> a -> a
    foo :: MyClass a => a -> a -> a
    bar :: MyClass a => a -> a -> a

**Comment by ndmitchell** [comment]
Looks awesome. Would be great to get a test added as per #377 (since this has broken and been fixed at least once before).

**Comment by RyanGlScott** [comment]
A test for this was added in https://github.com/haskell/haddock/pull/438.
