### ISSUE TITLE
Proposal: render math formulas

### ISSUE THREAD

**Issue by solatis** [haskell/haddock#382]
Hello,

As I understand it, the topic of Haddock being able to render math formulas in a pretty way comes up sometimes. There are several ways to tackle this issue:

 * use graphviz (like doxygen)
 * write a pure haskell implementation of mathtex;
 * use a client side library like [MathJax](https://www.mathjax.org/)

I would like to start a discussion whether there is any interest in tackling this issue. Personally, I think the MathJax way might be the most pragmatic since it renders everything purely client side: you will not have any additional dependencies for rendering the HTML, and the only thing that is required is including some javascript library and generating proper javascript when math expressions are encountered in haddock markup.

I would be interested in the point of view of the maintainers of haddock on this issue.

**Comment by hvr** [comment]
As MathJax is well-established by now, I think that'd be the fastest/easiest way to get us nicely rendered math-formulas... What markup-syntax on the Haddock side would you suggest for dropping into math-mode? Maybe simply `$f(x) = x$` like in TeX?

**Comment by Fuuzetsu** [comment]
So yes, it does come up frequently. Straight away I think we can abandon the idea that we'll render the formulas ourselves due to extra dependencies and whatnot.

As usual with these proposals, there's a question ‘can every backend do something reasonable with it?’. This question is mostly why we don't allow inlining HTML.

But in this case yes, I think we can do reasonable things. We can render in both HTML (somehow) and LaTeX, and just leave as-is in Hoogle.

I think mathjax is the way to go here. Downside is that it requires JavaScript to be enabled but in that case I think it's OK for the users to just see the formula.

So in the end I'd have no problem with such a feature.

Regarding syntax, I'd like to use `$foo$` but I fear the clash between named blocks. What do you think?

**Comment by hvr** [comment]
Then maybe `$$f(x) = x$$` instead?

**Comment by idontgetoutmuch** [comment]
$$...$$ actually means something in latex. E.g.

```
$$
\begin{aligned}
\mathbb{C}[X_u, X_t \,\vert\, X_0 = x_0] &=
\mathbb{E}\Bigg[\Bigg( \sigma\int_0^u e^{-\beta(u - s)}\mathrm{d}W_s  \Bigg)
                \Bigg( \sigma\int_0^t e^{-\beta(t - s)}\mathrm{d}W_s  \Bigg)\Bigg] \\
&=
\sigma^2e^{-\beta(u + t)}
\mathbb{E}\Bigg[\Bigg(\int_0^u e^{\beta s}\mathrm{d}W_s\Bigg)
          \Bigg(\int_0^t e^{\beta s}\mathrm{d}W_s\Bigg)\Bigg] \\
&=
\sigma^2e^{-\beta(u + t)}
\mathbb{E}\Bigg[\Bigg(\int_0^t e^{\beta s}\mathrm{d}W_s + \int_t^u e^{\beta s}\mathrm{d}W_s\Bigg)
          \Bigg(\int_0^t e^{\beta s}\mathrm{d}W_s\Bigg)\Bigg]
\end{aligned}
$$
```

**Comment by hvr** [comment]
> but maybe the `$$...$$` is not necessary when using mathjax?

The `$$` would be for Haddock's markup (and would be translated into whatever mathjax needs to see)

**Comment by idontgetoutmuch** [comment]
Is this doable at Zurihac?

**Comment by Fuuzetsu** [comment]
Hm, I don't see why not. As long as the person hacking it doesn't get bogged down on trying to  decide for best syntax or something, it should certainly be doable.

There are extra administrative issues such as probably having to bump interface file versions and package versions but those can just be ignored, I can handle them aftewards.

**Comment by idontgetoutmuch** [comment]
Here's an example of what I'd like to be able to do (using mathjax)

![examplemathjax](https://cloud.githubusercontent.com/assets/1550265/7549743/bf17a65c-f63a-11e4-9129-948aff0935c6.png)

**Comment by idontgetoutmuch** [comment]
I am trying to understand how to modify haddock. Just loading it into ghci took some effort

```
haddock/haddock-api $ ghci -isrc -i../haddock-library/src -idist/build/autogen -package ghc -optP-include -optPdist/build/autogen/cabal_macros.h
```

**Comment by Fuuzetsu** [comment]
The `.ghci` file already does that for you.

**Comment by idontgetoutmuch** [comment]
That's what I hoped but I get

```
Prelude> :l src/Haddock.hs
:l src/Haddock.hs

src/Haddock.hs:66:8:
    Could not find module ‘GHC’
    It is a member of the hidden package ‘ghc-7.10.1’.
    Use -v to see a list of the files searched for.
```

**Comment by idontgetoutmuch** [comment]
It's not clear how we should handle \. It would be nice to be able to write e.g.

```
where $$a = \pi r^$$
```

but I think at the moment we need to write

```
where $$a = \\pi r^$$
```

This is irksome as it means you can't just copy paste latex from an existing document.

**Comment by Fuuzetsu** [comment]
You'll have to not use `takeUntil` that we define because that automatically deals with `\` You still have to consider escaped `$`.

We're probably not be keeping the `$$` syntax in the end by we'll see.

**Comment by hvr** [comment]
@Fuuzetsu what do you think of the syntax `\( ... \)` as suggested by @bkaes  in https://github.com/haskell/haddock/pull/397#issuecomment-102759967 ?

**Comment by idontgetoutmuch** [comment]
@hvr I have done both.

**Comment by hvr** [comment]
@idontgetoutmuch :cake:  :-)

**Comment by recursion-ninja** [comment]
Very excited, I will begin using this as soon as the feature is released!

**Comment by Fuuzetsu** [comment]
Thanks to other people, this has been achieved in #465
