### ISSUE TITLE
Source links on instances not properly aligned in Firefox

### ISSUE THREAD

**Issue by hesselink** [haskell/haddock#384]
Firefox (both 37.0.2 and 39.0a2):

![screen shot 2015-04-24 at 16 58 52](https://cloud.githubusercontent.com/assets/75477/7321576/50a404ec-eaa3-11e4-9b6c-d315d08a7c1e.png)

Chrome (42.0.2311.90)

![screen shot 2015-04-24 at 16 59 01](https://cloud.githubusercontent.com/assets/75477/7321588/5c95128c-eaa3-11e4-8805-2a8a4caff2eb.png)

**Comment by Fuuzetsu** [comment]
Hm, I think someone told me about this already and I think they had some CSS which made it go away… I think it may have been @cartazio…

**Comment by hvr** [comment]
I observed that the `float:right` css attribute on the `class=link` seems to cause this for firefox, and also `td.src`'s `white-space:nowrap` seems to be related as well... but I know too little about CSS to understand what's really going on here...

**Comment by Rufflewind** [comment]
Appears to be a [known (and very old) bug](https://bugzilla.mozilla.org/show_bug.cgi?id=488725).  Basically, `whitespace: nowrap` + `float: right` = weird behavior.

One could probably work around this bug by capturing all the elements on the left inside a `<span style="float: left">`.  As a precautionary measure, on could also add a [clearfix](https://css-tricks.com/snippets/css/clear-fix/) on the parent `<td>` to prevent it from collapsing, although my testing seem to indicate that this isn't necessary on Firefox at least.

**Comment by Fuuzetsu** [comment]
@Rufflewind could you send a quick patch? `haddock-api/resources/html/Ocean.std-theme/ocean.css` is the file. I can eye the changes if you don't have time to build Haddock and try it out yourself. If it's done today-ish then it can go into the release.
