### ISSUE TITLE
Contents page has broken (local) links for modules.

### ISSUE THREAD

**Issue by amurrayc** [haskell/haddock#385]
This is with ghc 7.10.1 on OSX 10.10.3 compiled from source (although the ghcformacosx version seemed to behave the same).
Cabal and cabal-install 1.22.3.0
Haddock from ghc, hackage (2.16.0) and git behave similarly.

I have `documentation: True` and `hyperlink-source: True` in my `~/.cabal/config`

The links to modules on the contents page (`~/.cabal/share/doc/x86_64-osx-ghc-7.10.1/index.html`) are relative and therefore broken as the actual page referred to is in a subdir named after its package.

It seems that commit `﻿6e95f42907970c9cbb9f6279509a4bf5542ffae4` modified the `ModuleTree` so that the nodes refer to a `SourcePackageId` instead of a `PackageKey`.  Unfortunately when `Haddock.Backends.Xhtml.Names.ppModule` calls `moduleUrl` on this to get the anchor href it looks for the `Module`, constructed with the `SourcePackageId`, in `html_xrefs` where it was stored with a `PackageKey`. Thus no match is found and a local link is created.

Extending the `ModuleTree.Node` to carry an extra parameter so that it contains both the `PackageKey` and `SourcePackageId` and modifying `Haddock.Backends.Xhtml.mkNode` so that `htmlModule` uses the `PackageKey` and `htmlPkg` uses the `SourcePackageId` seems to work.  If that makes sense I could make a pull request but I'm not certain I fully understand all the ramifications.

**Comment by Fuuzetsu** [comment]
Aha, this is our https://ghc.haskell.org/trac/ghc/ticket/10206

@thoughtpolice was interested in getting this fixed

If you have some code you want to send, go ahead and submit a PR. Code that we might have to make some edits to is much better than no code at all.

**Comment by amurrayc** [comment]
I'm just getting to know the GitHub workflow and I think I erred by overrunning the commit description. The consequence being that my pull request seems to be a new issue (#386).  Sorry about that but I hope it's useful.

**Comment by Fuuzetsu** [comment]
That's what GitHub does always, don't worry.

I can't test your change for few more days so I'll have to let it sit there for a bit.

**Comment by thoughtpolice** [comment]
Awesome! Thank you for the fix; it looks just fine here, although I'll be sure to run a more thorough test before 7.10.2 :)

**Comment by thoughtpolice** [comment]
(FWIW, I've pushed this to `ghc-head` and `master`.)
