### ISSUE TITLE
Source HTML is invalid XML

### ISSUE THREAD

**Issue by snoyberg** [haskell/haddock#393]
This may in fact be an hscolour bug instead, in which case, please let me know and I'll reopen there.

I was processing some HTML files generated by Haddock, when I came across an example that had `&&` in an attribute value. Such values would need to be escaped, e.g. `&amp;&amp;`. One example is line 93 of:

http://hackage.haskell.org/package/linear-1.16.1/docs/src/Linear-Trace.html

This can theoretically cause trouble for HTML processing as well, but it is certainly invalid for XML content (which all HTML generated by Haddock claims by its XML declaration at the top).

**Comment by Fuuzetsu** [comment]
Hm, yes, I think this is a hscolour problem so closing. If they tell you it's not then I can dig further but I doubt that will be the case.

**Comment by snoyberg** [comment]
@malcolmwallace Ping, does this look like an hscolour issue to you?

**Comment by malcolmwallace** [comment]
Yes, it looks like the parsing of instance heads is seriously wrong.

**Comment by malcolmwallace** [comment]
I uploaded a new version (1.23) of HsColour to hackage, which fixes this problem.

**Comment by snoyberg** [comment]
Thanks!
