### ISSUE TITLE
Document CPP macros

### ISSUE THREAD

**Issue by goldfirere** [haskell/haddock#395]
I wanted to test whether haddock was running over my source code via CPP. I learned, with help on IRC, to check for `__HADDOCK_VERSION__`. (Curiously, plain old `__HADDOCK__` doesn't work.)

Is this documented anywhere? I couldn't find it.

**Comment by Fuuzetsu** [comment]
Haddock itself doesn't set the symbol, cabal does.

See https://github.com/haskell/cabal/blob/master/Cabal/doc/developing-packages.markdown and https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Haddock.hs#L429
