### ISSUE TITLE
Spurious "redundant import" warning generated

### ISSUE THREAD

**Issue by goldfirere** [haskell/haddock#396]
If I say

```
{-# OPTIONS_GHC -fwarn-unused-imports #-}

module Bug where

import Data.Dynamic

-- | This could be instantiated to 'Dynamic'.
foo :: a -> a
foo x = x
```

then I get a warning saying that my `import Data.Dynamic` is unused. But it's not! It's needed to resolve the link to `'Dynamic'` in my Haddock comment.

**Comment by Fuuzetsu** [comment]
There is nothing Haddock can do here except maybe tell GHC to not warn on unused imports but that doesn't sound satisfactory. Doing anything more would mean teaching GHC how to parse identifiers (including renaming) out of the comments and take that into consideration which is rather non-trivial.

On a side-note, having GHC deal with identifiers including renaming mean that Haddock could just skip the renaming phase all together, probably. It might be worth exploring but not for the sake of this ticket.

Anyway unless you have an idea about what Haddock should do here, I'm inclined to close as wontfix.

**Comment by goldfirere** [comment]
I don't know much about the structure of the GHC/Haddock interaction, but would it be possible to call `RnEnv.addUsedRdrNames`? If you can arrange such a call, that would probably do the trick?

Separately, it seems sad that Haddock has to have its own renamer. You can't hook into GHC's?

**Comment by Fuuzetsu** [comment]
>`addUsedRdrNames`

By the time we get to do anything with the env, GHC already ran and presumably produced the warning. I believe we can't do anything here, it's simply too late by the time we even get to in-comment identifiers. As I mentioned before, I think the only way out of this would be for GHC to look for identifiers in comments and add them itself but this sucks: we'd have to teach GHC even more about Haddock which I absolutely don't want to do.

>Separately, it seems sad that Haddock has to have its own renamer. You can't hook into GHC's?

We do use GHC's renamer. The `rename` function in `LexParseRn.hs` calls `lookupGRE_RdrName`. It also decides what to do if the name is ambiguous or not present in the env. This renaming happens after GHC runs and we have a `GlobalRdrEnv` which means we can do something meaningful with the identifiers in the comments.

**Comment by goldfirere** [comment]
That all makes sense.

I agree completely about not teaching GHC anything more about Haddock. It already makes me sad that GHC will fail with a parse error on a misplaced Haddock comment. (This is completely GHC's fault, not Haddock's!)

Oh well. Thanks.
