### ISSUE TITLE
Include fixity information in --hoogle output

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#415]
For example, it would be nice if `infixr 5 ++` was in the Hoogle output, so Hoogle could display it too.

**Comment by Fuuzetsu** [comment]
Sounds reasonable. I think I'll allocate time to Hoogle again this weekend so if you have any more requests/bugs then don't hesitate to file them all.

**Comment by ndmitchell** [comment]
Thanks! I think they are all raised now but will double check later today.

**Comment by ndmitchell** [comment]
I've raised a couple of additional tickets. I've raised them despite not having small test cases, partly because my test cases get outdated so quickly and I can't test with the latest Haddock easily. I suggest you treat them as entries for the test suite, and then if I subsequently discover that the "obvious" thing didn't cover it I'll solve that as a patch to the test suite for you. My usage of Haddock is somewhat weird since lots of people generate Haddock's with old versions - I'm generally working with Haddock bugs from years ago - but it's great if they disappear going forward.

**Comment by Fuuzetsu** [comment]
>I've raised them despite not having small test cases, partly because my test cases get outdated so quickly and I can't test with the latest Haddock easily

OK, don't worry. Of course test-cases are really great so that I even know what I'm fixing but if you can't give a test case for something then you can't and that's that.

**Comment by ndmitchell** [comment]
If you do have any difficulty reproducing, just assume they got fixed, and I'll take the time to follow up with a test case (added to the test suite, once there is such a thing for Hoogle) to "prove" the bug still exists.

**Comment by RyanGlScott** [comment]
This definitely happens on `master`, and a test case for this behavior was added in https://github.com/haskell/haddock/pull/438.
