### ISSUE TITLE
Color console output

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#416]
Should use the ansi-terminal library and work on Windows and Linux.

**Comment by Fuuzetsu** [comment]
We can only use GHC-shipped libraries. In the future I want to get rid of this restriction but it won't be very soon.

**Comment by ndmitchell** [comment]
Sorry, I meant to raise this against Hoogle but must have been in the wrong repo! Redone as https://github.com/ndmitchell/hoogle/issues/133

**Comment by ndmitchell** [comment]
(Feel free to reopen if you think Haddock would benefit from colours - I'm not a particular colour fan, but some people are)
