### ISSUE TITLE
Some classes get their functions included

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#417]
From the `base` Hoogle file I see:

```
class Show a where showsPrec _ x s = show x ++ s show x = shows x "" showList ls s = showList__ shows ls s
```

This should just be:

```
class Show a
```

**Comment by Fuuzetsu** [comment]
So we don't want default implementations, right?

**Comment by ndmitchell** [comment]
Correct - it seems weird to include them given they are not in the haddock docs.

**Comment by Fuuzetsu** [comment]
Maybe it'd be worthwhile including them in the future, I wonder. But for now I'll just remove them from Hoogle output as you ask.

**Comment by ndmitchell** [comment]
The default implementations are very much code, so while it might be reasonable to include them in some mode of something, I'd rather expect that same mode to include bodies of other functions, and at that point you're basically running `cat` on the source :)

**Comment by Fuuzetsu** [comment]
Actually in Haddock master we now have a nice source highlighter and hyperlinker, maybe for default methods at least we could use that. But I guess there is no point if we just use it to generate Source links reliably. Anyway, discussion for another issue.

**Comment by ndmitchell** [comment]
Cool, I'm looking forward to a nice highlighter and hyperlinker - certainly something I can integrate nicely with Hoogle.

**Comment by gbaz** [comment]
is this fixed?

**Comment by alexbiehl** [comment]
I think so

**Comment by gbaz** [comment]
checked latest base.txt and it doesn't seem to have this artifact, so closing.
