### ISSUE TITLE
Instances get non-valid annotations

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#418]
From the `base` Hoogle file I see:

    instance [safe] Show Version

I've previously seen:

    instance [incoherent] ...
    instance [overlap ok] ...
    instance [overlapping] ...

I think all the `[...]` bits should be hidden.

**Comment by mrhania** [comment]
Can't reproduce. Isn't this the same as #168 which was fixed?

**Comment by ndmitchell** [comment]
Certainly looks fixed in the base docs, and I suspect a reasonable fix for #168 would cut it out too. Thanks @mrhania for taking the time to go through all these tickets and spot which are already fixed.
