### ISSUE TITLE
Source links for instances do not point to hyperlinked source

### ISSUE THREAD

**Issue by mpickering** [haskell/haddock#419]
[Here](https://hackage.haskell.org/package/ghc-exactprint-0.3/docs/Language-Haskell-GHC-ExactPrint.html) is a package which demonstrates the problem. All other source links link to the hyperlinked source but the source links attached to instances point to the old-style source code.

**Comment by Fuuzetsu** [comment]
cc @mrhania

**Comment by mpickering** [comment]
From digging around.. it seems like this is expected. Rather than falling back to the old source code maybe it would be best to inject the `line-xxx` divs into the new source representation as well as all the hyperlinking stuff.

**Comment by Fuuzetsu** [comment]
No, I really don't thin it is expected. The `instance` source links were a fairly recent addition and I suspect @mrhania just forgot or didn't know about their existence when implementing the code highlighter/hyperlinker. It should use the new source files and that's' that.

**Comment by mrhania** [comment]
> From digging around.. it seems like this is expected. Rather than falling back to the old source code maybe it would be best to inject the line-xxx divs into the new source representation as well as all the hyperlinking stuff.

Falling back to the old source code is certainly not expected. Generally, once source hyperlinker is enabled, flags `--source-module`, `--source-entity` and `--source-entity-line` (previously provided to make linking to code generated by tools like HsColour possible) are ignored or rather overridden by hyperlinker format. However, until just now hyperlinker was not able to generate anchors so `--source-entity-line` flag was left intact - which you must have provided (or Cabal did it for you for some reason). Haddock even should give you a warning about mixing `--source-*` and `--hyperlinked-source` flags.

Anyway, #420 introduces line anchors, so `--source-entity-line` is now overridden and there should no longer be any reference to non-hyperlinker source.

However, this does not solve this issue. I have run Haddock on `base` and source links for instances point to the wrong lines (line anchors are correct).

> The instance source links were a fairly recent addition and I suspect @mrhania just forgot or didn't know about their existence when implementing the code highlighter/hyperlinker.

Well, hyperlinker is rather independent from source links generation (I haven't really changed the way function source links are generated, just reused existing functionality). Does it always work correctly for HsColour sources (for example, for `base` package)?

**Comment by mrhania** [comment]
Okay, I have just checked it and looks like it is not connected with source hyperlinker at all. Running `cabal haddock --html --hyperlink-source` (which works with HsColour rather than my hyperlinker) on `base` generates wrong source hyperlinks too. For example, in documentation for `Applicative` class declaration (whether the one in `Prelude` or the one in `Control.Applicative`) source links for `ZipList` point to line 128 of `GHC.Base` module (should be line 128 of `Control.Applicative`).

Also, why do not all classes have instance source links attached? For example, `Eq` class does not have them.

**Comment by Fuuzetsu** [comment]
@JPMoresmau implemented the feature, maybe he can answer

**Comment by JPMoresmau** [comment]
Is the issue about instances source links pointing to the wrong location the same as https://github.com/haskell/haddock/issues/383?

**Comment by Fuuzetsu** [comment]
Sounds like it. But you fixed that…

**Comment by gbaz** [comment]
is this fixed?

**Comment by harpocrates** [comment]
Closing this as fixed. The [newest Hackage docs of `ghc-exactprint`](https://hackage.haskell.org/package/ghc-exactprint-0.5.6.1/docs/Language-Haskell-GHC-ExactPrint.html) don't exhibit this problem. I also was not able to replicate locally with

    cabal new-haddock --with-ghc /usr/local/bin/ghc-8.4.2 \
                      --with-haddock /usr/local/bin/haddock-ghc-8.4.2 \
                      --haddock-for-hackage
