### ISSUE TITLE
Test suite failure in AdvanceTypes.hs with GHC 7.10.2

### ISSUE THREAD

**Issue by peti** [haskell/haddock#427]
Citing from http://hydra.cryp.to/build/1047031/nixlog/1/raw:

```
Output for AdvanceTypes.hs has changed! Exiting with diff:
Test suite html-test: FAIL
```

**Comment by Fuuzetsu** [comment]
Yeah, due to GHC change that I failed to catch before release. Will fix in next Haddock release (Soon™), for nixpkgs probably best to disable the tests for Haddock for now.

**Comment by mrhania** [comment]
Just for the record, `PatternSyns` test case is also failing when using GHC 7.10.2, diff:

    204,206c204
    <               <code>
    <                 <a href="#">&gt;&lt;</a>
    <               </code>
    ---
    >               <code>&gt;&lt;</code>

**Comment by Fuuzetsu** [comment]
@mrhania feel free to fix it if you have some minutes, it can take me a while to get around to it

**Comment by alexbiehl** [comment]
I think this can b
