### ISSUE TITLE
Please add anchor links to functions

### ISSUE THREAD

**Issue by enolan** [haskell/haddock#429]
It would be nice if each documented function (and type etc) had a link to its own anchor, so we could easily copy/paste links to specific parts of documentation. E.g. "You want fromMaybe <link>"
This is a fairly common pattern, although I'm struggling to find an example right now. The links are often a single '#' character, and are sometimes invisible or turned grey to be less noticeable until you mouse over the section heading.

Idea is from [this blog post](http://rickdzekman.com/thoughts/the-haskell-user-experience/).

**Comment by Fuuzetsu** [comment]
It has actually already been done and is in master, will be in next release: https://github.com/haskell/haddock/pull/407
