### ISSUE TITLE
Show default signatures for class members

### ISSUE THREAD

**Issue by phadej** [haskell/haddock#439]
Especially _minimal complete definition: Nothing_, when there are generics involved is misleading.

**Comment by Fuuzetsu** [comment]
Please provide a test case and expected output

**Comment by phadej** [comment]
With code 
```hs
{-# LANGUAGE DefaultSignatures #-}
module Example where

-- | Some algebraic structure
class Lattice a where
  -- | Join operation
  joinOp :: a -> a -> a

  -- | Default instance is based on 'Ord'
  default joinOp :: Ord a => a -> a -> a
  joinOp = max

  -- | Meet operation
  meetOp :: a -> a -> a

  -- | Default instance is based on 'Ord'
  default meetOp :: Ord a => a -> a -> a
  meetOp = min
```

Currently we get:
<img width="313" alt="screen shot 2015-08-26 at 19 17 08" src="https://cloud.githubusercontent.com/assets/51087/9499421/155b4e36-4c28-11e5-8309-f8dc878fe8ea.png">

But it would be cool to get:
<img width="404" alt="screen shot 2015-08-26 at 19 20 05" src="https://cloud.githubusercontent.com/assets/51087/9499425/1de87d3a-4c28-11e5-984c-9370240f036a.png">

or even
<img width="405" alt="screen shot 2015-08-26 at 19 24 20" src="https://cloud.githubusercontent.com/assets/51087/9499431/213c010a-4c28-11e5-836a-b17588eabf74.png">

**Comment by Fuuzetsu** [comment]
OK, very useful example, thanks

**Comment by harpocrates** [comment]
Fixed (almost exactly as the first proposal in https://github.com/haskell/haddock/issues/439#issuecomment-135090049) in 245aa215fd3f31b1dd49f9d0d084729bc7adb64b. The problem of supporting docs on default methods is tracked seperately in #30.

Here is what `Example` looks like:

<img width="549" alt="Screen Shot 2019-03-15 at 10 36 49 AM" src="https://user-images.githubusercontent.com/10766081/54450850-a1bad100-470e-11e9-83cb-fca4dfb5348b.png">
