### ISSUE TITLE
Missing instances

### ISSUE THREAD

**Issue by dmwit** [haskell/haddock#444]
The haddocks here don't list a `Fractional` instance for `Double` or `Float`:

http://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#t:Fractional

However, I know there was one, because immediately below that we have `class Fractional a => Floating a` and it *does* list `Floating` instances for `Double` and `Float`.

I'm actually not sure whether this is a haddock bug or a bug elsewhere, but thought it might be worth mentioning.

**Comment by Fuuzetsu** [comment]
This is just like #372 so closing as duplicate.
