### ISSUE TITLE
haddock trips over a comment

### ISSUE THREAD

**Issue by feuerbach** [haskell/haddock#445]
I have a (non-haddock) comment that looks like

```
      -- bla bla
      -- * bla bla
      --   bla bla
      -- * bla bla
      --   bla bla
```

Haddock (distributed with ghc-7.10.2) fails with:

```
        parse error on input ‘-- * ’
```

**Comment by Fuuzetsu** [comment]
It is not a Haddock failure but a GHC one. GHC is in charge of initially extracting and figuring out what comment belongs to what part of the code. By the time we see comments, they have long been extracted out.

See https://ghc.haskell.org/trac/ghc/ticket/8944
