### ISSUE TITLE
Update haskell.org/haddock project URLs

### ISSUE THREAD

**Issue by BartMassey** [haskell/haddock#457]
The documentation at http://haskell.org/haddock is out of date with respect to project URLs. The git repo has moved to [GitHub](http://github.com/haskell/haddock), the issue tracker has been moved [there](http://github.com/haskell/haddock/issues) also.

**Comment by BartMassey** [comment]
Looks like this got fixed but not closed. Closing.

**Comment by bgamari** [comment]
Bart Massey <notifications@github.com> writes:

> Looks like this got fixed but not closed. Closing.
>
Thanks for noticing!
