### ISSUE TITLE
Unicode operators

### ISSUE THREAD

**Issue by andy-morris** [haskell/haddock#458]
At the moment, Haddock doesn't link unicode identifiers. The sequence `@('⊆')@` just renders as `('⊆')`.

However, when I looked in the source to hopefully fix it, I found a comment in the `moduleName` parser saying "But as we **can't** match on unicode characters, this is currently not possible." I couldn't find any mention anywhere of _why_ unicode identifiers can't be matched, though. So I was hoping someone more familiar with the codebase could clarify.

**Comment by bgamari** [comment]
@Fuuzetsu any idea why this might be the case?
