### ISSUE TITLE
Type families type member lists are printed in full evaluated form:

### ISSUE THREAD

**Issue by phadej** [haskell/haddock#466]
Test case:

``` hs
-- Cl.hs
{-# LANGUAGE DataKinds, TypeFamilies #-}
module Cl where

class Cl a where
  type Fam a :: [*]

-- X.hs
{-# LANGUAGE DataKinds, TypeFamilies #-}
module X where

import Cl

data X = X

instance Cl X where
  type Fam X = '[Char]
```

The generated haddock looks like:

<img width="290" alt="screen shot 2015-12-25 at 01 00 43" src="https://cloud.githubusercontent.com/assets/51087/11998321/f33ca7d0-aaa2-11e5-96fa-5227eed3a6dc.png">

where I'd expect it to be

``` hs
type Fam X = '[Char]
```

as written in code

**Comment by harpocrates** [comment]
This was fixed in 2122de5473fd5b434af690ff9ccb1a2e58491f8c. Visual confirmation:

<img width="381" alt="Screen Shot 2019-05-22 at 9 09 06 AM" src="https://user-images.githubusercontent.com/10766081/58177052-77c6e300-7c58-11e9-9aa6-7a0bba71fc3f.png">

A regression test is in order though...

**Comment by harpocrates** [comment]
Test added in 646c8d2752e45d9304402d4134bf1c59006610fa.

**Comment by phadej** [comment]
Thanks!
