### ISSUE TITLE
Array documentation is missing its Read instance

### ISSUE THREAD

**Issue by rwbarton** [haskell/haddock#469]
See http://hackage.haskell.org/package/array-0.5.1.0/docs/Data-Array.html, or the corresponding file from the GHC 7.10.3 binary download.

```
...
(Ix i, Eq e) => Eq (Array i e)   
(Ix i, Ord e) => Ord (Array i e)     
(Ix a, Show a, Show b) => Show (Array a b)   
```

But there is also an instance `instance (Ix a, Read a, Read b) => Read (Array a b)`. (It's even documented in the Haskell 2010 Report!)

I'm guessing this is due to the fact that `Array` and its `Eq`, `Ord` and `Show` instances are defined in module `GHC.Arr` in base, while the `Read` instance is defined in module `GHC.Read`, which imports `GHC.Arr`. Still the instance really should be documented.

**Comment by Blaisorblade** [comment]
Based on https://github.com/haskell/haddock/issues/297#issuecomment-239144362, this is probably a dup of #372, but with a diagnosis.
This diagnosis appears to match the case of `Text` in `text` I mentioned [here](https://github.com/haskell/haddock/issues/297#issuecomment-239144362).

**Comment by RyanGlScott** [comment]
This was fixed in https://github.com/haskell/haddock/pull/724, and will work in the Haddock bundled with GHC 8.4.1. Proof:

![haddock](https://user-images.githubusercontent.com/2364661/35779982-68390dce-09a3-11e8-8192-e802664673ed.png)

**Comment by harpocrates** [comment]
@alexbiehl Can we close this?

**Comment by RyanGlScott** [comment]
Indeed we can :)
