### ISSUE TITLE
Haddock renders * as TYPE Lifted

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#473]
An example of it happening can be found in the Haddocks for [`Data.Functor.Product`](http://downloads.haskell.org/~ghc/master/libraries/html/base/Data-Functor-Compose.html). I imagine Haddock also probably renders `#` as `TYPE Unlifted` as well (at least, I'd guess so from looking at this [similar GHC bug](https://phabricator.haskell.org/D1757)).

Could we render it as `TYPE Lifted` as `*`, and `TYPE Unlifted` as `#` instead? They're type synonyms in GHC 8.0 now, so I don't think it would be too much trouble to change, and it would certainly be less confusing for beginners.

**Comment by bgamari** [comment]
I agree, there is no reason to expose users to the details of levity unprompted.

**Comment by RyanGlScott** [comment]
Opened #476.
