### ISSUE TITLE
Type family instances for Rep/Rep1 printed out in full

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#474]
Now that GHC generics has switched over to a [`-XDataKinds`-based encoding](https://phabricator.haskell.org/rGHC700c42b5e0ffd27884e6bdfa9a940e55449cff6f), the type instances for `Rep` and `Rep1` have become _much_ longer than they used to be, and in just about every Haddock page, they take up an insane amount of width. Look at the Haddocks for `base-4.9`'s [`Control.Applicative`](http://downloads.haskell.org/~ghc/master/libraries/html/base/Control-Applicative.html) for some examples.

This might be a regression, since `base-4.8.1.0`'s [`Control.Applicative`](http://hackage.haskell.org/package/base-4.8.1.0/docs/Control-Applicative.html) doesn't appear to print out any `Rep` or `Rep1` instance implementations.

**Comment by bgamari** [comment]
Indeed, I wonder why these instances were currently hidden.

It seems like in general the right-hand-sides of type family instances may be very long; often too long to reasonably print. I'm not sure how best to deal with this. One option would be to hide the RHS by default, perhaps showing it with an expander as we do instance specializations.

**Comment by RyanGlScott** [comment]
Collapsing the definitions by default seems like a nice workaround, since it keeps things at a sane width while still allowing one to view the whole instance if desired. I'll go ahead and assign myself to this task.

**Comment by RyanGlScott** [comment]
This was fixed in #482.
