### ISSUE TITLE
Release version 2.16.2?

### ISSUE THREAD

**Issue by mgsloan** [haskell/haddock#478]
The [changelog](https://github.com/haskell/haddock/blob/master/CHANGES) makes it seem like there's a released haddock version which supports hyperlinked sources.  [This is something people really want](https://twitter.com/raichoo/status/690276637380907008).  However, no such release exists in git tags or hackage.

**Comment by bgamari** [comment]
I believe the changelog entries are only there to ensure that these items aren't lost track of if a release was to happen. I'm afraid I that I don't have time to make such a release myself, nor am I really the maintainer.

@Fuuzetsu, perhaps you could cut a release?

**Comment by mgsloan** [comment]
Gotcha!  That's what I'd have figured, but there are two unreleased versions - 2.16.2 and 2.17.0

**Comment by bgamari** [comment]
Michael Sloan <notifications@github.com> writes:

> Gotcha!  That's what I'd have figured, but there are two unreleased versions - 2.16.2 and 2.17.0
>
Correct, 2.17.0 will be released alongside GHC 8.0.1.
