### ISSUE TITLE
Haddock mixes Type variables and Kind Variables

### ISSUE THREAD

**Issue by KevinCathcart** [haskell/haddock#491]
In a variety of places, Haddock seems to be showing that kind variables as though they were type variables, resulting in some very misleading signatures.

Take a look at the signature for the `(~~)` class as seen in the doucmentation for `Data.Type.Equality` in [current ghc master](http://downloads.haskell.org/~ghc/master/libraries/html/base/Data-Type-Equality.html#t:-126--126-): 

```
class (~#) j k a b => (j ~~ k) a b 
```

That is severely messed up, and there is no way to view things where that is even approximately correct. The correct signature would be:

```
class (~#) a b => (a :: j) ~~ (b :: k)
```

Technically that is still not a valid signature because (~#) is technically not a constraint, but it really is what we want to display, because it captures the correct idea, per `Note [The equality types story]` of [TysPrim.hs](https://ghc.haskell.org/trac/ghc/browser/ghc/compiler/prelude/TysPrim.hs).

We also see kinds and kind variables posing as type variables in instance signatures. See for example all the instances for [Data.Functor.Sum](http://downloads.haskell.org/~ghc/master/libraries/html/base/Data-Functor-Sum.html). Every single one of them shows either a kind of `*` or a kind variable as though they are some type parameter. I'm not experienced enough working with PolyKinds to have any idea which type parameter(s) the kind or kind variable actually applies to  (without checking in GHCi). Somebody who has never read anything about PolyKinds is likely to be even more confused.

I'd suggest that kind parameters not be shown by default for a kind of `*`.  GHCi itself when using `:browse` or `:info` defaults to showing kind variables in type signatures (with an exception around RuntimeRep), but never shows the application of the Kind value \* to a kind variable in instance signatures (It's unclear to me how it handles application of other specific kind values). Where we do show kind variables it should be using the kind signature notation.  

I understand that with GHC 8.0 technically kind and types are the same thing, and thus a kind variable is a type variable, but there is still a distinction made. Type variables in a type constructor correspond to Binders in the Kind signature. The ones with a named binder with `Invisible` or `Qualified` are do not show up as parameters in the type constructor, and are therefore equivalent to kind variables in the above discussion. Those that have an Anonymous binder, or a Namerd Binder with `Visible` do appear as type parameters, and should be shown like any other type parameter. 

See the `Note [TyBinders and VisibilityFlags]` in [TyCoRep.hs](https://github.com/ghc/ghc/blob/master/compiler/types/) for more information about this.

**Comment by gbaz** [comment]
resolved by above merge
