### ISSUE TITLE
Collapsed sections are not stored properly in cookie

### ISSUE THREAD

**Issue by anka-213** [haskell/haddock#492]
The javascript for collapsing and opening a section stores a cookie for remembering which sections was collapsed, so it can close those again the next time the page is loaded, which it does by toggling it's "collapsed" state. The problem is that some sections are collapsed by default, so when it tries to collapse it, it will instead be opened.

You can see this by opening the synopsis, closing it and then reloading the page. The synopsis will be open again.

**Comment by mpickering** [comment]
I can reproduce this, I will look at your patch now.
