### ISSUE TITLE
support inter-*package*  --hyperlinked-source links, currently only work for *intra* package references, 

### ISSUE THREAD

**Issue by cartazio** [haskell/haddock#496]
i'm not sure if this is a bug report or a feature request, but it looks like haddock's --hyperlinked-source source files currenlty only support intrapackage references?

cc @hvr @thoughtpolice @mpickering  @bgamari, thoughts?

**Comment by cartazio** [comment]
derp, meant to say *inter-package*

**Comment by harpocrates** [comment]
Fixed in 1b26460fb3b5df5215cc1e6715661cbc7c950085.
