### ISSUE TITLE
malformed inter package links from ghc package to boot libs in --hyperlinked-source

### ISSUE THREAD

**Issue by cartazio** [haskell/haddock#497]
the one case where the `--hyperlinked-source` seems to _try_ to provide interpackage links to boot libraries, but the urls have some parameter mangling eg `file:///Users/carter/.install-ghc/ghc-8.0.0-RC4-04-21/share/doc/ghc-8.0.0.20160421/html/libraries/ghc-8.0.0.20160421/base-4.9.0.0/src/%%7BMODULE/-%7D.html#%{NAME}/GHC.Exts.html` was the link to `GHC-Exts` from 
`file:///Users/carter/.install-ghc/ghc-8.0.0-RC4-04-21/share/doc/ghc-8.0.0.20160421/html/libraries/ghc-8.0.0.20160421/src/FastFunctions.html#inlinePerformIO`

**Comment by cartazio** [comment]
the key bit i'd like to highlight is the mangled `/%%7BMODULE/-%7D.html#%{NAME}/ compoentent`

**Comment by gbaz** [comment]
@cartazio did this get fixed?

**Comment by alexbiehl** [comment]
Not yet, but I have that on my agenda.

**Comment by harpocrates** [comment]
Fixed in 1b26460fb3b5df5215cc1e6715661cbc7c950085.
