### ISSUE TITLE
Version 2.17.2 depends on 'haddock-test' which does not exist on Hackage

### ISSUE THREAD

**Issue by peti** [haskell/haddock#511]
Therefore, it's impossible to execute the test suite for us in NixOS.

**Comment by bgamari** [comment]
Peter Simons <notifications@github.com> writes:

> Therefore, it's impossible to execute the test suite for us in NixOS.
>
Hmm, alright. I guess we'll need to start versioning this dependency
more accurately and pushing it to Hackage.

**Comment by Helkafen** [comment]
Fixed by #522. Let me know if it works for you.
