### ISSUE TITLE
Push out a new 2.17 release

### ISSUE THREAD

**Issue by bgamari** [haskell/haddock#518]
Another 2.17 release would be nice. This would fix,
- #505 
- #517 
- Hopefully #497
- #515 
- #280
- #492 
- #486

**Comment by massysett** [comment]
Agreed, due to #505 my haddocks aren't building, which is keeping me off GHC 8.0.

**Comment by bgamari** [comment]
@Helkafen, would you be able to make this happen?

**Comment by Fuuzetsu** [comment]
I can cut the release if @Helkafen can't though I'm not current with what's happening in the code these days and probably can't do the changes justice.
