### ISSUE TITLE
Support for Tex-style math mode

### ISSUE THREAD

**Issue by crockeea** [haskell/haddock#523]
I'll preface by saying I know nothing about character encoding.

I have a package that uses a lot of mathematical symbols in the documentation (greek letters, super- and subscripts, \in, \hat{}, \mathbb{Z}, and a handful of other common tex symbols). I can either fake this in documentation by writing out symbols (e.g., `omega`), but this isn't very pretty.
I can also get on the internet and look up unicode symbols (e.g., `&#x3C9;`), but this is extremely tedious, and moreover the source code comments are completely unreadable.

Would it be possible to add support for "common" Tex syntax, so that I could instead write, e.g., `@\omega@` which would render as &#x3C9;?

**Comment by hvr** [comment]
I'm not sure I see the benefit here, we have already have mathjax support since cabal-1.24 (see #463), or you can  write Unicode directly.

**Comment by crockeea** [comment]
Is that documented anywhere?
