### ISSUE TITLE
Document support for mathjax

### ISSUE THREAD

**Issue by crockeea** [haskell/haddock#524]
HEAD has no documentation for mathjax support. Haddock needs documentation for the command line option as well as for the markup syntax.

**Comment by idontgetoutmuch** [comment]
I added some documentation in a PR. If you type `haddock --help` you will see the `--mathjax=URL` option.

**Comment by crockeea** [comment]
I'm a bit confused about what exactly the requirements are. If I use haddock directly, I need to pass the mathjax url. But cabal (1.24) makes mathjax docs without any additional options. Do I even need the library installed on my system if I build the docs with cabal?

**Comment by hvr** [comment]
I assume the PR @idontgetoutmuch mentions is #525

**Comment by idontgetoutmuch** [comment]
By default, haddock will use the version of mathjax available via http but if you are working offline then this won't work. The url is there so you can use a local version of mathjax. I have a local version of mathjax; I hardly ever use it but if you want to work e.g. on a plane then it can be convenient. HTH.

**Comment by Helkafen** [comment]
#525 is merged.
