### ISSUE TITLE
Broken link in examples section and old tracker link on the haskell.org/haddock page

### ISSUE THREAD

**Issue by cotrone** [haskell/haddock#543]
On https://www.haskell.org/haddock, the link to "The latest version of the documentation is here" in the examples section points to a dead link.

I think the old link to trac is also out of date and should point here.

I could do both of those if someone can point me in the correct direction! I'm not sure where the latest version of the documentation should point.

**Comment by asr** [comment]
+1

**Comment by gbaz** [comment]
The homepage also points to an old bitrotted mailinglist, doesn't point to recent releases, etc.

**Comment by gbaz** [comment]
I can login and make cosmetic changes myself, but I don't want to take over as full-time maintainer of the page. If @cotrone or someone wants to volunteer I'll hook up the permissions?

**Comment by gbaz** [comment]
cf https://github.com/haskell/haddock/issues/360

**Comment by gbaz** [comment]
ok, those two issues are fixed. thanks for the report!
