### ISSUE TITLE
Haddock renders runtime rep arguments of unboxed tuples

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#544]
An example can be seen [here](http://docs.futurice.com/haskell-mega-repo/primitive-0.6.1.0/Control-Monad-Primitive.html) if you expand the information for the `PrimMonad IO` instance:

![runtime-reps](https://cloud.githubusercontent.com/assets/2364661/17218332/6116fea6-54b5-11e6-9b55-19ea1f6b2aac.png)

Notice the superfluous `VoidRep` and `PtrRepLifted` arguments.

We probably need to call [`dropRuntimeRepArgs`](http://git.haskell.org/ghc.git/blob/e98edbd1b8947dcb4a47d20fc854c0a9a6954bea:/compiler/types/TyCoRep.hs#l753) somewhere, but I'm not sure where...

**Comment by alexbiehl** [comment]
I noticed this in a different place: Applicative instance for `(->) a`
![bildschirmfoto 2017-07-03 um 07 12 26](https://user-images.githubusercontent.com/1876617/27778884-000d6e9a-5fbf-11e7-88c8-7f4de2fbea11.png)

The relevant code is in https://github.com/haskell/haddock/blob/master/haddock-api/src/Haddock/Interface/Specialize.hs (namely `specializeSig`. But there we `HsType`s not `Type`. 

It's `hsq_explicit` from GHC which claims to return only the explicit written tyvars but instead includes runtime representations for functions and unboxed tuples.

**Comment by RyanGlScott** [comment]
This should be fixed after #681.
