### ISSUE TITLE
Running haddock with "--hyperlinked-source" just creates / pollutes src directory

### ISSUE THREAD

**Issue by mgsloan** [haskell/haddock#545]
See https://github.com/commercialhaskell/stack/issues/2429 .  The issue is that stack has been using `haddock --hyperlinked-source` to detect if haddock supports hyperlinked source.  When `haddock --hyperlinked-source` runs, nothing happens but `style.css` and `highlight.js` get put into a `src` dir.

**Comment by Deewiant** [comment]
Dupe of #536

**Comment by mgsloan** [comment]
Ah, I should have searched!
