### ISSUE TITLE
Haddock always shows kind signatures for types re-exported from other packages

### ISSUE THREAD

**Issue by gridaphobe** [haskell/haddock#548]
If I run haddock on the following modules

``` haskell
module Foo where

data Foo = MkFoo
```

``` haskell
module Bar (Bar(..), Foo(..)) where

import Foo

data Bar = MkBar
```

the types are formatted as expected, **without** kind-signatures.

However, if I move `Foo` into a separate package it suddenly has a kind-signature in the `Bar` haddocks.

It would be nice if haddock would only display kind signatures when one of the type parameters has a non-`*` kind, otherwise it's just noise IMO.

**Comment by ezyang** [comment]
The reason for this problem is probably because Haddock is reverse engineering the source declaration from the recorded type in the GHC interface file, and then forgetting to suppress kinds (when you have it directly, it just uses the renamed source directly.)

**Comment by jkoppel** [comment]
Hi! I seem to be running into this issue, resurrected.

I'm currently updating documentation for a fork of the `compdata` package ( https://hackage.haskell.org/package/compdata-0.12 ), which has some complicated type signatures.

Here's a core function in the original package:

<img width="872" alt="Screen Shot 2020-08-20 at 4 30 22 AM" src="https://user-images.githubusercontent.com/1279592/90764850-de90dd00-e29d-11ea-97c1-cbaae2ec7678.png">

And here it is re-exported in the "essentials" package:

<img width="1098" alt="Screen Shot 2020-08-20 at 4 30 46 AM" src="https://user-images.githubusercontent.com/1279592/90764880-ec466280-e29d-11ea-9e45-5458df2d0261.png">


Yuck!
