### ISSUE TITLE
Feature request: when re-exporting from another package, @since should be rendered differently

### ISSUE THREAD

**Issue by edsko** [haskell/haddock#550]
Motivating example: if you look at the documentation of [http-conduit-2.2.0.1](http://hackage.haskell.org/package/http-conduit-2.2.0.1/docs/Network-HTTP-Conduit.html#t:HttpException), it seems it defines a type `HttpException` which, apparently, is available since version 0.5. However, in actuality `http-conduit` just re-exports the definition from `http-client`, and that version number (0.5) refers to `http-client`, not `http-conduit`; but this is completely invisible to the user, who would therefore reach the wrong conclusion that `HttpException` has been available in `http-conduit` since version 0.5.

**Comment by hvr** [comment]
related: #452

**Comment by alexbiehl** [comment]
Closing. #749 addresses this issue.
