### ISSUE TITLE
Bundled pattern synonyms in GHC 8 are not documented

### ISSUE THREAD

**Issue by treeowl** [haskell/haddock#551]
Pattern synonyms exported using the new GHC 8 syntax (bundled with type like constructors) are not documented. As far as I can tell, the only way to document them is to add redundant `pattern` exports.

**Comment by mpickering** [comment]
See #494 for a partial fix.

**Comment by treeowl** [comment]
That sounds partial... I want to be sure to get hand-written documentatIon
included. Does your fix do that?

**Comment by mpickering** [comment]
It is a patch contributed by @christiaanb

**Comment by christiaanb** [comment]
@treeowl It's not really partial... it's just that it always prints pattern synonyms using GADT syntax.

So let's say you have something silly as:

```haskell 
data Either a b = Left a | Right b

pattern Both :: a -> b -> Either a b
```

Then the haddock would be printed as:

`data Either a b`

__Constructors__
__`Left`__ `a`
__`Right`__ `b`
__`Both`__ `:: forall a b . a -> b -> Either a b`

Something more desirable would probably be:

`data Either a b`

__Constructors__
__`Left`__ `a`
__`Right`__ `b`

__Associated patterns__
__`Both`__ `:: forall a b . a -> b -> Either a b`

**Comment by treeowl** [comment]
Yes, that would definitely be more desirable! If you can do it, though, I
suggest you use the word "bundled". I think pattern synonyms are
"associated" with classes.

**Comment by christiaanb** [comment]
Oops, yes, I meant bundled. I'm always mixing those up.

**Comment by christiaanb** [comment]
I wrote the earlier mentioned patch as a "better-something-than-nothing"-patch just before the 8.0.1 release (I think). I hope I can get the suggested patch in before the 8.0.2 release.

**Comment by treeowl** [comment]
For sure.

**Comment by mpickering** [comment]
I think there is definitely an argument to not distinguish between pattern synonyms and constructors. They are meant to be a means for abstraction after all.

**Comment by treeowl** [comment]
Users concerned about portability and backwards compatibility care. I'm not
usually so worried about such, but my users are.

**Comment by alexbiehl** [comment]
We now have https://github.com/haskell/haddock/commit/87c551fc668b9251f2647cce8772f205e1cee154. Please feel free to reopen if you think your concerns haven't been addressed.
