### ISSUE TITLE
Methods of re-exported type-class from another package are not shown

### ISSUE THREAD

**Issue by k-bx** [haskell/haddock#552]
When a package re-exports another package's class, its methods are not listed under documentation. I first discovered this in `ClassyPrelude` [haddocs for IOData](https://www.stackage.org/haddock/lts-7.0/classy-prelude-1.0.0.2/ClassyPrelude.html#t:IOData), which did not list the methods.

I reproduced this by creating a small repo https://github.com/k-bx/haddock-reexport-bug . Just build it with `stack build` and build haddocs with `stack haddock`. If you open the result, you'll see that while classmethod [renders class with the method listed](https://i.imgur.com/0XMNZAn.png), the `UserModule` [does not render the method](https://i.imgur.com/kZWdpaN.png).

Thank you!

**Comment by niteria** [comment]
I believe this is the same as https://ghc.haskell.org/trac/ghc/ticket/12519
and #549.
It would help if you provided the version of haddock and ghc.
Thank you for a small repro!

**Comment by k-bx** [comment]
Haddock 2.17.3, ghc 8.0. Thanks for pointing to those, closing then.
