### ISSUE TITLE
haddock-api on hackage doesn't allow `ghc-8.0.2`

### ISSUE THREAD

**Issue by kolmodin** [haskell/haddock#571]
`haddock-api` in the repo allows `ghc-8.0.2` but  revision 1 on hackage restricted to `ghc < 8.0.2`.

https://hackage.haskell.org/package/haddock-api-2.17.3/revisions/

**Comment by hvr** [comment]
@kolmodin that's deliberate, @bergmark had to set that bound because GHC 8.0.2 moved around `NFData` instances... what's needed is a new release of `haddock-api` compatible with GHC 8.0.2

**Comment by basvandijk** [comment]
Could we please get a new release on Hackage that supports GHC-8.0.2?

The only patch that is needed based on `haddock-2.17.3-release` is the following: https://github.com/basvandijk/haddock/commit/f4c5e46ded05a4b8884f5ad6f3102f79ff3bb127

**Comment by kolmodin** [comment]
@hvr I have no doubt that it was deliberate :) I was trying to say what @basvandijk said.

**Comment by basvandijk** [comment]
Note that `nixpkgs` already [uses](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L490) that patch.

**Comment by hvr** [comment]
I'm going to upload an out-of-band patched (w/ the patch mentioned above) `haddock-api-2.17.3.1` later today

**Comment by hvr** [comment]
It's done. I've uploaded http://hackage.haskell.org/package/haddock-api-2.17.3.1
