### ISSUE TITLE
Incorrect link to source on instance declaration

### ISSUE THREAD

**Issue by chrissound** [haskell/haddock#572]
Not too sure if this is a bug on hackage / haddock, or even if it is actually a bug.

On this page https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Monoid.html  when I click on the 'source' link for the instance declaration of `(Ord a, Bounded a) => Monoid (Max a)` it redirects to https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Base.html#line-370
![2017-01-16-16 07 20](https://cloud.githubusercontent.com/assets/1499652/21990225/e819f2b4-dc05-11e6-8aa7-ce8e5c6d2746.png) which doesn't seem to be the correct location.

**Comment by harpocrates** [comment]
This seems like a straightforward confusion: the link should be to [line-370 of `Data.Semigroup`](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/Data.Semigroup.html#line-370), not `GHC.Base`. Looks like the `GHC.Base` is being picked up from the fact that `Monoid` itself is defined in `GHC.Base`.

**Comment by harpocrates** [comment]
Here is a simpler test case:

```haskell
-- ClassOnly.hs
module ClassOnly where

class Class a
```

```haskell
-- InstanceOnly.hs
module InstanceOnly where

import ClassOnly

data Qux = Qux
instance Class Qux
```

Then the source link on the `Qux` instance of `Class` (under the instance list in `ClassOnly.html`) links to a line in `ClassOnly.html`, not `InstanceOnly.html` as it should.
