### ISSUE TITLE
haddock fails with secret-sharing

### ISSUE THREAD

**Issue by LocutusOfBorg** [haskell/haddock#574]
as said on #233 

The latest version of haddock (version 2.17.3) fails when generating docs for secret-sharing-1.0.0.3 with:

haddock: internal error: renameType: HsSpliceTy
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Rename.hs:266:30 in main:Haddock.Interface.Rename

Haddock version 2.17.2 works fine.

G.

**Comment by gbaz** [comment]
still occurs with 2.18.1 :-/
