### ISSUE TITLE
haddock-api does not export `MDoc`

### ISSUE THREAD

**Issue by JustusAdam** [haskell/haddock#580]
The module `Documentation.Haddock` in the `haddock-api` package does not export the type alias `MDoc`, however this type is necessary to process the `Interface`  file generated by haddock.

I want to implement a JSON output for haddock documentations, but because `MDoc` is not exported I cannot convert the documentation from the `Interface`.

It seems to me this is not intentional and you just forgot to export `MDoc` but I am not sure. Should this have been a conscientious decision I would like to hear the rational for doing it, otherwise it would be nice if you could fix this.

**Comment by alexbiehl** [comment]
Resolved in #581. Closing.
