### ISSUE TITLE
failed cabal install on windows

### ISSUE THREAD

**Issue by rakesh-k** [haskell/haddock#583]
Need to install this as part of hsdev requirement for SublimeText3 on Windows. But I am getting following error:

```
Reading available packages...
Failed to query pkg-config, Cabal will continue without solving for pkg-config
constraints: user error (The program 'pkg-config' is required but it could not
be found.)
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: haddock-api-2.17.3 (dependency of haddock-2.17.3:-in-ghc-tree)
next goal: ghc (dependency of haddock-api-2.17.3)
rejecting: ghc-8.0.2/installed-8.0... (conflict: haddock-api => ghc>=8.0 &&
<8.0.2)
Dependency tree exhaustively searched.
```

I am using Haskell Platform ghc-8.0.2.
Any help is appreciated.

**Comment by RyanGlScott** [comment]
This should be fixed now that [`haddock-api-2.17.3.1`](http://hackage.haskell.org/package/haddock-api-2.17.3.1) has been uploaded, which supports GHC 8.0.2 (see also #571).

**Comment by Anshuman-Verma** [comment]
Appreciate @RyanGlScott for the upload, it works fine now.
@rakesh-k try to install the new version and it should be working fine.

**Comment by alexbiehl** [comment]
I think this is resolved then. Closing this issue. Please feel free to reopen if the issue persists.

**Comment by rakesh-k** [comment]
Thanks everyone for the fix!
