### ISSUE TITLE
Preparing the next release

### ISSUE THREAD

**Issue by wereHamster** [haskell/haddock#587]
There are currently a few issues open related to the latest haddock-api being incompatible with GHC 8.0.2. Can we cut a next release? Either 2.17.4 or 2.17.3.1 (probably the later if all it contains is the one compatibility change). I can prepare the code (cherry-pick the commit, update cabal file etc). But somebody with upload access to hackage would have to complete the release. Is anybody feeling responsible?

**Comment by bgamari** [comment]
Tomas Carnecky <notifications@github.com> writes:

> There are currently a few issues open related to the latest
> haddock-api being incompatible with GHC 8.0.2. Can we cut a next
> release? Either 2.17.4 or 2.17.3.1 (probably the later if all it
> contains is the one compatibility change). I can prepare the code
> (cherry-pick the commit, update cabal file etc). But somebody with
> upload access to hackage would have to complete the release. Is
> anybody feeling responsible?
>
@Helkafen is currently the maintainer of record but we haven't heard
much from him recently. I can certainly upload the release if necessary.

**Comment by JonCoens** [comment]
I'm waiting on haddock-api working with 8.0.2 for an upgrade and would appreciate a new release.

**Comment by RyanGlScott** [comment]
This has been fixed with the upload of [`haddock-api-2.17.3.1`](http://hackage.haskell.org/package/haddock-api-2.17.3.1) (see also #571).
