### ISSUE TITLE
Hidden constructors are exposed when using module reexports

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/haddock#591]
Here are the generated docs:
![image](https://cloud.githubusercontent.com/assets/1560937/24044650/3e94d996-0b2d-11e7-9844-79fdf5737569.png)

Here's the code for that module. You can see that the constructors are hidden.
![image](https://cloud.githubusercontent.com/assets/1560937/24044698/7e0a78ce-0b2d-11e7-83f2-ca42bc750d78.png)

A GHCI session proves that they are in fact hidden:

![image](https://cloud.githubusercontent.com/assets/1560937/24044690/6a3f54a4-0b2d-11e7-8450-530dee759ffb.png)

The associated code is here:
https://github.com/sannsyn/solr/tree/c49701f422c1ed21689757917548964ac312d4e8

**Comment by alexbiehl** [comment]
I bet this is another short coming of haddocks export logic. See https://github.com/haskell/haddock/issues/584 for another example. @ezyang proposed a solution in https://github.com/haskell/haddock/issues/586 but it got stuck in some detail about documentation on exports I think. I intend to take a look at some point.

**Comment by ezyang** [comment]
I think what may be the right thing to do is to extend the renamed IE syntax to also record "expansions" for `T(..)` and `module Foo` style exports, so that Haddock can directly read off what is brought into scope, rather than try to recompute it (poorly).

**Comment by gbaz** [comment]
should be resolved by #688
