### ISSUE TITLE
Build fails in linux, ghc versioning

### ISSUE THREAD

**Issue by ShrykeWindgrace** [haskell/haddock#596]
I clone the master branch of haddock with `git clone https://github.com/haskell/haddock.git`, then try to build it using stack (`stack init`), then produced output is 

> 
> Looking for .cabal or package.yaml files to use to init the project.
> Using cabal packages:
> - haddock.cabal
> - haddock-test/haddock-test.cabal
> - haddock-api/haddock-api.cabal
> - haddock-library/haddock-library.cabal
> 
> Selecting the best among 10 snapshots...
> 
> Downloaded lts-8.6 build plan.    
> * Rejected lts-8.6
>     ghc-8.0.2 cannot be used for these packages:
>         - haddock-api
>     ghc version 8.0.2 found
>         - haddock-api requires ==8.2.*
> 
> Downloaded nightly-2017-03-29 build plan.    
> * Rejected nightly-2017-03-29
>     ghc-8.0.2 cannot be used for these packages:
>         - haddock-api
>     ghc version 8.0.2 found
>         - haddock-api requires ==8.2.*
> 
> --SNIP--
> 
> None of the following snapshots provides a compiler matching your package(s):
>     - lts-8.6
>     - nightly-2017-03-29
>     - lts-7.20
>     - lts-6.30
>     - lts-5.18
>     - lts-4.2
>     - lts-3.22
>     - lts-2.22
>     - lts-1.15
>     - lts-0.7
> 
> This may be resolved by:
>     - Using '--omit-packages to exclude mismatching package(s).
>     - Using '--resolver' to specify a matching snapshot/resolver

It seems that there is typo in the requirement `ghc == 8.2.*` in *.cabal files, since the latest release of ghc is only 8.0.2 =)

config: Ubuntu 16.04, ghc 8.0.2, stack 1.3.2

**Comment by hvr** [comment]
Please note that the `master` branch is in fact for use with the soon to be released GHC 8.2.1; so `ghc == 8.2.*` is not a typo :-)

**Comment by ShrykeWindgrace** [comment]
Thank you for clarification. In this case an update of the readme file would be quite welcome, because in the current state the installation instructions are misleading - the 8.2.* is yet to be released (and "mid-april" is at least two weeks away). A gentle reminder "use this branch for that version of ghci" would be enough.

**Comment by harpocrates** [comment]
We got rid of `master`. Now, branches are named after the compiler version with which they are expected to compile, so this should not be a problem again. Additionally, the README's of each branch should mention the right GHC versions.
