### ISSUE TITLE
Render module-reexported declarations in the re-exporting module

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/haddock#597]
```module Child (f, g) where …```

```
module Parent (module Child, h) where

import Child (g)
```

currently we will get documentation for `h` and a link to `Child` in `Parent`. We should allow an option that will render `g` and `h` instead. I think we have all the information and we can keep the old behaviour with module-specific flag.

**Comment by ntc2** [comment]
The docs say that it already works this way, but then in a foot note it says it's not actually implemented: https://www.haskell.org/haddock/doc/html/ch03s04.html#idm140354810861024 (I can't find docs for a more recent Haddock online).

**Comment by ntc2** [comment]
Also, I think this issue is a duplicate of #584. The other issue has more details, so I'd close this one.

**Comment by gbaz** [comment]
should be resolved by #688
