### ISSUE TITLE
Synopsis section not present in the haddocks being generated

### ISSUE THREAD

**Issue by psibi** [haskell/haddock#599]
Not sure if this is the right repository or the hackage-server repository would be better suited for this.

Recent version of Hackage, is not showing synopsis section at all in the generated docs.

Example:

Synopsis is present here: https://hackage.haskell.org/package/persistent-2.2.4/docs/Database-Persist.html

But in the latest one it's absent: https://hackage.haskell.org/package/persistent-2.6.1/docs/Database-Persist.html

In fact it has been absent for quite some months now.

**Comment by Fuuzetsu** [comment]
Pretty sure it was switched off on Hackage for some reason (though not 100%)

**Comment by psibi** [comment]
@Fuuzetsu Any related thread / link for the reasoning behind it ?

**Comment by Fuuzetsu** [comment]
Not that I can recall off the top of my head. I might be completely wrong, just saying it's worth asking someone from Hackage.

**Comment by hvr** [comment]
I investigated a bit, and it turns out that this appears to be an **unintended** side-effect of 474a0c182d6ef9a7e93e277a2755d04d943059a0

**Comment by alexbiehl** [comment]
Thanks @hvr. I'm on it.

**Comment by alexbiehl** [comment]
With https://github.com/haskell/haddock/commit/4346ad26ac1346aa5e59991315f6969c844bea60 there is now a proper fix in master.

**Comment by psibi** [comment]
@alexbiehl Thanks for the fix! Feel free to close the issue.

**Comment by alexbiehl** [comment]
@psibi Please be aware that a fix is already present in the latest released haddock-2.17.4. So you can already use that until we release haddock-2.18.
