### ISSUE TITLE
There should be a --maintainer flag

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#6]
**Original reporter**: _david.waern@<hidden>_

There should be a --maintainer flag to allow Cabal to pass the maintainer from the .cabal file to the generated docs.

**Comment by harpocrates** [comment]
Information about the maintainer is passed in through the module header. I can't think of any good way to resolve conflicting information from a `--maintainer` flag with the module header information. Feel free to re-open if this is still wanted.
