### ISSUE TITLE
rST markup for Haddock

### ISSUE THREAD

**Issue by jml** [haskell/haddock#618]
I would really really like it if I could write Haskell API documentation with reStructuredText (rST). It's great for writing Python documentation, and would allow me to be consistent between my API docs and higher-level docs (I notice that Haddock uses rST for its docs). 

Haddock markup is idiosyncratic, and unlike markup used elsewhere. It's hard to guess, and I always find myself consulting the manual.

I realise this is a big request, and that there are equally valid arguments for Markdown or other markup languages. I'd love to implement it myself, but step 0 is filing a bug here.

**Comment by hvr** [comment]
...it may be useful to review why attempts to add support for Markdown have failed in the past (see https://github.com/haskell/haddock/issues/244#issuecomment-261019664) and whether rST would have a better chance than Markdown.

**Comment by jml** [comment]
I filed this already as #570.  Sorry for the duplication.
