### ISSUE TITLE
Test failure on stackage

### ISSUE THREAD

**Issue by decentral1se** [haskell/haddock#634]
All the tests pass and then I see:

```
> /tmp/stackage-build13/haddock-2.17.5$ dist/build/html-test/html-test
Haddock executable not specified
```

**Comment by alexbiehl** [comment]
Could you disable tests for haddock temporarily? The fix is on master but I won't be able to release until tomorrow.

**Comment by lwm** [comment]
Yep, already did with https://github.com/fpco/stackage/commit/0665f5e6f0101dc3a45f3dfe17b9119e00841aa7 (not sure why it didn't show here). Thanks!

**Comment by lwm** [comment]
@alexbiehl, I'm seeing *a lot* of haddock related errors on Stackage. They all look like https://github.com/fpco/stackage/issues/2563#issue-233918532 (where foo.html is missing). Is this bug related?

**Comment by lwm** [comment]
Any chance of a release today @alexbiehl?
