### ISSUE TITLE
Upcoming change to ModuleGraph

### ISSUE THREAD

**Issue by niteria** [haskell/haddock#635]
Context: I'm optimizing GHCi :reload speed and one of the bottlenecks points to inefficient representation of `ModuleGraph`.

Problem: 
`ModuleGraph` is currently not abstract, it's defined as:
```
type ModuleGraph = [ModSummary]
```
The problem is that there's a place in `haddock` that assumes this representation.

That place is here:
https://github.com/haskell/haddock/blob/master/haddock-api/src/Haddock/Interface.hs#L147

I think the smoothest path forward is to change `map` to `fmap` and keep `ModuleGraph` a `Functor`.

My main question is how to roll out this change, and to be more precise when and where (which branch) to make the changes to Haddock and GHC.

cc @bgamari @simonmar

**Comment by alexbiehl** [comment]
@niteria That sounds reasonable. You can provide a pull request to `ghc-head` branch this is where HEAD points to.

**Comment by niteria** [comment]
Hm, after https://github.com/haskell/haddock/commit/c4a06a877be56d5cd790f8abb7928fa39458e1e4 haddock/ghc-head no longer needs mapMG.

haddock/master still uses map, but IIUC https://github.com/haskell/haddock/commit/c4a06a877be56d5cd790f8abb7928fa39458e1e4 will be merged into haddock/master at some point.
