### ISSUE TITLE
Ambiguous methods for classes in .txt files

### ISSUE THREAD

**Issue by ChShersh** [haskell/haddock#637]
Haddock prints information about exported methods in a way that can't be parsed unambiguously into origin source structure. Consider next two modules:

```haskell
module Example1 (Class1 (..)) where

class Class1 t where
    method1 :: t -> t
    method2 :: t -> t -> t
```

```haskell
module Example2 (Class2 (..), method2) where

class Class2 t where
    method1 :: t -> t

method2 :: Class2 t => t -> t -> t
method2 = undefined
```

When running `stack haddock` command to generate exported symbols database I see next `.txt` file:

```haskell
-- Hoogle documentation, generated by Haddock
-- See Hoogle, http://www.haskell.org/hoogle/


-- | Haddock example
--   
--   Please see README.md
@package haddock-txt-classes-ambiguity
@version 0.1

module Example2
class Class2 t
method1 :: Class2 t => t -> t
method2 :: Class2 t => t -> t -> t

module Example1
class Class1 t
method1 :: Class1 t => t -> t
method2 :: Class1 t => t -> t -> t
```

If instead it would be something like this (similar to records):

```haskell
module Example2
class Class2 t
[method1] :: Class2 t => t -> t
method2 :: Class2 t => t -> t -> t

module Example1
class Class1 t
[method1] :: Class1 t => t -> t
[method2] :: Class1 t => t -> t -> t
```

then this information can be parsed preserving origin structure.

Here is repository with these examples: https://github.com/ChShersh/haddock-txt-classes-ambiguity

`.txt` file can be found after running `stack haddock` at:

`haddock-txt-classes-ambiguity/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/doc/html/haddock-txt-classes-ambiguity/haddock-txt-classes-ambiguity.txt`

I'm interested in making this done via pull request, other proposals are welcome.
If I understand correctly, I should start investigation and diving into code from this function:

https://github.com/haskell/haddock/blob/e41e21e6caccfe18c5a291c8c0f8be143552cc27/haddock-api/src/Haddock/Backends/Hoogle.hs#L45

**Comment by hvr** [comment]
Just as a word of advice: the more you try to use the hoogle txt output as the basis for API analysis, the more shortcomings you'll find which will cause you trouble. Also, take into account that any change you make in the format may break or require changes to `hoogle`. I've actually run into that very issue you pointed out a few years ago. I would have suggested to either mimic Haskell syntax better, i.e. indent the real methods, or to prefix them with the classname, i.e. `Class1.method1 :: ...`.

**Comment by ChShersh** [comment]
@hvr What would you recommend to use instead of analyzing hoogle txt files? Are there any more robust ways to analyze exported symbols by modules by only parsing (without compilation)?

**Comment by hvr** [comment]
@ChShersh I'd keep an eye on #645 ...

**Comment by gbaz** [comment]
Shall we close this?

**Comment by ChShersh** [comment]
@gbaz Feel free to close it! #645 is merged. I didn't have a change to look at it. But still have it my TODO-list.
