### ISSUE TITLE
Haddock commit c4a06a877be56d5cd790f8abb7928fa39458e1e4 or/and GHC commit 53c78be0aab76a3107c4dacbb1d177afacdd37fa is/are buggy

### ISSUE THREAD

**Issue by awson** [haskell/haddock#640]
Current `ghc-head` Haddock fails to produce `language-c-quote-0.12` package documentation barfing something like `unknown symbol languagezmczmquotezm0zi12zmU79M5Ik6y66BQup46vL86_LanguageziCziParserziMonad_emptyPState_closure`.

Reverting ['Don't enable compilation for template haskell'](https://github.com/haskell/haddock/commit/c4a06a877be56d5cd790f8abb7928fa39458e1e4) commit fixes things for me.

Thus either this commit or relevant ghc commit or both is/are buggy. Perhaps, this should be cross-reported to GHC trac.

**Comment by alexbiehl** [comment]
Thanks @awson! @duog is the expert here, what do you say?

**Comment by duog** [comment]
It's more likely to be a ghc problem, trac is probably the place. It is probably replicatable by building with ghc --make -fno-code -fwrite-interface. I will look into this when I get a chance.

**Comment by awson** [comment]
Perhaps, but all the object code (both vanilla and profiled libraries and prelinked object file for ghci) was built by ghc with no problems.

**Comment by awson** [comment]
Well, doing

**Comment by awson** [comment]
Well, doing `ghc ... --make -fno-code -fwrite-interface ...` I'm getting the same error.

But I don't quite understand how should we describe this bug. What exactly is buggy in ghc?

**Comment by alexbiehl** [comment]
IIRC this is the change at fault here:
https://github.com/ghc/ghc/commit/53c78be0aab76a3107c4dacbb1d177afacdd37fa

Ghc doesn't seem to compile your modules as though it should work this
patch.

awson <notifications@github.com> schrieb am Do., 22. Juni 2017, 19:07:

**Comment by duog** [comment]
I made ghc -fno-code smarter: it enables object code generation for modules depended on by modules that use template haskell.

Haddock uses -fno-code, and used to enable object code generation for all modules in a project where template haskell is used at all. The commit you reverted disabled that behavior, because it should be unnecessary when ghc is already generating the necessary object code.

I think what is going wrong is that the quasi-qutoes in language-c-quote should also trigger object code generation.

if you pass -opt-ghc=-asm to haddock, that may work around the issue.

**Comment by duog** [comment]
[trac](https://ghc.haskell.org/trac/ghc/ticket/13863#ticket)

**Comment by awson** [comment]
Thanks.
Btw, this is exactly what I suspected too – template-haskell and quasi-quoting having different relevant code paths.

**Comment by alexbiehl** [comment]
@awson @duog is on fixing this in https://phabricator.haskell.org/D3677

**Comment by alexbiehl** [comment]
Alright, https://github.com/ghc/ghc/commit/d55bea14c745f7f448fb24673a21b511d1c1c222 has all the magic to make it work again. Closing this for now. Feel free to reopen if you think your converns haven't been addressed.
