### ISSUE TITLE
Haddock drops fixity declarations for re-exported class methods

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#641]
Here's two modules:

```haskell
module Foo (C(..)) where

infixl 9 `a`

class C x where
  a :: x
```
```haskell
module Bar (a) where

import Foo
```

To reproduce this issue, run `haddock Bar.hs --html -o foobar`, and open up `foobar/Foo.html` and `foobar/Bar.html`. You'll notice that `Foo.html` looks fine:

<img width="369" alt="screen shot 2017-06-22 at 4 18 29 pm" src="https://user-images.githubusercontent.com/2364661/27460058-79b2f1b8-5766-11e7-9846-9e9021203bf7.png">

But `Bar.html` does not: it doesn't report the fixity of `a`!

<img width="478" alt="screen shot 2017-06-22 at 4 17 48 pm" src="https://user-images.githubusercontent.com/2364661/27460065-7f52a564-5766-11e7-9e82-7215e94cf34b.png">

Moreover, this only happens when you re-export `a` by itself. If you bundle `a` with `C` when re-exporting it:

```haskell
module Bar (C(..)) where

import Foo
```

Then this issue does not occur:

<img width="352" alt="screen shot 2017-06-22 at 4 20 08 pm" src="https://user-images.githubusercontent.com/2364661/27460109-afe90cd6-5766-11e7-8275-f42c4be27085.png">

This is the version of `haddock` I'm using:

```
Haddock version 2.18.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
```

Although the issue also occurs with earlier `haddock`s as well.

**Comment by RyanGlScott** [comment]
A place where this occurs in the wild is `base`, since the reexported Haddocks for [`elem`](http://hackage.haskell.org/package/base-4.9.1.0/docs/Data-List.html#v:elem) in `Data.List` do not show its fixity declaration from `Data.Foldable` (but there is a fixity declaration for `notElem`, since it's a top-level function, not a class method of `Foldable`).

**Comment by alexbiehl** [comment]
Thanks @RyanGlScott. I will have a look, I have done something similar for bundled pattern synonyms recently.
