### ISSUE TITLE
Regression: per-argument docs in type class methods are not rendered anymore

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haddock#647]
See: https://stackoverflow.com/questions/44820920/is-there-a-way-to-make-haddock-render-per-argument-docs-for-type-class-methods

2.16.1, works: https://hackage.haskell.org/package/megaparsec-5.0.0/docs/Text-Megaparsec-Prim.html (see the `failure` method of `MonadParsec`).

2.17.3, does not work: https://hackage.haskell.org/package/megaparsec-5.3.1/docs/Text-Megaparsec-Prim.html#v:failure

The docs have been there for all time.

That's quite unfortunate, people got confused without the docs.

**Comment by alexbiehl** [comment]
@mrkkrp Please take a look at https://github.com/haskell/haddock/pull/648. I am certain it fixes the issues.

**Comment by mrkkrp** [comment]
Thanks for the quick response! When release of the version 2.18 is planned?

**Comment by alexbiehl** [comment]
Haddock 2.18 comes along with ghc-8.2. Theoretically I could release a 2.17.6 but I am not sure it will reach many people, given that hackage for example is still on 2.17.3. What do you think?

**Comment by mrkkrp** [comment]
I guess I'm OK with waiting for 2.18. Megaparsec 6 will be in development for some time anyway, so hopefully GHC 8.2 will be released before it.

**Comment by alexbiehl** [comment]
Alright! Thanks for reporting the issue by the way.

Mark Karpov <notifications@github.com> schrieb am Do., 29. Juni 2017 um
19:36 Uhr:
