### ISSUE TITLE
Re-exporting a constructor as a pattern synomym causes internal error "extractRecSel: selector not found"

### ISSUE THREAD

**Issue by leftaroundabout** [haskell/haddock#653]
https://github.com/leftaroundabout/dumb-cas/tree/2ca60634fd2a6aec00d3beae50c4f5d5104354d8/CAS
```haskell
{-# LANGUAGE PatternSynonyms #-}
module CAS.Dumb (pattern (:=:)) where
import CAS.Dumb.Tree
```
```haskell
module CAS.Dumb.Tree where

data CAS' γ s² s¹ s⁰ = Symbol !s⁰

infixr 4 :=:
data Equality' γ s² s¹ s⁰
  = (:=:) { originalExpression :: !(CAS' γ s² s¹ s⁰)
          , transformedExpression :: !(CAS' γ s² s¹ s⁰) }
```
This re-export of the `:=:` constructor causes the following Haddock error:
```
$ cabal haddock --hyperlink-source
Running hscolour for dumb-cas-0.1.0.0...
Preprocessing library for dumb-cas-0.1.0.0..
Preprocessing library for dumb-cas-0.1.0.0..
Running Haddock on library for dumb-cas-0.1.0.0..
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: base-4.10.0.0, ghc-prim-0.5.0.0,
integer-gmp-1.0.0.1
Haddock coverage:
   0% (  0 /  3) in 'CAS.Dumb.Tree'
  Missing documentation for:
    Module header
    CAS' (CAS/Dumb/Tree.hs:4)
    Equality' (CAS/Dumb/Tree.hs:7)
haddock: internal error: extractRecSel: selector not found
CallStack (from HasCallStack):
  error, called at src/Haddock/Interface/Create.hs:918:26 in haddock-api-2.17.3-7MCkWQdoFOzHq7JdxAPWNq:Haddock.Interface.Create
```
The behaviour is the same with Haddock-2.16.1 on GHC-7.10, and with Haddock-2.17.3 on GHC-8.3.20170711.

Obviously, the problem can easily be avoided by exporting the constructor in the usual way instead (i.e. `module CAS.Dumb (Equality ((:=:)))`, but if Haddock has problems with the `pattern` syntax (which GHC itself accepts, though I'm not sure how well-specified this is) it would be nice to at least give a clearer error message.

**Comment by alexbiehl** [comment]
Thanks for the report @leftaroundabout! Could you also try with current haddock master on ghc-8.2?

**Comment by leftaroundabout** [comment]
I could... but since the problem is the same with GHC-7.10 and GHC-HEAD, I would be surprised if it were any different in GHC-8.2. Do you have reason to believe so?

**Comment by alexbiehl** [comment]
Well, master branch has all the new features (Special Support for bundled
Pattern synonyme) and Bug fixes while ghc-head just tracks compatibility
changes for GHC HEAD. Though merging is on my backlog. But I say it's worth
trying.

Justus Sagemüller <notifications@github.com> schrieb am Mi., 12. Juli 2017,
17:12:

**Comment by alexbiehl** [comment]
Oh, looking at your code I think it is actually incorrect. GHC shouldn't accept the `pattern` export for a data constructor like `(:=:)`.
