### ISSUE TITLE
haddock-api: haddock does not support +RTS flags in --optghc options

### ISSUE THREAD

**Issue by trofi** [haskell/haddock#666]
Example failure:
```
$ haddock Main.hs --optghc="+RTS" --optghc=-A512M --optghc=-RTS
haddock: Couldn't parse GHC options: +RTS -A512M -RTS
```

The situation arises when non-cabal build systems use haddock.
For example building ghc itself does not work if we add the following to `mk/build.mk`:
```
SRC_HC_OPTS += +RTS -A512M -RTS
```

At documentation generation phase ghc build will fail. I suggest filtering out all options
from `+RTS` to `-RTS` in `parseGhcFlags` area.

**Comment by alexbiehl** [comment]
Thanks for reporting. Your proposal seems reasonable.
