### ISSUE TITLE
Hide instances by default

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#698]
Even browsing through the Prelude is a hassle, among many other examples, because of the hundreds of instances that come with each type class.

**Comment by vlatkoB** [comment]
Maybe a switch somewhere on the module page that would collapse all instances?

**Comment by Lysxia** [comment]
I made PR #823 to make them collapsed by default, which I think is what we want more often than the opposite.

**Comment by harpocrates** [comment]
@Lysxia Thank you for starting this discussion on the Haskell Cafe! Based on the discussion, your updated suggestion sounds like a clear improvement on the current state.

Any ideas where the button should go? Perhaps in the top bar beside "Quick Jump", "Source", "Contents", and "Index'?

**Comment by Lysxia** [comment]
Some more related ideas:

- add the number of instances to be folded/unfolded next to every switch, that would help visitors decide whether they want to collapse a list or not, without necessarily scrolling down to realize it's too long.

- add a link to the top of a long list at the bottom.

**Comment by Lysxia** [comment]
I hope #994 and #995 address the main points of this issue!

**Comment by ntc2** [comment]
@Lysxia I'd still like a way to make "hide all instances" my personal default.

The toggle button at the top in #995 is an improvement, but for example is not so helpful if I jump into the middle of some docs by clicking on a link in Hoogle or in some other docs. In that case, I would have to scroll up to the top, click the toggle, and then scroll back down again. And I think i'd have to do it for every module, but I'm not sure (I haven't tried running your patch).

What do people think about using a cookie to save the expand/collapse state? Since you added the ability for modules to override the default in #994, I guess there would be three possible states for this expand/collapse state in the cookie:
- `default`: do whatever the module says, which is expand by default, but collapse if your new flag from #994 was used. This would also be the expand/collapse state when the cookie was not set.
- `expand`: expand all instances, even if the module says otherwise via the new #994 flag.
- `collapse`: collapse all instances.

**Comment by nomeata** [comment]
In the process of writing http://haskell-for-readers.nomeata.de/ I introduce haddock and point my readers to https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html, but especially this module is very crowded by lots of long instance lists. Having these lists collapsed by default would be great.

> add the number of instances to be folded/unfolded next to every switch

Agreed that this is a good idea.

**Comment by nomeata** [comment]
If I read the code correctly, it adds lots of configuration power, but the default is still expanded, right? Is there support for changing that to closed? I believe it would be the better choice, especially for the very important `Prelude`.

**Comment by harpocrates** [comment]
> If I read the code correctly, it adds lots of configuration power, but the default is still expanded, right? Is there support for changing that to closed? I believe it would be the better choice, especially for the very important `Prelude`.

The path to making collapsed the default is not closed off completely, just for this coming version of Haddock. Support for collapsed-by-default was not clear in the Haskell-Café thread (see @ntc2's excellent summary: https://mail.haskell.org/pipermail/haskell-cafe/2019-January/130515.html). Given that Haddock is already making some big changes with this release (like a completely new theme), I am concerned about changing too many things too quickly.

That said, here's the new UI you get once you've clicked on the "Instances" button:

<img width="464" alt="screen shot 2019-02-28 at 3 40 31 am" src="https://user-images.githubusercontent.com/10766081/53564057-b1c99280-3b0a-11e9-8a8b-ea4e22f7186e.png">

If you click "Collapse All Instances by Default" while navigating docs on Hackage, I believe this means that _any_ Haddock you subsequently explore on Hackage will reflect this new setting. In other words: the hidden-by-default behaviour can be a one-time setting if you so choose it to be.

Seem fair enough?

**Comment by nomeata** [comment]
> Seem fair enough?

Definitely an improvement, but I think the default should be optimized for newcomers experience, and configuration options should not be an excuse for not doing the work of figuring out the best defaults.

**Comment by nomeata** [comment]
There is also the approach to set the default per module, so that developers can set it (collapsed in Prelude, expanded in MTL.)

**Comment by Lysxia** [comment]
That sounds like a case for PR #994 (which adds that setting to haddock-the-tool).

**Comment by harpocrates** [comment]
These are all great points but, with my maintainer hat on, I'd like to see some sort of community consensus before moving forward with such a big change.

With my Haskell developer hat on: it'd be nice if we could come up with a solution that does not involve special casing the `Prelude`. Every time we add such a module-level or package-level option, it erodes a bit from the benefit of predictability that comes with using generated docs. That's not to say we shouldn't do this, just a word of caution about doing it...

**Comment by nomeata** [comment]
I agree with your hesitation to make it configurable on the module-level, and will shut up now (I raised my point :-))

**Comment by ntc2** [comment]
> If you click "Collapse All Instances by Default" while navigating docs on Hackage, I believe this means that _any_ Haddock you subsequently explore on Hackage will reflect this new setting. In other words: the hidden-by-default behaviour can be a one-time setting if you so choose it to be.

Yes, the "Collapse All Instances by Default" is a global setting / applies to all modules you subsequently browse on Haddock.

I agree with @nomeata that enabling this option by default would be a better choice for new users (and most existing users), but I'm also sympathetic with @harpocrates concern about changing defaults that existing users have already gotten used to. One concern I have is how easily people will discover and understand the new options, but hopefully the options will make sense if people get as far as clicking on the new "Instances" menu. We could add "tool tips" to the new options, with prose descriptions of what the options do.

**Comment by nomeata** [comment]
In one of my libraries, I wanted to re-export `Generic` so that my users don’t have to import `GHC.Generic` just for the deriving clause. But then I looked at the haddock … 6 pages of really unhelpful instance. Really, more developer control would be very helpful.

**Comment by ntc2** [comment]
Related, more than a year ago we implemented a related PR (https://github.com/haskell/haddock/pull/1007) that was merged, that gave users the option to collapse instances by default globally on hackage. However, when I go to a hackage now, I don't see the the instance options??? E.g. http://hackage.haskell.org/package/parsec3-1.0.1.8/docs/Text-Parsec.html#

**Comment by gbaz** [comment]
Docs aren't rebuilt whenever haddock is updated. That package was uploaded (and had docs built) in 2015...

**Comment by ntc2** [comment]
Okay, that makes sense @gbaz, but now I tried with a recently updated
package and I also don't see the instances menu: Okay, that makes sense,
but now I tried with a recently updated package and I also don't see the
instances menu:
http://hackage.haskell.org/package/attoparsec-0.13.2.4/docs/Data-Attoparsec-ByteString.html
.

Anyone know if the instances menu appears in the haddocks for any package
on hackage? I haven't been doing much Haskell programming for almost a
year, so I'm kind of out of the loop.

**Comment by Lysxia** [comment]
Hackage hasn't upgraded its version of Haddock for a while, that's why the automatic doc does not have that feature. At the moment you have to either manually upload docs, or read them on Stackage, which uses a recent enough version of Haddock. I don't know where to raise the issue. Maybe haskell/hackage-server?

**Comment by harpocrates** [comment]
> I don't know where to raise the issue. Maybe haskell/hackage-server?

I believe that is the right place, although I'm fairly certain they are (continually) actively working on this sort of upgrade.
