### ISSUE TITLE
Hyperlinker: Hovering a name should show its type

### ISSUE THREAD

**Issue by alexbiehl** [haskell/haddock#715]
An interesting feature for our hyperlinked source backend. Hovering over a name should show its type:

![hover](https://user-images.githubusercontent.com/1876617/33825323-944f6c5e-de61-11e7-91cd-186061039b3a.png)

Implementation should be straight forward. In https://github.com/haskell/haddock/blob/master/haddock-api/src/Haddock/Backends/Hyperlinker/Ast.hs we already collect all the information for each binder which we can use in the renderer.

In case of parameterized functions we could show the original type and the instantiated types on hover. This might give a nice experience when browsing sources.

/cc @harpocrates Interested?

**Comment by harpocrates** [comment]
Definitely interested - although I'm going to rework the constructor args stuff first. :)

**Comment by harpocrates** [comment]
@alexbiehl On closer examination - we aren't actually collecting the full types of things though, are we? This would mean holding on to quite a bit more information than we currently do...

**Comment by alexbiehl** [comment]
Yeah, I noticed that shortly after posting this. Currently we are working
incthe renamed source. For type information we need to work on the typed
source and collect Ids instead of Names. It's a bigger project than
previously thought.

Alec Theriault <notifications@github.com> schrieb am Mi., 13. Dez. 2017,
21:58:

**Comment by wz1000** [comment]
I'm about to start work on my GSOC project on [Making GHC Tooling friendly](https://docs.google.com/document/d/1QP4tV-oSJd3X90JKVY4D__Dfr-ypVB57p1yDqyk2aQ8/edit?usp=sharing) which intends to get GHC to dump all the information haddock needs to generate hyperlinked source(basically a representation of the entire AST).

I was undecided whether to include type information in this file, but this issue makes a good case that it should be included.

If all goes well, --hyperlinked-source should essentially turn into a translator from .hie files to .html files. Similarly, haskell-ide-engine would become a program that responds to LSP queries by reading .hie files, cutting out the calls to GHC to compile stuff altogether.

/cc @alanz @bgamari @gbaz @hvr

**Comment by harpocrates** [comment]
Potentially relevant: https://github.com/haskell/haddock/pull/708.

**Comment by alexbiehl** [comment]
(Are you guys at Bayhack this week? btw.)

**Comment by gbaz** [comment]
I agree that including type information makes sense. If the general goal is an output format that external tools can use to do "most everything" without reinvoking GHC or using its API directly, then this would be a good thing. My only caution would be that the .hie project should proceed incrementally so as to avoid feature-creep dragging the entire thing down -- i.e. I don't want the scope of the project to inflate in such a way that rather than _more_ stuff, we get nothing at all :-)

**Comment by alanz** [comment]
I think the other important factor is the interface provided to tooling to actually access this information.

So to support @gbaz, some sort of full life cycle demo of aninitial limited/uncontroversial data structure would probably make sense.

**Comment by harpocrates** [comment]
> If all goes well, `--hyperlinked-source` should essentially turn into a translator from .hie files to .html files.

I am curious to see how you work around CPP for this. The more I think about this whole feature request, the less sure I am about what should be produced... I guess solving that is part of the fun!

**Comment by harpocrates** [comment]
hyperlinked-source has a bunch of (barely good-enough) heuristics for trying to split up the input into alternating CPP and non-CPP chunks. The GHC tokenizer gets run on the non-CPP segments. This lets us give tokens pretty colours without having more meaningful ASTs.

Separately (and where .hie files are more obviously useful), the renamed source gets traversed SYB-style to collect linking information. That means that whatever CPP code path ended up being chosen to produce the renamed source is the only one that ends up having links and anchors.

**Comment by harpocrates** [comment]
> So it sounds like we could do something similar here?

I totally agree. I just wanted to point out that making `--hyperlinked-source` work _entirely_ from .hie files might involve following a pretty deep CPP rabbit hole.

**Comment by wz1000** [comment]
An interesting possibility for future work could be a way to merge together
.hie files that took different CPP pathways.

**Comment by harpocrates** [comment]
Implemented in 1b26460fb3b5df5215cc1e6715661cbc7c950085.
