### ISSUE TITLE
haddock-library-1.4.4.x without internal libraries?

### ISSUE THREAD

**Issue by shlevy** [haskell/haddock#719]
Internal libraries do not quite yet seem ready for prime time: We can't build haddocks https://github.com/haskell/cabal/issues/4969 and we can't build with nix https://github.com/NixOS/nixpkgs/issues/32980. Can we have a new release of `1.4.4.x` so we can use haddock-api-2.18.x without hacking around these issues until they're properly fixed?

**Comment by hvr** [comment]
fwiw, http://hackage.haskell.org/package/haddock-library

**Comment by shlevy** [comment]
Do you know how they're built? Using new-haddock maybe? (haven't tested if that works)

**Comment by hvr** [comment]
Tbh, I don't remember, I'll retry regenerating them, then I should be able to tell you.

**Comment by shlevy** [comment]
We've fixed internal library builds in nixpkgs and disabled haddock builds for haddock-library, so I guess this isn't needed.
