### ISSUE TITLE
Infix class methods lack fixity declaration in --hoogle output

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#722]
Taking a look at the output of `--hoogle` for the base library, things like `***` get an entry, but don't get a fixity declaration entry. I see:

```
(&&&) :: Arrow a => a b c -> a b c' -> a b (c, c')
```

But would expect to also see:

```
infixr 3 &&&
```

**Comment by RyanGlScott** [comment]
Odd. While most functions' fixities get propagated to `--hoogle` output, it seems that class methods don't benefit from this for some reason.
