### ISSUE TITLE
LaTeX backend: declNames error

### ISSUE THREAD

**Issue by ugeorge** [haskell/haddock#727]
When trying to generate LaTeX documentation of a more complex project (i.e. makes use of type classes and type families), Haddock throws the following error and no output is generated:

    haddock: internal error: declaration not supported by declNames
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Backends/LaTeX.hs:257:8 in main:Haddock.Backends.LaTeX

Possible cause: at the [pointed line](https://github.com/haskell/haddock/blob/e812e1a371187b2d0c2a789f3b5afd430163440a/haddock-api/src/Haddock/Backends/LaTeX.hs#L258) `declNames` throws an error instead of handling the remaining type constructors `InstD` and  `DerivD`) safely.

Haddock version: 2.16.1
Cabal version: 2.0.0.1
GHC version: 8.2.1

**Comment by harpocrates** [comment]
Fixed in ae23b4f25a972620686617b5aab5375d5046b1c9.
