### ISSUE TITLE
Hyperlinked source links to pattern synonyms don't work 

### ISSUE THREAD

**Issue by harpocrates** [haskell/haddock#731]
In the hyperlinked sources, clicking on a pattern synonym does _not_ bring you to its definition. Ditto for modules in export lists.

**Comment by alexbiehl** [comment]
A wild guess: we don't generate anchors for these yet?

**Comment by alexbiehl** [comment]
Ah, we are missing a case for `PatBind` here https://github.com/haskell/haddock/blob/4aa69143fd620644bbc899a5996089865cbafd34/haddock-api/src/Haddock/Backends/Hyperlinker/Ast.hs#L112-L114

**Comment by alexbiehl** [comment]
I figured we need to handle pattern synonyms in `Haddock.Backends.Hyperlinker.Ast` (`PatSynBind` and `PatSynSig`)
