### ISSUE TITLE
haddock ignoring extra-source-files

### ISSUE THREAD

**Issue by tonyday567** [haskell/haddock#759]
Haddock does not copy over images I keep in my other directory, which are listed in extra-source-files.

An example is an old upload of a library of mine https://hackage.haskell.org/package/chart-unit-0.5.4/docs/ versus a newer one https://hackage.haskell.org/package/chart-unit-0.5.5.0/docs/

**Comment by hvr** [comment]
Does Haddock also ignore the  `extra-doc-files` declaration? (c.f. http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-extra-doc-files )

**Comment by tonyday567** [comment]
I get:

```Warning: Ignoring unknown field "extra-doc-files" in package description```

I suspect this is a hpack issue.

**Comment by tonyday567** [comment]
A quick glance at the hpack repo and it looks like extra-doc-files support went in a few days ago, so should be flowing through stack soon.

Bypassing package.yaml fixes in the meantime, so closing.

Thanks for the help!
