### ISSUE TITLE
Haddock doesn't show exports for reexporting modules with explicit imports lists

### ISSUE THREAD

**Issue by ChShersh** [haskell/haddock#765]
Probably related issues: #563 #584 

If I reexport module which I import with explicit import list, I don't see documentation for things I reexported, only module name.

Code example:

```haskell
module Universum.Function
       ( module Data.Function
       ) where

import Data.Function (const, fix, flip, id, on, ($), (.))
```

How it renders:

![screenshot from 2018-02-28 19-03-25](https://user-images.githubusercontent.com/4276606/36797876-2eace222-1cba-11e8-97aa-7edccaa8e15c.png)

Full example here:

* http://hackage.haskell.org/package/universum-1.1.0/docs/Universum-Function.html

I find this non-convenient to reexport every function manually just to see it in Haddock...

Maybe this is fixed by this PR: #688 

If so, it's good to have confirmation (cause I'm using `haddock-2.17.4`).

**Comment by alexbiehl** [comment]
I just tried haddock-2.19.0 (coming with ghc-8.4.1-rc1) and it looks like this: 

![bildschirmfoto 2018-02-28 um 17 51 38](https://user-images.githubusercontent.com/1876617/36800550-150072ee-1cb0-11e8-86b5-b6dbff7b66f5.png)

So, yes this should be fixed. This can be closed then, right?

**Comment by ChShersh** [comment]
@alexbiehl Sure, you can close this! Thanks for confirmation and your your effort :pray:
