### ISSUE TITLE
internal error: extractDecl (ClsInstD)

### ISSUE THREAD

**Issue by tmcdonell** [haskell/haddock#775]
I encountered this error running haddock on `accelerate-llvm-native` ([example travis log](https://travis-ci.org/tmcdonell/accelerate-llvm/jobs/352645388#L3445)):

```
haddock: internal error: internal: extractDecl (ClsInstD)
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1067:16 in main:Haddock.Interface.Create
```

 - ghc-8.4.1
 - haddock-2.19.0 and 2.19.0.1
 - ubuntu 14.04 and macOS 10.13

If you have some suggestions for how to trim this down to a smaller example I can try that. Otherwise this should reproduce it:

```
$ git clone https://github.com/AccelerateHS/accelerate-llvm.git
$ cd accelerate-llvm
$ stack haddock accelerate-llvm-native
```

**Comment by alexbiehl** [comment]
Trevor, thank you for your report. 'extractDecl' is called for exports that only export a small part of the whole declaration. In this case we are talking about a class instance which probably exports an associated data type or similar and we are only interested in that data type. Maybe that helps pinning down the offender. 

I will investigate by myself later today.

**Comment by alexbiehl** [comment]
Trevor, I couldn't find anything suspicious from your source (I just had a look, couldn't build it for some reason). I found a missing case in `extractDecl` (see https://github.com/haskell/haddock/commit/7b3f6f3a5230dab898a8a824f03636e27b84bfb1). 

This case was strictly not possible with older versions of haddock. Could you give it a try?

**Comment by tmcdonell** [comment]
Hi @alexbiehl, thanks for the quick fix! haskell/haddock@ 7b3f6f3a5230dab898a8a824f03636e27b84bfb1 seems to have done it! (:

**Comment by alexbiehl** [comment]
Good to know. Interestingly, AFAIK, this situation can only arise with the use of `pattern` exports like this: 
```
module (pattern A) where

class T a where 
  data X a

instance T Bla where
  data X Blah = A | B
```

I couldn't find such a thing in your source code. Have you seen something like this?

**Comment by tmcdonell** [comment]
Interesting. I don't have any pattern synonyms at all. There are some associated data types ([1](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm-native/src/Data/Array/Accelerate/LLVM/Native/Compile.hs#L59), [2](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm-native/src/Data/Array/Accelerate/LLVM/Native/Link.hs#L49), [3](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm-ptx/src/Data/Array/Accelerate/LLVM/PTX/Compile.hs#L89), [4](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm-ptx/src/Data/Array/Accelerate/LLVM/PTX/Link.hs#L51)) which are all standard records, and a few non-associated data families ([1](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm/src/Data/Array/Accelerate/LLVM/CodeGen/IR.hs#L45), [2](https://github.com/tmcdonell/accelerate-llvm/blob/757485c73dc113944e6582147c880a952f043245/accelerate-llvm/src/Data/Array/Accelerate/LLVM/CodeGen/Module.hs#L42), [3](https://github.com/tmcdonell/accelerate/blob/master/src/Data/Array/Accelerate/Array/Data.hs#L118)), but I think that is it.

**Comment by alexbiehl** [comment]
Ok, could you upload the documentation somewhere?

**Comment by tmcdonell** [comment]
Uploaded here: https://tmcdonell.github.io/haddock-bug/accelerate-llvm-native-1.2.0.0/

Here is a slightly older version build with ghc-8.2 / haddock-2.18.1: http://tmcdonell-bot.github.io/accelerate-travis-buildbot/accelerate-llvm-native-1.2.0.0/index.html
