### ISSUE TITLE
Why is attoparsec re-packaged inside of haddock-library?

### ISSUE THREAD

**Issue by peti** [haskell/haddock#784]
I was very surprised to see that `haddock-library` re-distributes `attoparsec` as an internal library even though the package is readily available for re-use on Hackage. May I ask why that decision was made?

**Comment by alexbiehl** [comment]
Haddock ships with GHC. As such it may only depend on packages which are
distributed with GHC itself. That's basically it.



Peter Simons <notifications@github.com> schrieb am Do., 22. März 2018 um
10:14 Uhr:

**Comment by peti** [comment]
In theory, it should be possible to switch between a dependency on an internal sub-library and a dependency on the proper public `attoparsec` by means of a Cabal flag. That way, the build for GHC  could be stand-alone, but everyone else who's building from Hackage would benefit from `attoparsec` updates, etc. Would that be an option?

**Comment by hvr** [comment]
@peti we need a rather small part of `attoparsec` and it makes dependency management if we do *not* need to track an external `attoparsec` dependency; as then people would inevitably ask us to update `haddock-library` to support newer versions of `attoparsec`. `attoparsec` is a private dependency of `haddock-library`, and internal implemetnation detail, and as such we prefer to keep it hidden/vendored; this gives us more freedom.

**Comment by mimi1vx** [comment]
@hvr and kills packaging for Linux distributions

**Comment by hvr** [comment]
@mimi1vx That's not true; Linux distros already patch Haskell packages as needed to fit their respective policies; just look at Debian

**Comment by mimi1vx** [comment]
@hvr ok, better look to rpm-based distros and for something more recent than debian

**Comment by hvr** [comment]
@mimi1vx The problem you seem to be referring to (support for a package containing multiple libraries) is a much more general one that downstream packaging system will have to deal with anyway as we're going to see a lot more of this with the upcoming [Support for Multiple Public Libraries in a .cabal package](https://summer.haskell.org/ideas.html#cabal-multiple-libraries).

**Comment by harpocrates** [comment]
Not to hijack this issue too much, but why are we using `attoparsec` at all? It isn't exactly the library that comes to mind when thinking "we need to parse potentially rich UTF-8 text"... Is this mostly for historical reasons? Or for performance (something makes me doubt this - our performance is dominated by typechecking time)?

**Comment by gbaz** [comment]
The attoparsec dep was added in the course of the 2013 gsoc work by @Fuuzetsu : http://fuuzetsu.co.uk/blog/posts/2013-07-30-first-month-with-haddock.html

**Comment by Fuuzetsu** [comment]
It was used to replace usage of Alex/Happy for doc comment parsing as those had a huge issue with unicode (and would frequently fail because of it) as well as being generally pretty difficult to work with.

I don't like attoparsec in-tree any more than the next guy. The only reason we're in such situation these days is that Haddock heavily relies on GHC API and while it no longer lives in-tree for development, it's still a submodule and is updated by GHC devs as they update the API. This allows GHC folks to generate documentation as they go along. When I was working on it, we already had a gracious policy whereas _I_ didn't have to track GHC HEAD and we'd simply update Haddock master when new release was about to happen.

I think until Haddock is used and updated by GHC devs, attoparsec has to stay in-tree. It is of course possible to use a cabal flag to pick the implementation but I worry that will just complicate things: one set of people uses a stripped down vendored version while another set of people gets the full thing off hackage.  

@peti may I ask why you're asking? As far as the ecosystem itself is concerned it should make no difference whether or not attoparsec is vendored inside Haddock and should be treated as simply being part of Haddock source.

**Comment by peti** [comment]
I asked because in my experience it's a mistake to bundle another package inside of your own package rather than just express a proper dependency. I was curious why that was done, and I can understand the reasoning. GHC wouldn't allow a proper dependency, so I guess the current solution is fine under the circumstances. It's a shame that this is necessary, but unfortunately it is.

Anyway, there is an amusing bit of irony to be found in the fact that distributions like Nix and openSUSE now cannot distribute Haddock documentation for `haddock-library` because of https://github.com/haskell/cabal/issues/4969.

**Comment by quasicomputational** [comment]
I'd guess the stack issue is that stack is getting confused by the name collision between attoparsec proper and the bundled attoparsec. Renaming the bundled one could potentially fix that (not that I've tried). The cabal issue wrt building documentation looks more fundamental.

Is switching to plain old parsec out of the question? That's a GHC boot library so depending on it ought to not be a problem.

**Comment by gbaz** [comment]
@Fuuzetsu I actually recently thought of the same question as above. I.e. do you think at some unspecified future point a switch to parsec (without cratering performance) would be possible? Obviously it would be a ton of work and I'm not proposing anyone do it at this time, but just in terms of feasibility, it might be nice at some point to stop vendoring and start relying on the now more expansive set of bootlibs...

**Comment by Fuuzetsu** [comment]
@gbaz when it was written I don't think parsec was in boot libs. There's nothing that we do that is attoparsec specific and the parsers are (or were when I wrote them) pretty basic. I don't think it'd be a lot of work to port it over at all. Performance could end up worse but the time spent parsing comments is actually really tiny relative to everything else Haddock does and is completely trumped by any GHC API interactions. I think it would be OK if someone wants to sit down for few hours and port things over to parsec then remove the attoparsec vendor.

**Comment by harpocrates** [comment]
Wasn't `parsec` added in the boot libs only in 8.4.1? I think that is what [this](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory) table indicates although I'm not sure...

In any case, I just wanted to report I am in the process of removing `attoparsec` in favor of a regular `parsec` dependency. I'll probably open a PR tonight or sometime this weekend.

**Comment by gbaz** [comment]
Yes -- parsec was only recently added, so as Fuuzetsu said, at the time, using attoparsec vs parsec wasn't really a difference in terms of expanding the dep footprint. A PR moving over sounds like a good way to tackle tech debt to me :-)

**Comment by hvr** [comment]
@gbaz first off, I strongly disagree about the "technical debt" claim. What exactly is the debt here? Moreover, we need to be very careful about performance here. If switching to `parsec` has any noticeable performance regression I consider it a show stopper.  If anything, I rather had the intention to try to switch to `alex`/`happy`, but certainly not `parsec`.

**Comment by harpocrates** [comment]
Here is how I see this:

  * Having a vendored `attoparsec` is suboptimal. More code is almost never a good thing. Besides, we are stuck regularly porting over changes from a subset of the actual `attoparsec`.
  * `attoparsec` is not the right library for this purpose: it is for parsing binary formats, not UTF-8 source.

Both of these points are the result of decisions taken at a time when this was the best alternative. It no longer is: `parsec` is part of the boot libs, so we can properly depend on it and, if we use it via `Text`, we will have proper UTF-8 characters. Also, `parsec` and `attoparsec` have similar APIs (modulo backtracking), so we can switch from one to the other with reasonable confidence in correctness.

>  I rather had the intention to try to switch to `alex`/`happy`, but certainly not `parsec` (and I say this being the current maintainer of `parsec`).

I'm curious, what worries you? If there are serious problems with `parsec`, why was it allowed to become a boot lib? I am personally against trying to use `alex`/`happy`. Even if someone manages to write a grammar for Haddock (and I seriously doubt this is possible), it will become a nightmare to debug/tweak. I say this having just completed a giant parser project in which I uncovered several Happy bugs.

**Comment by gbaz** [comment]
I agree with the above. If it is easy, the performance hit is negligible, and we're confident in our tests, then it sounds like a win in terms of reducing maintenance long-term. (And points 1 and 3 are what makes looking towards parsec particularly appealing). If it fails on any of these axes, then probably there's not enough bang for the buck to do it any time soon unless there's some further strong motivation.

**Comment by Fuuzetsu** [comment]
It is possible to write happy/alex grammar. This is what haddock used to use and what attoparsec replaced. Happy was awful to maintain and there were several utf related bugs. Again, the actual comment parsing time is so negligible that even 5x slower parsing time would probably not be noticable. Not that I think parsec eould be 5x slower here. Copy pasting out of date attoparsec code is certainly a good reason to switch to a proper, maintained package. Definitely against happy here, it has many many outstanding bugs that will never be fixed because it works for ghc and nobody else cares. It's also unfun to work with.

**Comment by harpocrates** [comment]
> Definitely against happy here, it has many many outstanding bugs that will never be fixed because it works for ghc and nobody else cares.

Off-topic, I know, but really? If you know of any outstanding bugs, please report them! I went through a while ago and fixed all of the correctness bugs I could find. Right now, the issue tracker is just full of (half-baked) feature-requests (and one compile-time regression blocked by GHC).

**Comment by hvr** [comment]
> If there are serious problems with parsec, why was it allowed to become a boot lib? 

To be honest, we would have rather gone w/ `megaparsec` as every new project should, but due to the dependency footprint it wasn't an option.
