### ISSUE TITLE
Generalize string type 

### ISSUE THREAD

**Issue by alexbiehl** [haskell/haddock#791]
We want to parameterise DocH over the string type and offer String and ByteString (and in the future Text) versions of the parser. 

This will help us avoid unnecessary string conversions in haddock and ghc with the hi haddock proposal.

**Comment by harpocrates** [comment]
What is the plan for this now that `haddock-library` works over `Text`? Shall we still parameterize `DocH` over the string type, or just switch the string fields to `Text`?

I'd like to solve this so I can afterwards propose some small enhancements to `DocH` in preparation for eventual markdown support.

**Comment by alinab** [comment]
I have a solution for this on a local feature branch but will require permissions to set up a pull request.
