### ISSUE TITLE
`@since` annotations should include the package name

### ISSUE THREAD

**Issue by taktoa** [haskell/haddock#800]
Suppose that a package `foo-2.0.1` exposes a module `Foo` containing an identifier `bar` that has an `@since 2.0.0` attribute in its documentation comment, and then another package `baz-1.0.0` reexports `Foo.bar` from an exposed module `Baz`. Running Haddock on `baz` will result in documentation that confusingly says `@since 2.0.0` on an identifier exported by a module in a package whose version is only `1.0.0`! This could be ameliorated by including in the rendered version of an `@since` attribute the name of the package the identifier was defined in.

For a concrete example: [this](https://hackage.haskell.org/package/hedgehog-0.5.3/docs/Hedgehog.html#t:Ord1) says `Since 4.9.0.0`, even though `hedgehog` only has version `0.5.3`! Perhaps it would also be convenient to make the package name a link, e.g.:

_Since: [base](https://hackage.haskell.org/package/base) version [4.9.0.0](https://hackage.haskell.org/package/base-4.9.0.0)_

Unrelatedly (but relevant since the rendering of `@since` annotations will have to be changed for this issue), while I like the idea of `@since` annotations, I think the current way of rendering them clogs up the Haddock output if you put them on everything. When I wrote `language-ninja`, I actually wrote some [ridiculous JS/CSS](https://github.com/awakesecurity/language-ninja/tree/58030e1a9ebb2026d280c7aae2a1cb3b5e9321bc/misc) to make them easier on the eyes: [example](https://hackage.haskell.org/package/language-ninja-0.2.0/docs/Language-Ninja-AST.html).

**Comment by gbaz** [comment]
@NunoAlexandre maybe this is something that could be addressed in the haddock redesign?

**Comment by harpocrates** [comment]
`@since` annotations should include the package name since 978dbc859df09eb991d9ccc0911276cc9655b783.
