### ISSUE TITLE
Windows line endings (CRLF) affect HTML source code rendering?

### ISSUE THREAD

**Issue by mpilgrem** [haskell/haddock#812]
On Hackage, Windows line endings (CRLF) affect the rendering of source code. See, for example, https://hackage.haskell.org/package/ansi-terminal-0.8.0.3/docs/src/System.Console.ANSI.html, which renders with a blank line between each line of source code. The hackage-server GitHub repository has identified this as a Haddock-related issue to be raised here (https://github.com/haskell/hackage-server/issues/750).

This sort of issue may have arisen in the past: see #57.

**Comment by harpocrates** [comment]
Did you generate the documentation on a windows machine (I wasn't able to reproduce this when rebuilding docs for `ansi-terminal` on MacOS)? Also, what version of Haddock are you using?

The hyperlinked-source backend was changed recently and I'm not sure it ever got tested on windows...

**Comment by mpilgrem** [comment]
I am not using Haddock myself but I understand that Hackage does - but I do not know how, exactly.

I use a Windows machine to code. When I use `git`, it translates CRLF (local) to LF (repository) and vice versa. However, when I use `stack sdist` or `stack upload` to publish on Hackage, those tools are used locally and package the local files (which contain CRLF line endings).

**Comment by gbaz** [comment]
Hackage's docbuilder runs on ubuntu. We're using the latest released haddock. So the issue isn't running on windows, but rather that the new hyperlinked-source backend may not have special handling to translate CRLF.
