### ISSUE TITLE
Backticks on infix identifiers are not monospaced

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#824]
This docstring

```
'elem' is often used infix: ``elem``
```

renders as

![image](https://user-images.githubusercontent.com/3664523/39852648-f41083e4-541d-11e8-98f5-fdfd02eafddf.png)

I think it makes more sense to monospace the backticks too.

(Related: https://github.com/haskell/haddock/issues/780)

**Comment by harpocrates** [comment]
Fixed in a5199600c39d25d7b71dcb2328000c1c49ad95a2:

![screen shot 2019-02-25 at 11 01 06 am](https://user-images.githubusercontent.com/10766081/53361482-b7e22800-38ec-11e9-9c4c-40b2008a02f1.png)
