### ISSUE TITLE
Some parentheses cause MINIMAL pragma to be excluded from Haddock output

### ISSUE THREAD

**Issue by taktoa** [haskell/haddock#834]
With Haddock 2.18.1, the following code (excerpted from [here](https://github.com/taktoa/eqsat/blob/547fdc9b8b7cc45e0ab407c02f5ad4a4d8716e2f/library/EqSat/TermIndex/Class.hs#L483-L553)):

```haskell
class (TermIndex index) => Mergeable index where
  {-# MINIMAL (merge | mergeMany) #-}

  merge
    :: (Monad m, Key node var)
    => index node var value
    -> index node var value
    -> (value -> value -> m value)
    -> m (index node var value)
  merge left right comb = do
    mergeMany (BV.fromList [left, right]) comb

  mergeMany
    :: ( Monad m, Key node var
       , Vector vec (index node var value)
       , Vector vec (Mut index node var value (PrimState m))
       )
    => vec (index node var value)
    -> (value -> value -> m value)
    -> m (index node var value)
  mergeMany indices comb = do
    Vector.foldr (\x my -> my >>= \y -> merge x y comb) new indices

  mergeMut
    :: (PrimMonad m, Key node var)
    => Mut index node var value (PrimState m)
    -> Mut index node var value (PrimState m)
    -> (value -> value -> m value)
    -> m (Mut index node var value (PrimState m))
  mergeMut leftMut rightMut comb = do
    left  <- freeze leftMut
    right <- freeze rightMut
    merge left right comb >>= unsafeThaw

  mergeManyMut
    :: ( PrimMonad m, Key node var
       , Vector vec (index node var value)
       , Vector vec (Mut index node var value (PrimState m))
       )
    => vec (Mut index node var value (PrimState m))
    -> (value -> value -> m value)
    -> m (Mut index node var value (PrimState m))
  mergeManyMut indicesMut comb = do
    indices <- Vector.mapM freeze indicesMut
    mergeMany indices comb >>= unsafeThaw
```

results in this output:

![selection_205](https://user-images.githubusercontent.com/553443/40360565-30f2f8a6-5d8c-11e8-8bba-e43f1f91f16f.png)

If I remove the parentheses from the `MINIMAL` pragma (i.e.: `{-# MINIMAL merge | mergeMany #-}`), I get this output:

![selection_206](https://user-images.githubusercontent.com/553443/40360573-35084c0c-5d8c-11e8-9408-4a620b834b4c.png)

It is not clear to me whether this is a bug in GHC's parser for `MINIMAL` pragmas (which would hopefully not just silently fail on input that it doesn't understand!), or a bug in Haddock. The [GHC manual](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#minimal-pragma) states that parentheses are allowed at the top level in `MINIMAL` pragmas.

**Comment by taktoa** [comment]
Note that the `{-# MINIMAL (remove | removeMany), (removeMut | removeManyMut) #-}` pragma defined [in the same file](https://github.com/taktoa/eqsat/blob/547fdc9b8b7cc45e0ab407c02f5ad4a4d8716e2f/library/EqSat/TermIndex/Class.hs#L567) has the same problem, which is actually a real problem since then the only way to write this pragma is with the ugly

```haskell
{-# MINIMAL remove, removeMut | removeMany, removeMut | removeMany, removeMut | removeMany, removeManyMut #-}
```

since `,` binds stronger than `|` in `MINIMAL` specifications.

**Comment by alexbiehl** [comment]
I think we should honor the Parens case here: https://github.com/haskell/haddock/blob/978dbc859df09eb991d9ccc0911276cc9655b783/haddock-api/src/Haddock/Backends/Xhtml/Decl.hs#L552

**Comment by alexbiehl** [comment]
@taktoa Could you execute `ghc --show-iface <your build path>/EqSat/TermIndex/Class.hi` and see if the minimal pragma with parenthesis is present in the interface?
