### ISSUE TITLE
Move HsDocString to ByteString in time for GHC-8.6!?

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#840]
I already have a WIP patch moving HsDocString from FastString to ByteString at https://github.com/sjakobi/ghc/commit/c4066e2160c28a60ac9e36ded1d8eb3ba45a3d0d.

As this does seem to help with performance I'm wondering if there was a point in doing this switch already in GHC-8.6.

Obviously this also requires changes to haddock-api. But as I'm only seeing 4 places where HsDocStrings are deconstructed, I think this should be doable in these time constraints.

What do you think about this?

The corresponding GHC ticket is https://ghc.haskell.org/trac/ghc/ticket/15157.

**Comment by alexbiehl** [comment]
Do it! But do it fast the merge window is closing slowly but surely /cc @bgamari
