### ISSUE TITLE
Documentation for backquotes

### ISSUE THREAD

**Issue by elpinal** [haskell/haddock#847]
The behavior of backquotes should be described.

**Comment by harpocrates** [comment]
Could you elaborate on precisely what you wish was documented?

**Comment by elpinal** [comment]
It's my fault that I vaguely explained what is a problem when opening this issue.

I have lost enthusiasm for this issue.
So I don't care about how this issue goes on.


Anyway, I saw some documentation comment (I forget where) contain something like this:

```
-- | @x `operator` y@
...
```

I think the author of the comment intended to use backquotes as the Haskell's infix notation, but unfortunately, haddock considers these backquotes as the notation for hyperlinked identifiers.

The problem is that, as far as I know, this behavior (backquotes are treated as the notation for hyperlinked identifiers) is not documented in https://haskell-haddock.readthedocs.io/en/latest/index.html.

**Comment by harpocrates** [comment]
Good point, this is only very briefly mentioned in the docs (https://haskell-haddock.readthedocs.io/en/latest/markup.html#hyperlinked-identifiers). We should fix this.

Thanks for elaborating!
