### ISSUE TITLE
Escaped apostrophes following identifiers are misparsed

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#848]
I knew that `'Foo''s ...` would be misparsed but expected `'Foo'\'s ...` to work.

Sadly the parser doesn't know that identifiers can't be a mix of letters and symbols and accepts the `\`. As ghc's `parseIdentifier` rejects this mess, we end up with

![image](https://user-images.githubusercontent.com/3664523/40943238-a87f6354-6850-11e8-9ef7-43cedec38d37.png)

As a workaround I use

```
`Foo`'s ...
```

**Comment by sjakobi** [comment]
If we can't write a correct parser ourselves, we could change `parseString` and `parseParas` to use the validation function that is currently only applied with `overIdentifier`. The validation function would help us pick a valid identifier in `parseValid`.

**Comment by harpocrates** [comment]
Fixed in a5199600c39d25d7b71dcb2328000c1c49ad95a2.

`'Foo'\'s` is now properly parsed as: a link to `Foo'`, an escaped `'`, and an s. Proof:

![screen shot 2019-02-25 at 9 16 45 am](https://user-images.githubusercontent.com/10766081/53355588-27045000-38de-11e9-9825-a9bbaa3b85e9.png)
