### ISSUE TITLE
Document the parser gotchas

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#852]
The Haddock parser currently has some bugs where the workaround isn't always obvious. See for example #848.

Until the parser is fixed, it would be good to have some recommendation on how to avoid these gotchas. For example, using backticks to delimit identifiers is more reliable than using single ticks.

**Comment by harpocrates** [comment]
@sjakobi Do you have other examples of this sort of gotcha? I can't think of any that are still not fixed.

**Comment by sjakobi** [comment]
I can't think of any either. Thanks for all the UX improvements! :)
