### ISSUE TITLE
Avoiding CI breakage on ghc-head?

### ISSUE THREAD

**Issue by harpocrates** [haskell/haddock#859]
In the time I've been following Haddock development, it roughly follows a cycle

  1. there is a branch for the latest stable GHC (currently `ghc-8.4`) and a branch for GHC HEAD (`ghc-head`) and most changes go into the former (since few people actually have HEAD available)
  2. when GHC release candidates becomes available, there is some scrambling to try to get everything in the stable branch also in the head branch
  3. when that version is actually released, a new branch is created

Point 1 is really where the most time is spent. Unfortunately, stuff gets merged into `ghc-head` without tests passing all the time. This is sometimes because the test suite cannot be built, other times because matching GHC changes have not made their way into Herbert's PPA yet. That means that by the time point 2 rolls around, we are stuck accepting a bunch of test output changes all at once (and the odds of something incorrect being let in are much higher)!

The only simpler way I can think of fixing this situation is to change our CI script to install Cabal/GHC from tarballs (so we can take advantage of the nightly-built tarballs). That way, we can keep `ghc-head` mostly green even if features coming into Haddock are going to depend on a very recent GHC. I'm already doing something similar [here](https://github.com/harpocrates/inline-rust/blob/8bf7e3c811006a851f2de733442bfa669a75d20d/.travis.yml).

In any case, I'd be interesting in people's opinions (in particular @hvr).

**Comment by hvr** [comment]
We're fully aware of this workflow dilemma. But ghc-head suffers from additional issues as Hackage generally can't (nor should it!) be expected to be compatible with GHC HEAD. So it's quite likely that ghc-head will fail CI due to accidental reasons.

Fwiw, the easiest way to avoid having to resort to the rather inconvenient use of nightly tarballs would be if I simply increase the build-rate of my ghc-head PPA again to its original daily frequency.

**Comment by harpocrates** [comment]
> Fwiw, the easiest way to avoid having to resort to the rather inconvenient use of nightly tarballs would be if I simply increase the build-rate of my ghc-head PPA again to its original daily frequency.

At its core, that functionally equivalent to what I was proposing - minus the inconvenience of dealing with tarballs. It would be nice if we also had an Appeyor CI (I introduced a windows-only regression not too far back that could've been easily avoided). Do you know if chocolatey offers GHC HEAD anywhere?

**Comment by harpocrates** [comment]
I'm hitting this again (CI is broken on ghc-head).

> ... easiest way to avoid having to resort to the rather inconvenient use of nightly tarballs ...

Why would it be more inconvenient to use nightly tarballs here? They would be more up to date (for instance CI would be working right now if we had that set up). Plus we could start testing MacOS and Windows. 

I'm also seeing some unexpected test outputs with the PPA...

**Comment by hvr** [comment]
Fwiw, I had to stop building ghc-head packages, since GHC `master` is currently exposing the wrong version number, which is messing up everything.  This is actually a reason more *not* to use those uncontrolled nightly tarball builds.

**Comment by harpocrates** [comment]
I think using the nightly tarballs might be a good idea because they should almost always build Haddock (since Haddock must also have been built as part of GHC's validate). Sure, sometimes GHC `master` is not going to be able to build the full testsuite, but that seems like an acceptable limitation.

Would a reasonable compromise be to have an additional Travis build job that uses the tarballs? It won't be always green, but when it _is_ green we can be pretty sure that everything is correct.

**Comment by hvr** [comment]
I've just removed redundant CI jobs from the matrix, cause they were wasting resources.... so I'm not thrilled about adding back others, and in the process complicating the scripting (which as you may have noticed is being auto-generated; if you do manual changes, these may easily be lost again when the Travis CI config is re-generated).

**Comment by harpocrates** [comment]
> I've just removed redundant CI jobs from the matrix, cause they were wasting resources.... 

CI on `master` GHC is nonetheless something we should have. That it is currently not working is not necessarily an indication it can't.

>  and in the process complicating the scripting (which as you may have noticed is being auto-generated; if you do manual changes, these may easily be lost again when the Travis CI config is re-generated).

I did notice this. I still think it would be worth trying out my suggestion (I'll put up a PR when I find the time). `multi-ghc-travis` doesn't look like the right fit for Haddock:

  * we don't actually care about testing against a bunch of GHC versions
  * we care about testing against as new as possible a version `master` GHC
  * it is Ubuntu specific (and so couldn't catch the recent windows-only CRLF bug, or the MacOS-only crash of `html-test`)

Since the current script is auto-generated, it should be quite easy to revert back to the existing behaviour if so desired, no?

**Comment by hvr** [comment]
Btw, we've resolved the version-mixup with GHC's  `master` and `ghc-head` which wasn't the CI's fault but rather a problem on GHC's end. Things should soon normalise again. I'll keep an eye on CI and resolve remaining issues as I see them

Stay tuned!

**Comment by harpocrates** [comment]
We now use GHC CI artifacts on the `ghc-head` branch (since bf07847e45356024e10d1a325f015ac53544ea85).

It has been working nicely, so closing this for now.
