### ISSUE TITLE
--show-interface outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#864]
The docs state:

> Dumps a binary interface file to stdout in a human readable fashion.

**Comment by harpocrates** [comment]
Could we just change the docs? Otherwise, I fear the dump output and the warnings will be difficult to separate. Right now, I rely on `haddock --dump-interface foo.haddock 2> foo_interface.txt`.

**Comment by alexbiehl** [comment]
Yes, let's do that.

Alec Theriault <notifications@github.com> schrieb am So., 1. Juli 2018,
14:11:

**Comment by sjakobi** [comment]
> Could we just change the docs? Otherwise, I fear the dump output and the warnings will be difficult to separate.

Hm, separation of warnings and dump output is precisely what I'd like to have here:

If I pipe the dump output to e.g. `python -m json.tool` to make it readable, I want the warnings to go to a different handle.
