### ISSUE TITLE
Re-exported modules aren't shown when ignore-exports is enabled

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#866]
```
{-# OPTIONS_HADDOCK ignore-exports #-}
module Lib (module Data.Tuple) where
import Data.Tuple
```

is rendered as

![image](https://user-images.githubusercontent.com/3664523/42028576-ec1a6b3e-7acc-11e8-9555-2203912a60dc.png)

The problematic code seems to be this:

https://github.com/haskell/haddock/blob/9339517a2bd1c16c1d11e66d9c754f0ef702f99a/haddock-api/src/Haddock/Interface/Create.hs#L121-L130

**Comment by sjakobi** [comment]
I thought it would be sufficient to change line 128 above to use `exports0` but that's not the case.

**Comment by tysonzero** [comment]
@sjakobi

What is the long term alternative plan for this situation given the "wontfix" label?

We're using haddocks as our internal documenting tool, so we benefit a lot from being able to see both re-exports and un-exported definitions. 

Currently we of course have to choose one or the other, and it seems that in future we may not even be able to choose (`ignore-exports` getting removed?).
