### ISSUE TITLE
Hoogle backend removes parentheses erroneously for functions reexported from other packages

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#873]
Take this module:

```haskell
module Bug (($)) where
```

And run `haddock --hoogle --package-name=bug --package-version=0.0.0 Bug.hs`. You'll get some very questionable results in `bug.txt`:

```
-- Hoogle documentation, generated by Haddock
-- See Hoogle, http://www.haskell.org/hoogle/

@package bug
@version 0.0.0

module Bug
($) :: () => a -> b -> a -> b
```

The type of `($)` is quite wrong, since it's missing some critical parentheses.

As far as I can tell, this issue only occurs with functions that were defined in a separate package. If I try to define `($)` locally, or within a different module in the same package, then the issue does not occur.

**Comment by harpocrates** [comment]
The HTML and LaTeX backends each have a section to deal with properly printing types (see [this](https://github.com/haskell/haddock/blob/ghc-head/haddock-api/src/Haddock/Backends/Xhtml/Decl.hs#L1101) and  [this](https://github.com/haskell/haddock/blob/ghc-head/haddock-api/src/Haddock/Backends/LaTeX.hs#L904)). The Hoogle backend just uses the GHC `Outputable` instance.

I'll have a fix soon.
