### ISSUE TITLE
`tyThingToLHsDecl` expands some type aliases

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#879]
For

```
module Lib (_Right) where
import Lens.Micro
```

haddock generates

![image](https://user-images.githubusercontent.com/3664523/42765928-6cb1fdfc-8919-11e8-8931-4bfab6b1620e.png)

whereas the microlens haddocks show

![image](https://user-images.githubusercontent.com/3664523/42765995-952d9e1c-8919-11e8-82fb-80dc89106060.png)

@RyanGlScott explained this at https://github.com/sjakobi/haddock/issues/6#issuecomment-405270517:

> Ugh, I know why this is happening. It's due to these lines in `synifyType`:
>
> https://github.com/haskell/haddock/blob/4abf7d4979b5364da59f7412a3d7143aea26cf7e/haddock-api/src/Haddock/Convert.hs#L517-L520
>
> In particular, this calls [`tcSplitSigmaTy`](http://git.haskell.org/ghc.git/blob/8b6a9e5575fc848dc03b50b415aa57447654662f:/compiler/typecheck/TcType.hs#l1566), which in turn invokes two functions ([`splitForAllTys`](http://git.haskell.org/ghc.git/blob/71f6b18ba365da9ee4795f6cbce6ec9f1bfe95e8:/compiler/types/Type.hs#l1316) and [`tcSplitPredFunTy_maybe`](http://git.haskell.org/ghc.git/blob/71f6b18ba365da9ee4795f6cbce6ec9f1bfe95e8:/compiler/typecheck/TcType.hs#l1547)) that expand type synonyms. This also explains why this doesn't affect `type Unit = ()`, as this code is only ever called for types with a `forall` at the front.
>
> I'm not sure of a way to work around this other than developing a counterpart to `tcSplitSigmaTy` that doesn't expand type synonyms...

**Comment by sjakobi** [comment]
Ryan expanded on the fix he proposes:

```
RyanGlScott: sjakobi: It might be as simple as creating variants of those functions that don't call coreView
RyanGlScott: (coreView is what expands type synonyms)
```

I'll give this a try.

**Comment by sjakobi** [comment]
I have an `html-test` test for this:

```
module Bug879 (traverseCondTreeV) where

import Distribution.Types.CondTree
```

`Cabal`'s `Traversal` and `Lens` types seem to be the only synonyms containing a `forall` exposed from the boot libraries. Is it ok if I add this dependency on `Cabal`?

**Comment by RyanGlScott** [comment]
Can you not define your own version of `Lens` locally?

**Comment by sjakobi** [comment]
> Can you not define your own version of Lens locally?

AFAIK haddock currently only uses `tyThingToLHsDecl` for things from external packages (this changes with Hi Haddock). I guess I could add another package to this repo that exports what I need?!

**Comment by RyanGlScott** [comment]
Ah, I forgot about that. In that case, you could add a test for something of type `forall a. ReadS a` (where [`ReadS`](https://hackage.haskell.org/package/base-4.11.1.0/docs/Prelude.html#t:ReadS) is a type synonym defined in `base`).

**Comment by harpocrates** [comment]
> Is it ok if I add this dependency on Cabal?

I think it should suffice to add `Cabal` to the list of base dependencies, no? The dependency is only looked up when the tests are run.

https://github.com/haskell/haddock/blob/657b1b3d519545f8d4ca048c06210d6cbf0f0da0/haddock-test/src/Test/Haddock/Config.hs#L249-L255

**Comment by sjakobi** [comment]
@RyanGlScott 

> Ah, I forgot about that. In that case, you could add a test for something of type forall a. ReadS a (where ReadS is a type synonym defined in base).

I'm failing to find an example with that type that would trigger the bug. In fact, I don't see how such an example would exercise `tyThingToLHsDecl`.

@harpocrates 

Thanks for the pointer! I'm currently running into

```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 2.3.0.0 supports
'ghc' version < 8.7): /home/simon/src/ghc-hdk-879/inplace/bin/ghc-stage2 is
version 8.7.20180716
```

I might just delay adding the test case a bit then.

**Comment by sjakobi** [comment]
@harpocrates:

I now tried to add the test to the `ghc-8.4` branch, updating `pkgs` as you recommendad, but `html-test` now produces a huge diff involving lots of references to `Distribution.Compat.Prelude.Internal`.

Sample:

```
Diff for file "QuasiExpr.html":
61c61
< 		  > <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 		  > <a href="#" title="Prelude"
71c71
< 		  > <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 		  > <a href="#" title="Data.String"
95c95
< 		  > <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 		  > <a href="#" title="Data.String"
113c113
< 		      > <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 		      > <a href="#" title="Text.Show"
139c139
< 			  > :: <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > :: <a href="#" title="Data.Int"
143c143
< 			  > -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > -&gt; <a href="#" title="Text.Show"
153c153
< 			  > -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > -&gt; <a href="#" title="Data.String"
163c163
< 			  >] -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  >] -&gt; <a href="#" title="Text.Show"
233c233
< 		      > <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 		      > <a href="#" title="Text.Show"
259c259
< 			  > :: <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > :: <a href="#" title="Data.Int"
263c263
< 			  > -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > -&gt; <a href="#" title="Text.Show"
273c273
< 			  > -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  > -&gt; <a href="#" title="Data.String"
283c283
< 			  >] -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 			  >] -&gt; <a href="#" title="Text.Show"
302c302
< 	    > -&gt; <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 	    > -&gt; <a href="#" title="Prelude"
322c322
< 	    > :: <a href="#" title="Distribution.Compat.Prelude.Internal"
---
> 	    > :: <a href="#" title="Data.String"
```

Delaying the test case until the Hi Haddock changes have been merged seems like the easiest solution.

**Comment by RyanGlScott** [comment]
> I'm failing to find an example with that type that would trigger the bug. In fact, I don't see how such an example would exercise `tyThingToLHsDecl`.

Ugh, quite right. I overlooked the fact that it's not enough for the type synonym to be defined in an external package—the function with the type signature of `forall a. <TypeSynonym> a` must _also_ be defined in an external package. This, as it turns out, is surprisingly hard to find in a boot library. (Which is probably why this bug went unnoticed for so long!)

I'm starting to come around to the opinion that it would be wiser to wait until Hi Haddock lands before adding a test for this. Trying to depend on a heavy dependency like `Cabal` just for the sake of a regression test seems like overkill, in my opinion.

**Comment by harpocrates** [comment]
> I now tried to add the test to the ghc-8.4 branch, updating pkgs as you recommendad, but html-test now produces a huge diff involving lots of references to Distribution.Compat.Prelude.Internal.

I'm guessing you added `Cabal` to the front of the list instead of the back (and ran into what I think is basically https://github.com/haskell/haddock/issues/773). Adding it to the back should not cause tests currently passing to stop passing (I just tried it).

```haskell
       pkgs =
         [ "array"
         , "base"
         , "ghc-prim"
         , "process"
         , "template-haskell"
         , "Cabal"
         ]
```

> Trying to depend on a heavy dependency like `Cabal` just for the sake of a regression test seems like overkill, in my opinion.

But we don't need a dependency on `Cabal` in the `.cabal` file sense - we just need `Cabal` to be in the global package database when the tests are _run_ (which it already always is, given that it is a boot library). Besides, `haddock-test` even already depends on `Cabal` in the `.cabal` file sense:

https://github.com/haskell/haddock/blob/657b1b3d519545f8d4ca048c06210d6cbf0f0da0/haddock-test/haddock-test.cabal#L19

---

I just also want to be clear: I'm not trying to say we should not wait until Hi Haddock lands though, I'm just trying to clarify technical details.
