### ISSUE TITLE
Haddock tries to rename type variables

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#881]
I just noticed that we call `lookupRn` on type variables, for example `a` in the signature

```
print :: Show a => a -> IO ()
```

As we won't find type variables in the `LinkEnv` each of these lookups results in a call to `outRn` which doesn't look particularly efficient.

We later filter out these "missing names" in `renameInterface`:

https://github.com/haskell/haddock/blob/657b1b3d519545f8d4ca048c06210d6cbf0f0da0/haddock-api/src/Haddock/Interface/Rename.hs#L58-L75

**Comment by alexbiehl** [comment]
Uh, nice catch. Shouldn't be too hard to fix, right?


Simon Jakobi <notifications@github.com> schrieb am Di., 17. Juli 2018 um
15:57 Uhr:

**Comment by sjakobi** [comment]
> I think a couple of functions called by renameDecl need to be fixed.

Alternatively, we might just change `rename` to filter out type variables. That should be simpler.

**Comment by sjakobi** [comment]
`Name.isTyVarName` looks useful here.

**Comment by sjakobi** [comment]
Fixed in https://github.com/haskell/haddock/commit/d9c87e47afda04fd2bda380b81afca8e337a517c. 

Thanks @harpocrates! :)
