### ISSUE TITLE
Haddock fails on parallel execution

### ISSUE THREAD

**Issue by Profpatsch** [haskell/haddock#894]
As noted in [this issue](https://github.com/tweag/rules_haskell/issues/229):

> If haskell_doc is called with more than one job, the related instances of Haddock will concurrently try to create the same temporary directory, and fail the job.

There’s a bit of theorizing in our upstream issue how that could be.

@thumphries and @dleprovost, can you paste a log output of what happens exactly?
Maybe we can produce a bazel-less shell script that reproduces the issue.

**Comment by harpocrates** [comment]
Any hope of getting some sort of semi-reproducible test case for this? As observed in the thread you linked, the `withTempOutputDir` is designed specifically to work around this sort of issue (with `getProcessID`).

https://github.com/haskell/haddock/blob/39251d3aa339958aafd8b955f41323a8b0b60012/haddock-api/src/Haddock/Interface.hs#L142-L148

**Comment by Profpatsch** [comment]
I’d have to delegate to @thumphries for this one.

**Comment by thumphries** [comment]
When invoked via rules_haskell on certain distributions (Fedora 27 was one) haddock was seemingly running with reused low PIDs and crashing. I have no theory for why this might have been happening so it is going to be hard to reproduce. The system in question didn’t seem to be anywhere near PID_MAX, etc. something in the way bazel was invoking it

We fixed this in rules_haskell by running each invocation in a temporary directory. We could move that fix upstream here, I don’t feel strongly about it without a better explanation

**Comment by regnat** [comment]
> withTempOutputDir is designed specifically to work around this sort of issue (with getProcessID).

Bazel (and probably some other build systems) use PID namespacing for the builds. So it's definitely possible (and even likely) that two different invocations of haddock will get the same PID, hence the collision

**Comment by harpocrates** [comment]
> Bazel (and probably some other build systems) use PID namespacing for the builds.

That seems like the likely culprit, thanks for chiming in! At a glance, It seems like the best way forward is to just append some increasing number suffix to the generated directory names (I recall the `temporary` package does something similar; we should draw inspiration from there).

**Comment by Kleidukos** [comment]
Is this something that can solved at the Bazel level?

**Comment by Kleidukos** [comment]
Bazel support is being fixed at the level of Haddock with a one-shot mode. Closing this.
