### ISSUE TITLE
haddock --hoogle shouldn't require a version number

### ISSUE THREAD

**Issue by mboes** [haskell/haddock#898]
Let's say I have a simple library that I want to generate some Haddocks for:

```haskell
module Foo where

x = True
```

I don't want to make it a full Cabal package. I don't want to publish it on Hackage. Just call it library "foo" and generate some Haddocks and Hoogle for it. Unfortunately, I have to invent a version name too, or I'll get the following warning:

```
$ haddock --package-name="foo" -o haddock -h --hoogle Foo.hs
Haddock coverage:
   0% (  0 /  2) in 'Foo'
  Missing documentation for:
    Module header
    x (Foo.hs:3)
Warning: Foo: could not find link destinations for:
    Integer
haddock: Unable to find a package providing module Foo, skipping Hoogle.

         Perhaps try specifying the desired package explicitly using the --package-name
         and --package-version arguments.
```

Expected: that `--package-version` is optional even when `--hoogle` is turned on.

**Comment by alexbiehl** [comment]
I guess this was an oversight. Everything is implemented with package
version being optional except for the CLI arg parsing. That should be an
easy fix.

Mathieu Boespflug <notifications@github.com> schrieb am Mo., 6. Aug. 2018
um 10:10 Uhr:
