### ISSUE TITLE
Broken "Edit on GitHub" link on readthedocs

### ISSUE THREAD

**Issue by undergroundquizscene** [haskell/haddock#909]
At https://haskell-haddock.readthedocs.io/en/latest/intro.html), the "Edit on GitHub" button in the top right-hand corner points to https://github.com/haskell/haddock/blob/master/doc/intro.rst. However, there is no master branch on this repository, as far as I can see, so that link is a dead link.

**Comment by harpocrates** [comment]
@gbaz do you know how I could go about modifying https://haskell-haddock.readthedocs.io? It is going to need to be updated every time we switch GHC versions...

**Comment by gbaz** [comment]
I don't know how to modify it, no. I don't know who set it up, or how. Maybe there are some clues on the https://github.com/haskell/haddock/issues/360 ticket?

Why don't we just have a master branch?

**Comment by gbaz** [comment]
resolved on the linked ticket or thereabouts
