### ISSUE TITLE
Pattern synonyms aren't included in Hoogle output

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#946]
Originally from https://github.com/ndmitchell/hoogle/issues/261 reported by @ttuegel, if you look at https://hackage.haskell.org/package/containers-0.6.0.1/docs/containers.txt it lacks the pattern synonym `:<|`.

**Comment by harpocrates** [comment]
Ack. Sure enough, looks like the Hoogle backend does not do _anything_ with bundled patterns. Thanks for the bug report!
