### ISSUE TITLE
Packaging: deprecation of haddock-library 1.6.1 on Hackage

### ISSUE THREAD

**Issue by nekketsuuu** [haskell/haddock#950]
Now `haddock-library-1.6.1` cannot be installed easily because it has impossible dependency `base (>1 && <1)`. A commit 44169f4b1907e34fdf8ff84cf8b7509b1dfcaf55 says the following.

> Bump haddock-library to 1.7.0
> The 1.6.1 release should've been a major bump, since ....

So `haddock-library-1.6.1` is deprecated. Then how about explicitly deprecating 1.6.1 on Hackage? See <http://hackage.haskell.org/package/haddock-library/preferred> for details, and <https://stackoverflow.com/q/21724729/5989200> for a procedure.

Otherwise, for example, installation of `haddock-library (==1.6.*)` is a little difficult. Stack mistakenly recommend `haddock-library-1.6.1`, but actually `haddock-library-1.6.0` is needed. In my case, `stack install pandoc-2.3.1` recommended the following.

```
  * Recommended action: try adding the following to your extra-deps
    in C:\sr\global-project\stack.yaml:

- HsYAML-0.1.1.2
- haddock-library-1.6.1
- hslua-1.0.1
- hslua-module-text-0.2.0
```

**Comment by harpocrates** [comment]
Should be done now. Thanks for the suggestion!

**Comment by hvr** [comment]
I really wished Stack would be fixed instead of forcing us to do this kind of workarounds
