### ISSUE TITLE
The identifier parser should accept parenthesized operators like (+)

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#951]
The identifier parser doesn't accept `'(+)'` as a reference to `+`, and instead requires `@('+')@` which is very unreadable IMHO.

**Comment by sjakobi** [comment]
Maybe we should also consider rendering the entirety of `(+)` as a link, as the `+` inside is a very small target for the mouse cursor.

**Comment by harpocrates** [comment]
Fixed in a5199600c39d25d7b71dcb2328000c1c49ad95a2. Proof:

![screen shot 2019-02-25 at 9 22 17 am](https://user-images.githubusercontent.com/10766081/53355878-e8bb6080-38de-11e9-93a3-912da9443fd1.png)
