### ISSUE TITLE
Expander/collapser ids can conflict to easily

### ISSUE THREAD

**Issue by harpocrates** [haskell/haddock#953]
We do some work to generate HTML id's in a deterministic fashion. However, we're not trying hard enough to make them unique. Here's an example: 

```haskell
module Bug953 where

{- | A foo

==== __Examples__

Foo example body
-}
data Foo = Foo'

{- | A bar

==== __Examples__

Bar example body
-}
data Bar = Bar'
```

It is impossible to expand the first example section (clicking on the plus expands the second section!) because the two generated HTML elements are given the same `ch:noid:0` id.

**Comment by harpocrates** [comment]
@sjakobi This is what is causing the example section of `data [] a` to be unexpandable (the `Either` example gets expanded instead 😄).

**Comment by Lysxia** [comment]
I think I just got bitten by this: https://hackage.haskell.org/package/generic-data-0.8.0.0/docs/Generic-Data.html#t:FiniteEnum The "Details" link expands an Example link down below instead.

1. Is this the same issue?
2. Is it fixed?
3. How often does Hackage update Haddock?

**Comment by bgamari** [comment]
Hackage documentation is regenerated every time a package is uploaded.

However, haddock on the builder is uploaded significantly less frequently. I suspect it hasn't happened since this was fixed. I can check whether I still have permission to do so and will update it if so.
