### ISSUE TITLE
Bizarre HTML formatting of symbolic name

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#959]
I originally discovered this oddity in the [Haddocks for `singletons-2.5`](http://hackage.haskell.org/package/singletons-2.5/docs/Data-Singletons-TypeError.html#t::-36--36-:-64--35--64--36--36-). Here is a minimal example of how to trigger the issue:

```haskell
{-# LANGUAGE TypeOperators #-}
module Bug where

data (:$$:@#@$$)
```
```
$ haddock Bug.hs --html -o bug
Haddock coverage:
Warning: Package name is not available.
   0% (  0 /  2) in 'Bug'
  Missing documentation for:
    Module header
    :$$:@#@$$ (Bug.hs:4)
```
![haddock](https://user-images.githubusercontent.com/2364661/48002003-3e71c000-e0d8-11e8-865f-0821fb1abc6d.png)

**Comment by harpocrates** [comment]
You mean you didn't want MathJax to treat `$$:@#@$$` as a snippet of display-style math? 😉 

I imagine there must be a way to set up exclusions on MathJax; I'll take a look. Impressive bug in any case!
