### ISSUE TITLE
Blockquote styling is missing from both Ocean and NewOcean themes?

### ISSUE THREAD

**Issue by toonn** [haskell/haddock#967]
A while back I noticed hackage didn't style block quotes, which was confusing. This was fixed in haskell/hackage-server#776.
Could something like this be included in the haddock styles? I didn't find `blockquote` in the css files but I didn't look for something past that, maybe haddock doesn't produce blockquote elements.

I also have a minor complaint I didn't want to open a separate issue for. Could someone please think of a better name than `NewOcean` for the new theme? The previous one has fairly little to do with oceans afaics and this purple one has nothing to do with it. I know naming is a silly thing to argue about but what will the next one be called, NewNewOcean, NewestOcean? May I suggest `PurpleHaze`? : )

Some questions I don't know where else to direct:
  1. Is the style switcher gonna be a permanent feature?
  2. Will the style switcher be ported over to hackage?
  3. Could colors be factored out of themes some way? I'm all for structure and UX improvements but I'm personally kinda sad about all the purple. It'd be great if I could get the improvements but using the old colors.

**Comment by harpocrates** [comment]
> Could something like this be included in the haddock styles? I didn't find blockquote in the css files but I didn't look for something past that, maybe haddock doesn't produce blockquote elements. 

I don't think we produce blockquotes, but probably still worth putting in the CSS (for when somebody decides to start generating blockquotes). Would you like to open a PR?

> I also have a minor complaint I didn't want to open a separate issue for. Could someone please think of a better name than NewOcean for the new theme? The previous one has fairly little to do with oceans afaics and this purple one has nothing to do with it. I know naming is a silly thing to argue about but what will the next one be called, NewNewOcean, NewestOcean? May I suggest PurpleHaze? : )

Hehe, naming things is hard. @NunoAlexandre do you have a good reason for calling the theme "NewOcean"? If you not, wanna do the honors of coming up with a new name?

> Some questions I don't know where else to direct:
>
>  1.    Is the style switcher gonna be a permanent feature?
>  2.    Will the style switcher be ported over to hackage?
>  3.    Could colors be factored out of themes some way? I'm all for structure and UX improvements but I'm personally kinda sad about all the purple. It'd be great if I could get the improvements but using the old colors.

The style switcher was already a feature of Haddock (albeit a previously broken one). Just pass `--built-in-themes` to `haddock` (note that's not the same as `cabal new-haddock --built-in-themes` or `stack haddock --built-in-themes`!).

I don't think the style switcher is going to be enabled by default on Hackage. AFAIK, Hackage tries to do whatever `cabal new-haddock --haddock-for-hackage` does.

I'm not sure how to factor out the colors, besides just making a new theme that uses the current NewOcean theme as a starting point but draws inspiration from Ocean's colours, but maybe there is a way!

**Comment by NunoAlexandre** [comment]
> Hehe, naming things is hard. @NunoAlexandre do you have a good reason for calling the theme "NewOcean"? If you not, wanna do the honours of coming up with a new name?

@harpocrates, I didn't choose "NewOcean", didn't particularly liked it either ;) What about "Linuwial" or "Nazare" (The [beach with the biggest waves ever surfed](https://youtu.be/NTgAqH9MEeg?t=39), close to where I came from, if we want to keep the connection to oceans ;) )

**Comment by harpocrates** [comment]
It’s entirely your call. What do you like most? :)

**Comment by NunoAlexandre** [comment]
@harpocrates let's do "Linuwial" then ;) Thanks 👍

**Comment by toonn** [comment]
@harpocrates, ah, I guess I didn't think of the difference between what's on hackage, which often includes a README.md and just the haddocks for a project. I could do a PR if you want but I'm not sure it's necessary if haddocks never contain blockquotes anyway, unless hackage should just use haddock's themes?

**Comment by harpocrates** [comment]
> I could do a PR if you want but I'm not sure it's necessary if haddocks never contain blockquotes anyway, unless hackage should just use haddock's themes?

I doubt hackage is going to start using Haddock's theme. It is just less work from a development standpoint for them to duplicate the CSS. Personally, I lean very slightly towards wanting the blockquote CSS in the new theme since it'll future-proof us for when someone decides to start generating blockquotes.

> @harpocrates let's do "Linuwial" then ;) Thanks 👍

Done in a7a5ccec3fc44f3f2deab9ba32a5b9fe95aa9f6c.
