### ISSUE TITLE
Release 2.22.0 to Hackage?

### ISSUE THREAD

**Issue by neongreen** [haskell/haddock#975]
There's Haddock 2.22.0 in the Releases tab on Github, but it's not on Hackage. Is there a reason for that?

**Comment by harpocrates** [comment]
@hvr Do you want to do this, or should I?

**Comment by solpeth** [comment]
Hey all, can we still expect `haddock` and `haddock-api` to be released on hackage going forward?

**Comment by harpocrates** [comment]
This should be now done. Sorry for the delay. In the future, I'll make sure to release to Hackage shortly after the corresponding GHC release.

  * [`haddock-2.22.0`](https://hackage.haskell.org/package/haddock-2.22.0)
  * [`haddock-api-2.22.0`](https://hackage.haskell.org/package/haddock-api-2.22.0)
