### ISSUE TITLE
SIGSEGV when building haddocks for haskell-src-exts with hyperlinked sources

### ISSUE THREAD

**Issue by qrilka** [haskell/haddock#986]
The original ticket is https://github.com/haskell-suite/haskell-src-exts/issues/418 opening issue for Haddock on suggesttion from @mpickering

**Comment by harpocrates** [comment]
Duplicate of #837.

In a nutshell: this is fixed starting in 8.6.1, but not on any of 8.4.{1,2,3,4}.

**Comment by qrilka** [comment]
LTS-13.0 does the trick, thanks
